// Code generated by counterfeiter. DO NOT EDIT.
package snapshotfakes

import (
	"context"
	"io"
	"sync"

	"github.com/concourse/concourse/agent/snapshot"
)

type FakeContentStore struct {
	DeleteAllStub        func(context.Context, snapshot.Digest) error
	deleteAllMutex       sync.RWMutex
	deleteAllArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.Digest
	}
	deleteAllReturns struct {
		result1 error
	}
	deleteAllReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteLocationStub        func(context.Context, snapshot.Location) error
	deleteLocationMutex       sync.RWMutex
	deleteLocationArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.Location
	}
	deleteLocationReturns struct {
		result1 error
	}
	deleteLocationReturnsOnCall map[int]struct {
		result1 error
	}
	ExistsStub        func(context.Context, snapshot.Location) (bool, error)
	existsMutex       sync.RWMutex
	existsArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.Location
	}
	existsReturns struct {
		result1 bool
		result2 error
	}
	existsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	OpenStub        func(context.Context, snapshot.Snapshot) (io.ReadCloser, error)
	openMutex       sync.RWMutex
	openArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.Snapshot
	}
	openReturns struct {
		result1 io.ReadCloser
		result2 error
	}
	openReturnsOnCall map[int]struct {
		result1 io.ReadCloser
		result2 error
	}
	PutStub        func(context.Context, snapshot.Digest, io.Reader) ([]snapshot.Location, error)
	putMutex       sync.RWMutex
	putArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.Digest
		arg3 io.Reader
	}
	putReturns struct {
		result1 []snapshot.Location
		result2 error
	}
	putReturnsOnCall map[int]struct {
		result1 []snapshot.Location
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeContentStore) DeleteAll(arg1 context.Context, arg2 snapshot.Digest) error {
	fake.deleteAllMutex.Lock()
	ret, specificReturn := fake.deleteAllReturnsOnCall[len(fake.deleteAllArgsForCall)]
	fake.deleteAllArgsForCall = append(fake.deleteAllArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.Digest
	}{arg1, arg2})
	stub := fake.DeleteAllStub
	fakeReturns := fake.deleteAllReturns
	fake.recordInvocation("DeleteAll", []interface{}{arg1, arg2})
	fake.deleteAllMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeContentStore) DeleteAllCallCount() int {
	fake.deleteAllMutex.RLock()
	defer fake.deleteAllMutex.RUnlock()
	return len(fake.deleteAllArgsForCall)
}

func (fake *FakeContentStore) DeleteAllCalls(stub func(context.Context, snapshot.Digest) error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = stub
}

func (fake *FakeContentStore) DeleteAllArgsForCall(i int) (context.Context, snapshot.Digest) {
	fake.deleteAllMutex.RLock()
	defer fake.deleteAllMutex.RUnlock()
	argsForCall := fake.deleteAllArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeContentStore) DeleteAllReturns(result1 error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = nil
	fake.deleteAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeContentStore) DeleteAllReturnsOnCall(i int, result1 error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = nil
	if fake.deleteAllReturnsOnCall == nil {
		fake.deleteAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeContentStore) DeleteLocation(arg1 context.Context, arg2 snapshot.Location) error {
	fake.deleteLocationMutex.Lock()
	ret, specificReturn := fake.deleteLocationReturnsOnCall[len(fake.deleteLocationArgsForCall)]
	fake.deleteLocationArgsForCall = append(fake.deleteLocationArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.Location
	}{arg1, arg2})
	stub := fake.DeleteLocationStub
	fakeReturns := fake.deleteLocationReturns
	fake.recordInvocation("DeleteLocation", []interface{}{arg1, arg2})
	fake.deleteLocationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeContentStore) DeleteLocationCallCount() int {
	fake.deleteLocationMutex.RLock()
	defer fake.deleteLocationMutex.RUnlock()
	return len(fake.deleteLocationArgsForCall)
}

func (fake *FakeContentStore) DeleteLocationCalls(stub func(context.Context, snapshot.Location) error) {
	fake.deleteLocationMutex.Lock()
	defer fake.deleteLocationMutex.Unlock()
	fake.DeleteLocationStub = stub
}

func (fake *FakeContentStore) DeleteLocationArgsForCall(i int) (context.Context, snapshot.Location) {
	fake.deleteLocationMutex.RLock()
	defer fake.deleteLocationMutex.RUnlock()
	argsForCall := fake.deleteLocationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeContentStore) DeleteLocationReturns(result1 error) {
	fake.deleteLocationMutex.Lock()
	defer fake.deleteLocationMutex.Unlock()
	fake.DeleteLocationStub = nil
	fake.deleteLocationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeContentStore) DeleteLocationReturnsOnCall(i int, result1 error) {
	fake.deleteLocationMutex.Lock()
	defer fake.deleteLocationMutex.Unlock()
	fake.DeleteLocationStub = nil
	if fake.deleteLocationReturnsOnCall == nil {
		fake.deleteLocationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteLocationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeContentStore) Exists(arg1 context.Context, arg2 snapshot.Location) (bool, error) {
	fake.existsMutex.Lock()
	ret, specificReturn := fake.existsReturnsOnCall[len(fake.existsArgsForCall)]
	fake.existsArgsForCall = append(fake.existsArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.Location
	}{arg1, arg2})
	stub := fake.ExistsStub
	fakeReturns := fake.existsReturns
	fake.recordInvocation("Exists", []interface{}{arg1, arg2})
	fake.existsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeContentStore) ExistsCallCount() int {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return len(fake.existsArgsForCall)
}

func (fake *FakeContentStore) ExistsCalls(stub func(context.Context, snapshot.Location) (bool, error)) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = stub
}

func (fake *FakeContentStore) ExistsArgsForCall(i int) (context.Context, snapshot.Location) {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	argsForCall := fake.existsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeContentStore) ExistsReturns(result1 bool, result2 error) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	fake.existsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) ExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	if fake.existsReturnsOnCall == nil {
		fake.existsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.existsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) Open(arg1 context.Context, arg2 snapshot.Snapshot) (io.ReadCloser, error) {
	fake.openMutex.Lock()
	ret, specificReturn := fake.openReturnsOnCall[len(fake.openArgsForCall)]
	fake.openArgsForCall = append(fake.openArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.Snapshot
	}{arg1, arg2})
	stub := fake.OpenStub
	fakeReturns := fake.openReturns
	fake.recordInvocation("Open", []interface{}{arg1, arg2})
	fake.openMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeContentStore) OpenCallCount() int {
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	return len(fake.openArgsForCall)
}

func (fake *FakeContentStore) OpenCalls(stub func(context.Context, snapshot.Snapshot) (io.ReadCloser, error)) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = stub
}

func (fake *FakeContentStore) OpenArgsForCall(i int) (context.Context, snapshot.Snapshot) {
	fake.openMutex.RLock()
	defer fake.openMutex.RUnlock()
	argsForCall := fake.openArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeContentStore) OpenReturns(result1 io.ReadCloser, result2 error) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = nil
	fake.openReturns = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) OpenReturnsOnCall(i int, result1 io.ReadCloser, result2 error) {
	fake.openMutex.Lock()
	defer fake.openMutex.Unlock()
	fake.OpenStub = nil
	if fake.openReturnsOnCall == nil {
		fake.openReturnsOnCall = make(map[int]struct {
			result1 io.ReadCloser
			result2 error
		})
	}
	fake.openReturnsOnCall[i] = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) Put(arg1 context.Context, arg2 snapshot.Digest, arg3 io.Reader) ([]snapshot.Location, error) {
	fake.putMutex.Lock()
	ret, specificReturn := fake.putReturnsOnCall[len(fake.putArgsForCall)]
	fake.putArgsForCall = append(fake.putArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.Digest
		arg3 io.Reader
	}{arg1, arg2, arg3})
	stub := fake.PutStub
	fakeReturns := fake.putReturns
	fake.recordInvocation("Put", []interface{}{arg1, arg2, arg3})
	fake.putMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeContentStore) PutCallCount() int {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return len(fake.putArgsForCall)
}

func (fake *FakeContentStore) PutCalls(stub func(context.Context, snapshot.Digest, io.Reader) ([]snapshot.Location, error)) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = stub
}

func (fake *FakeContentStore) PutArgsForCall(i int) (context.Context, snapshot.Digest, io.Reader) {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	argsForCall := fake.putArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeContentStore) PutReturns(result1 []snapshot.Location, result2 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	fake.putReturns = struct {
		result1 []snapshot.Location
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) PutReturnsOnCall(i int, result1 []snapshot.Location, result2 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	if fake.putReturnsOnCall == nil {
		fake.putReturnsOnCall = make(map[int]struct {
			result1 []snapshot.Location
			result2 error
		})
	}
	fake.putReturnsOnCall[i] = struct {
		result1 []snapshot.Location
		result2 error
	}{result1, result2}
}

func (fake *FakeContentStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeContentStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ snapshot.ContentStore = new(FakeContentStore)
