// Code generated by counterfeiter. DO NOT EDIT.
package snapshotfakes

import (
	"context"
	"sync"
	"time"

	"github.com/concourse/concourse/agent/snapshot"
)

type FakeMetadataStore struct {
	AddLocationStub        func(context.Context, snapshot.DigestLease, snapshot.Location) error
	addLocationMutex       sync.RWMutex
	addLocationArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Location
	}
	addLocationReturns struct {
		result1 error
	}
	addLocationReturnsOnCall map[int]struct {
		result1 error
	}
	CommitSealBatchStub        func(context.Context, snapshot.DigestLease, snapshot.SealCommit) (map[string]snapshot.SealedOutput, error)
	commitSealBatchMutex       sync.RWMutex
	commitSealBatchArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.SealCommit
	}
	commitSealBatchReturns struct {
		result1 map[string]snapshot.SealedOutput
		result2 error
	}
	commitSealBatchReturnsOnCall map[int]struct {
		result1 map[string]snapshot.SealedOutput
		result2 error
	}
	DigestStateStub        func(context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) (snapshot.DigestState, error)
	digestStateMutex       sync.RWMutex
	digestStateArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 time.Time
	}
	digestStateReturns struct {
		result1 snapshot.DigestState
		result2 error
	}
	digestStateReturnsOnCall map[int]struct {
		result1 snapshot.DigestState
		result2 error
	}
	DiscoverLifecycleCandidatesStub        func(context.Context, snapshot.LifecyclePageRequest) (snapshot.LifecycleCandidatePage, error)
	discoverLifecycleCandidatesMutex       sync.RWMutex
	discoverLifecycleCandidatesArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.LifecyclePageRequest
	}
	discoverLifecycleCandidatesReturns struct {
		result1 snapshot.LifecycleCandidatePage
		result2 error
	}
	discoverLifecycleCandidatesReturnsOnCall map[int]struct {
		result1 snapshot.LifecycleCandidatePage
		result2 error
	}
	GetAuthorizedStub        func(context.Context, int, snapshot.SnapshotID) (snapshot.Snapshot, bool, error)
	getAuthorizedMutex       sync.RWMutex
	getAuthorizedArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotID
	}
	getAuthorizedReturns struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}
	getAuthorizedReturnsOnCall map[int]struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}
	ListAuthorizedStub        func(context.Context, int, snapshot.SnapshotListFilter) ([]snapshot.Snapshot, error)
	listAuthorizedMutex       sync.RWMutex
	listAuthorizedArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotListFilter
	}
	listAuthorizedReturns struct {
		result1 []snapshot.Snapshot
		result2 error
	}
	listAuthorizedReturnsOnCall map[int]struct {
		result1 []snapshot.Snapshot
		result2 error
	}
	MarkDigestExpiredStub        func(context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) (bool, error)
	markDigestExpiredMutex       sync.RWMutex
	markDigestExpiredArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 time.Time
	}
	markDigestExpiredReturns struct {
		result1 bool
		result2 error
	}
	markDigestExpiredReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	PinStub        func(context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef, string) (snapshot.RetentionClaim, error)
	pinMutex       sync.RWMutex
	pinArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 int
		arg4 string
		arg5 snapshot.SnapshotRef
		arg6 string
	}
	pinReturns struct {
		result1 snapshot.RetentionClaim
		result2 error
	}
	pinReturnsOnCall map[int]struct {
		result1 snapshot.RetentionClaim
		result2 error
	}
	RemoveLocationStub        func(context.Context, snapshot.DigestLease, snapshot.Location) error
	removeLocationMutex       sync.RWMutex
	removeLocationArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Location
	}
	removeLocationReturns struct {
		result1 error
	}
	removeLocationReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveStagedUploadsStub        func(context.Context, snapshot.DigestLease, snapshot.Digest, []int64) error
	removeStagedUploadsMutex       sync.RWMutex
	removeStagedUploadsArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 []int64
	}
	removeStagedUploadsReturns struct {
		result1 error
	}
	removeStagedUploadsReturnsOnCall map[int]struct {
		result1 error
	}
	StageUploadStub        func(context.Context, snapshot.DigestLease, snapshot.StageUploadRequest) (snapshot.StagedUpload, error)
	stageUploadMutex       sync.RWMutex
	stageUploadArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.StageUploadRequest
	}
	stageUploadReturns struct {
		result1 snapshot.StagedUpload
		result2 error
	}
	stageUploadReturnsOnCall map[int]struct {
		result1 snapshot.StagedUpload
		result2 error
	}
	UnpinStub        func(context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef) error
	unpinMutex       sync.RWMutex
	unpinArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 int
		arg4 string
		arg5 snapshot.SnapshotRef
	}
	unpinReturns struct {
		result1 error
	}
	unpinReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetadataStore) AddLocation(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.Location) error {
	fake.addLocationMutex.Lock()
	ret, specificReturn := fake.addLocationReturnsOnCall[len(fake.addLocationArgsForCall)]
	fake.addLocationArgsForCall = append(fake.addLocationArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Location
	}{arg1, arg2, arg3})
	stub := fake.AddLocationStub
	fakeReturns := fake.addLocationReturns
	fake.recordInvocation("AddLocation", []interface{}{arg1, arg2, arg3})
	fake.addLocationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMetadataStore) AddLocationCallCount() int {
	fake.addLocationMutex.RLock()
	defer fake.addLocationMutex.RUnlock()
	return len(fake.addLocationArgsForCall)
}

func (fake *FakeMetadataStore) AddLocationCalls(stub func(context.Context, snapshot.DigestLease, snapshot.Location) error) {
	fake.addLocationMutex.Lock()
	defer fake.addLocationMutex.Unlock()
	fake.AddLocationStub = stub
}

func (fake *FakeMetadataStore) AddLocationArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.Location) {
	fake.addLocationMutex.RLock()
	defer fake.addLocationMutex.RUnlock()
	argsForCall := fake.addLocationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) AddLocationReturns(result1 error) {
	fake.addLocationMutex.Lock()
	defer fake.addLocationMutex.Unlock()
	fake.AddLocationStub = nil
	fake.addLocationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) AddLocationReturnsOnCall(i int, result1 error) {
	fake.addLocationMutex.Lock()
	defer fake.addLocationMutex.Unlock()
	fake.AddLocationStub = nil
	if fake.addLocationReturnsOnCall == nil {
		fake.addLocationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addLocationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) CommitSealBatch(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.SealCommit) (map[string]snapshot.SealedOutput, error) {
	fake.commitSealBatchMutex.Lock()
	ret, specificReturn := fake.commitSealBatchReturnsOnCall[len(fake.commitSealBatchArgsForCall)]
	fake.commitSealBatchArgsForCall = append(fake.commitSealBatchArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.SealCommit
	}{arg1, arg2, arg3})
	stub := fake.CommitSealBatchStub
	fakeReturns := fake.commitSealBatchReturns
	fake.recordInvocation("CommitSealBatch", []interface{}{arg1, arg2, arg3})
	fake.commitSealBatchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) CommitSealBatchCallCount() int {
	fake.commitSealBatchMutex.RLock()
	defer fake.commitSealBatchMutex.RUnlock()
	return len(fake.commitSealBatchArgsForCall)
}

func (fake *FakeMetadataStore) CommitSealBatchCalls(stub func(context.Context, snapshot.DigestLease, snapshot.SealCommit) (map[string]snapshot.SealedOutput, error)) {
	fake.commitSealBatchMutex.Lock()
	defer fake.commitSealBatchMutex.Unlock()
	fake.CommitSealBatchStub = stub
}

func (fake *FakeMetadataStore) CommitSealBatchArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.SealCommit) {
	fake.commitSealBatchMutex.RLock()
	defer fake.commitSealBatchMutex.RUnlock()
	argsForCall := fake.commitSealBatchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) CommitSealBatchReturns(result1 map[string]snapshot.SealedOutput, result2 error) {
	fake.commitSealBatchMutex.Lock()
	defer fake.commitSealBatchMutex.Unlock()
	fake.CommitSealBatchStub = nil
	fake.commitSealBatchReturns = struct {
		result1 map[string]snapshot.SealedOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) CommitSealBatchReturnsOnCall(i int, result1 map[string]snapshot.SealedOutput, result2 error) {
	fake.commitSealBatchMutex.Lock()
	defer fake.commitSealBatchMutex.Unlock()
	fake.CommitSealBatchStub = nil
	if fake.commitSealBatchReturnsOnCall == nil {
		fake.commitSealBatchReturnsOnCall = make(map[int]struct {
			result1 map[string]snapshot.SealedOutput
			result2 error
		})
	}
	fake.commitSealBatchReturnsOnCall[i] = struct {
		result1 map[string]snapshot.SealedOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) DigestState(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.Digest, arg4 time.Time) (snapshot.DigestState, error) {
	fake.digestStateMutex.Lock()
	ret, specificReturn := fake.digestStateReturnsOnCall[len(fake.digestStateArgsForCall)]
	fake.digestStateArgsForCall = append(fake.digestStateArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.DigestStateStub
	fakeReturns := fake.digestStateReturns
	fake.recordInvocation("DigestState", []interface{}{arg1, arg2, arg3, arg4})
	fake.digestStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) DigestStateCallCount() int {
	fake.digestStateMutex.RLock()
	defer fake.digestStateMutex.RUnlock()
	return len(fake.digestStateArgsForCall)
}

func (fake *FakeMetadataStore) DigestStateCalls(stub func(context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) (snapshot.DigestState, error)) {
	fake.digestStateMutex.Lock()
	defer fake.digestStateMutex.Unlock()
	fake.DigestStateStub = stub
}

func (fake *FakeMetadataStore) DigestStateArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) {
	fake.digestStateMutex.RLock()
	defer fake.digestStateMutex.RUnlock()
	argsForCall := fake.digestStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMetadataStore) DigestStateReturns(result1 snapshot.DigestState, result2 error) {
	fake.digestStateMutex.Lock()
	defer fake.digestStateMutex.Unlock()
	fake.DigestStateStub = nil
	fake.digestStateReturns = struct {
		result1 snapshot.DigestState
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) DigestStateReturnsOnCall(i int, result1 snapshot.DigestState, result2 error) {
	fake.digestStateMutex.Lock()
	defer fake.digestStateMutex.Unlock()
	fake.DigestStateStub = nil
	if fake.digestStateReturnsOnCall == nil {
		fake.digestStateReturnsOnCall = make(map[int]struct {
			result1 snapshot.DigestState
			result2 error
		})
	}
	fake.digestStateReturnsOnCall[i] = struct {
		result1 snapshot.DigestState
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidates(arg1 context.Context, arg2 snapshot.LifecyclePageRequest) (snapshot.LifecycleCandidatePage, error) {
	fake.discoverLifecycleCandidatesMutex.Lock()
	ret, specificReturn := fake.discoverLifecycleCandidatesReturnsOnCall[len(fake.discoverLifecycleCandidatesArgsForCall)]
	fake.discoverLifecycleCandidatesArgsForCall = append(fake.discoverLifecycleCandidatesArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.LifecyclePageRequest
	}{arg1, arg2})
	stub := fake.DiscoverLifecycleCandidatesStub
	fakeReturns := fake.discoverLifecycleCandidatesReturns
	fake.recordInvocation("DiscoverLifecycleCandidates", []interface{}{arg1, arg2})
	fake.discoverLifecycleCandidatesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidatesCallCount() int {
	fake.discoverLifecycleCandidatesMutex.RLock()
	defer fake.discoverLifecycleCandidatesMutex.RUnlock()
	return len(fake.discoverLifecycleCandidatesArgsForCall)
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidatesCalls(stub func(context.Context, snapshot.LifecyclePageRequest) (snapshot.LifecycleCandidatePage, error)) {
	fake.discoverLifecycleCandidatesMutex.Lock()
	defer fake.discoverLifecycleCandidatesMutex.Unlock()
	fake.DiscoverLifecycleCandidatesStub = stub
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidatesArgsForCall(i int) (context.Context, snapshot.LifecyclePageRequest) {
	fake.discoverLifecycleCandidatesMutex.RLock()
	defer fake.discoverLifecycleCandidatesMutex.RUnlock()
	argsForCall := fake.discoverLifecycleCandidatesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidatesReturns(result1 snapshot.LifecycleCandidatePage, result2 error) {
	fake.discoverLifecycleCandidatesMutex.Lock()
	defer fake.discoverLifecycleCandidatesMutex.Unlock()
	fake.DiscoverLifecycleCandidatesStub = nil
	fake.discoverLifecycleCandidatesReturns = struct {
		result1 snapshot.LifecycleCandidatePage
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) DiscoverLifecycleCandidatesReturnsOnCall(i int, result1 snapshot.LifecycleCandidatePage, result2 error) {
	fake.discoverLifecycleCandidatesMutex.Lock()
	defer fake.discoverLifecycleCandidatesMutex.Unlock()
	fake.DiscoverLifecycleCandidatesStub = nil
	if fake.discoverLifecycleCandidatesReturnsOnCall == nil {
		fake.discoverLifecycleCandidatesReturnsOnCall = make(map[int]struct {
			result1 snapshot.LifecycleCandidatePage
			result2 error
		})
	}
	fake.discoverLifecycleCandidatesReturnsOnCall[i] = struct {
		result1 snapshot.LifecycleCandidatePage
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) GetAuthorized(arg1 context.Context, arg2 int, arg3 snapshot.SnapshotID) (snapshot.Snapshot, bool, error) {
	fake.getAuthorizedMutex.Lock()
	ret, specificReturn := fake.getAuthorizedReturnsOnCall[len(fake.getAuthorizedArgsForCall)]
	fake.getAuthorizedArgsForCall = append(fake.getAuthorizedArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotID
	}{arg1, arg2, arg3})
	stub := fake.GetAuthorizedStub
	fakeReturns := fake.getAuthorizedReturns
	fake.recordInvocation("GetAuthorized", []interface{}{arg1, arg2, arg3})
	fake.getAuthorizedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeMetadataStore) GetAuthorizedCallCount() int {
	fake.getAuthorizedMutex.RLock()
	defer fake.getAuthorizedMutex.RUnlock()
	return len(fake.getAuthorizedArgsForCall)
}

func (fake *FakeMetadataStore) GetAuthorizedCalls(stub func(context.Context, int, snapshot.SnapshotID) (snapshot.Snapshot, bool, error)) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = stub
}

func (fake *FakeMetadataStore) GetAuthorizedArgsForCall(i int) (context.Context, int, snapshot.SnapshotID) {
	fake.getAuthorizedMutex.RLock()
	defer fake.getAuthorizedMutex.RUnlock()
	argsForCall := fake.getAuthorizedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) GetAuthorizedReturns(result1 snapshot.Snapshot, result2 bool, result3 error) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = nil
	fake.getAuthorizedReturns = struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMetadataStore) GetAuthorizedReturnsOnCall(i int, result1 snapshot.Snapshot, result2 bool, result3 error) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = nil
	if fake.getAuthorizedReturnsOnCall == nil {
		fake.getAuthorizedReturnsOnCall = make(map[int]struct {
			result1 snapshot.Snapshot
			result2 bool
			result3 error
		})
	}
	fake.getAuthorizedReturnsOnCall[i] = struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMetadataStore) ListAuthorized(arg1 context.Context, arg2 int, arg3 snapshot.SnapshotListFilter) ([]snapshot.Snapshot, error) {
	fake.listAuthorizedMutex.Lock()
	ret, specificReturn := fake.listAuthorizedReturnsOnCall[len(fake.listAuthorizedArgsForCall)]
	fake.listAuthorizedArgsForCall = append(fake.listAuthorizedArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotListFilter
	}{arg1, arg2, arg3})
	stub := fake.ListAuthorizedStub
	fakeReturns := fake.listAuthorizedReturns
	fake.recordInvocation("ListAuthorized", []interface{}{arg1, arg2, arg3})
	fake.listAuthorizedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) ListAuthorizedCallCount() int {
	fake.listAuthorizedMutex.RLock()
	defer fake.listAuthorizedMutex.RUnlock()
	return len(fake.listAuthorizedArgsForCall)
}

func (fake *FakeMetadataStore) ListAuthorizedCalls(stub func(context.Context, int, snapshot.SnapshotListFilter) ([]snapshot.Snapshot, error)) {
	fake.listAuthorizedMutex.Lock()
	defer fake.listAuthorizedMutex.Unlock()
	fake.ListAuthorizedStub = stub
}

func (fake *FakeMetadataStore) ListAuthorizedArgsForCall(i int) (context.Context, int, snapshot.SnapshotListFilter) {
	fake.listAuthorizedMutex.RLock()
	defer fake.listAuthorizedMutex.RUnlock()
	argsForCall := fake.listAuthorizedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) ListAuthorizedReturns(result1 []snapshot.Snapshot, result2 error) {
	fake.listAuthorizedMutex.Lock()
	defer fake.listAuthorizedMutex.Unlock()
	fake.ListAuthorizedStub = nil
	fake.listAuthorizedReturns = struct {
		result1 []snapshot.Snapshot
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) ListAuthorizedReturnsOnCall(i int, result1 []snapshot.Snapshot, result2 error) {
	fake.listAuthorizedMutex.Lock()
	defer fake.listAuthorizedMutex.Unlock()
	fake.ListAuthorizedStub = nil
	if fake.listAuthorizedReturnsOnCall == nil {
		fake.listAuthorizedReturnsOnCall = make(map[int]struct {
			result1 []snapshot.Snapshot
			result2 error
		})
	}
	fake.listAuthorizedReturnsOnCall[i] = struct {
		result1 []snapshot.Snapshot
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) MarkDigestExpired(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.Digest, arg4 time.Time) (bool, error) {
	fake.markDigestExpiredMutex.Lock()
	ret, specificReturn := fake.markDigestExpiredReturnsOnCall[len(fake.markDigestExpiredArgsForCall)]
	fake.markDigestExpiredArgsForCall = append(fake.markDigestExpiredArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 time.Time
	}{arg1, arg2, arg3, arg4})
	stub := fake.MarkDigestExpiredStub
	fakeReturns := fake.markDigestExpiredReturns
	fake.recordInvocation("MarkDigestExpired", []interface{}{arg1, arg2, arg3, arg4})
	fake.markDigestExpiredMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) MarkDigestExpiredCallCount() int {
	fake.markDigestExpiredMutex.RLock()
	defer fake.markDigestExpiredMutex.RUnlock()
	return len(fake.markDigestExpiredArgsForCall)
}

func (fake *FakeMetadataStore) MarkDigestExpiredCalls(stub func(context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) (bool, error)) {
	fake.markDigestExpiredMutex.Lock()
	defer fake.markDigestExpiredMutex.Unlock()
	fake.MarkDigestExpiredStub = stub
}

func (fake *FakeMetadataStore) MarkDigestExpiredArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.Digest, time.Time) {
	fake.markDigestExpiredMutex.RLock()
	defer fake.markDigestExpiredMutex.RUnlock()
	argsForCall := fake.markDigestExpiredArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMetadataStore) MarkDigestExpiredReturns(result1 bool, result2 error) {
	fake.markDigestExpiredMutex.Lock()
	defer fake.markDigestExpiredMutex.Unlock()
	fake.MarkDigestExpiredStub = nil
	fake.markDigestExpiredReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) MarkDigestExpiredReturnsOnCall(i int, result1 bool, result2 error) {
	fake.markDigestExpiredMutex.Lock()
	defer fake.markDigestExpiredMutex.Unlock()
	fake.MarkDigestExpiredStub = nil
	if fake.markDigestExpiredReturnsOnCall == nil {
		fake.markDigestExpiredReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.markDigestExpiredReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) Pin(arg1 context.Context, arg2 snapshot.DigestLease, arg3 int, arg4 string, arg5 snapshot.SnapshotRef, arg6 string) (snapshot.RetentionClaim, error) {
	fake.pinMutex.Lock()
	ret, specificReturn := fake.pinReturnsOnCall[len(fake.pinArgsForCall)]
	fake.pinArgsForCall = append(fake.pinArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 int
		arg4 string
		arg5 snapshot.SnapshotRef
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.PinStub
	fakeReturns := fake.pinReturns
	fake.recordInvocation("Pin", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.pinMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) PinCallCount() int {
	fake.pinMutex.RLock()
	defer fake.pinMutex.RUnlock()
	return len(fake.pinArgsForCall)
}

func (fake *FakeMetadataStore) PinCalls(stub func(context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef, string) (snapshot.RetentionClaim, error)) {
	fake.pinMutex.Lock()
	defer fake.pinMutex.Unlock()
	fake.PinStub = stub
}

func (fake *FakeMetadataStore) PinArgsForCall(i int) (context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef, string) {
	fake.pinMutex.RLock()
	defer fake.pinMutex.RUnlock()
	argsForCall := fake.pinArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeMetadataStore) PinReturns(result1 snapshot.RetentionClaim, result2 error) {
	fake.pinMutex.Lock()
	defer fake.pinMutex.Unlock()
	fake.PinStub = nil
	fake.pinReturns = struct {
		result1 snapshot.RetentionClaim
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) PinReturnsOnCall(i int, result1 snapshot.RetentionClaim, result2 error) {
	fake.pinMutex.Lock()
	defer fake.pinMutex.Unlock()
	fake.PinStub = nil
	if fake.pinReturnsOnCall == nil {
		fake.pinReturnsOnCall = make(map[int]struct {
			result1 snapshot.RetentionClaim
			result2 error
		})
	}
	fake.pinReturnsOnCall[i] = struct {
		result1 snapshot.RetentionClaim
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) RemoveLocation(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.Location) error {
	fake.removeLocationMutex.Lock()
	ret, specificReturn := fake.removeLocationReturnsOnCall[len(fake.removeLocationArgsForCall)]
	fake.removeLocationArgsForCall = append(fake.removeLocationArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Location
	}{arg1, arg2, arg3})
	stub := fake.RemoveLocationStub
	fakeReturns := fake.removeLocationReturns
	fake.recordInvocation("RemoveLocation", []interface{}{arg1, arg2, arg3})
	fake.removeLocationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMetadataStore) RemoveLocationCallCount() int {
	fake.removeLocationMutex.RLock()
	defer fake.removeLocationMutex.RUnlock()
	return len(fake.removeLocationArgsForCall)
}

func (fake *FakeMetadataStore) RemoveLocationCalls(stub func(context.Context, snapshot.DigestLease, snapshot.Location) error) {
	fake.removeLocationMutex.Lock()
	defer fake.removeLocationMutex.Unlock()
	fake.RemoveLocationStub = stub
}

func (fake *FakeMetadataStore) RemoveLocationArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.Location) {
	fake.removeLocationMutex.RLock()
	defer fake.removeLocationMutex.RUnlock()
	argsForCall := fake.removeLocationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) RemoveLocationReturns(result1 error) {
	fake.removeLocationMutex.Lock()
	defer fake.removeLocationMutex.Unlock()
	fake.RemoveLocationStub = nil
	fake.removeLocationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) RemoveLocationReturnsOnCall(i int, result1 error) {
	fake.removeLocationMutex.Lock()
	defer fake.removeLocationMutex.Unlock()
	fake.RemoveLocationStub = nil
	if fake.removeLocationReturnsOnCall == nil {
		fake.removeLocationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeLocationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) RemoveStagedUploads(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.Digest, arg4 []int64) error {
	var arg4Copy []int64
	if arg4 != nil {
		arg4Copy = make([]int64, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.removeStagedUploadsMutex.Lock()
	ret, specificReturn := fake.removeStagedUploadsReturnsOnCall[len(fake.removeStagedUploadsArgsForCall)]
	fake.removeStagedUploadsArgsForCall = append(fake.removeStagedUploadsArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.Digest
		arg4 []int64
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.RemoveStagedUploadsStub
	fakeReturns := fake.removeStagedUploadsReturns
	fake.recordInvocation("RemoveStagedUploads", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.removeStagedUploadsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMetadataStore) RemoveStagedUploadsCallCount() int {
	fake.removeStagedUploadsMutex.RLock()
	defer fake.removeStagedUploadsMutex.RUnlock()
	return len(fake.removeStagedUploadsArgsForCall)
}

func (fake *FakeMetadataStore) RemoveStagedUploadsCalls(stub func(context.Context, snapshot.DigestLease, snapshot.Digest, []int64) error) {
	fake.removeStagedUploadsMutex.Lock()
	defer fake.removeStagedUploadsMutex.Unlock()
	fake.RemoveStagedUploadsStub = stub
}

func (fake *FakeMetadataStore) RemoveStagedUploadsArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.Digest, []int64) {
	fake.removeStagedUploadsMutex.RLock()
	defer fake.removeStagedUploadsMutex.RUnlock()
	argsForCall := fake.removeStagedUploadsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMetadataStore) RemoveStagedUploadsReturns(result1 error) {
	fake.removeStagedUploadsMutex.Lock()
	defer fake.removeStagedUploadsMutex.Unlock()
	fake.RemoveStagedUploadsStub = nil
	fake.removeStagedUploadsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) RemoveStagedUploadsReturnsOnCall(i int, result1 error) {
	fake.removeStagedUploadsMutex.Lock()
	defer fake.removeStagedUploadsMutex.Unlock()
	fake.RemoveStagedUploadsStub = nil
	if fake.removeStagedUploadsReturnsOnCall == nil {
		fake.removeStagedUploadsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeStagedUploadsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) StageUpload(arg1 context.Context, arg2 snapshot.DigestLease, arg3 snapshot.StageUploadRequest) (snapshot.StagedUpload, error) {
	fake.stageUploadMutex.Lock()
	ret, specificReturn := fake.stageUploadReturnsOnCall[len(fake.stageUploadArgsForCall)]
	fake.stageUploadArgsForCall = append(fake.stageUploadArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 snapshot.StageUploadRequest
	}{arg1, arg2, arg3})
	stub := fake.StageUploadStub
	fakeReturns := fake.stageUploadReturns
	fake.recordInvocation("StageUpload", []interface{}{arg1, arg2, arg3})
	fake.stageUploadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataStore) StageUploadCallCount() int {
	fake.stageUploadMutex.RLock()
	defer fake.stageUploadMutex.RUnlock()
	return len(fake.stageUploadArgsForCall)
}

func (fake *FakeMetadataStore) StageUploadCalls(stub func(context.Context, snapshot.DigestLease, snapshot.StageUploadRequest) (snapshot.StagedUpload, error)) {
	fake.stageUploadMutex.Lock()
	defer fake.stageUploadMutex.Unlock()
	fake.StageUploadStub = stub
}

func (fake *FakeMetadataStore) StageUploadArgsForCall(i int) (context.Context, snapshot.DigestLease, snapshot.StageUploadRequest) {
	fake.stageUploadMutex.RLock()
	defer fake.stageUploadMutex.RUnlock()
	argsForCall := fake.stageUploadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMetadataStore) StageUploadReturns(result1 snapshot.StagedUpload, result2 error) {
	fake.stageUploadMutex.Lock()
	defer fake.stageUploadMutex.Unlock()
	fake.StageUploadStub = nil
	fake.stageUploadReturns = struct {
		result1 snapshot.StagedUpload
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) StageUploadReturnsOnCall(i int, result1 snapshot.StagedUpload, result2 error) {
	fake.stageUploadMutex.Lock()
	defer fake.stageUploadMutex.Unlock()
	fake.StageUploadStub = nil
	if fake.stageUploadReturnsOnCall == nil {
		fake.stageUploadReturnsOnCall = make(map[int]struct {
			result1 snapshot.StagedUpload
			result2 error
		})
	}
	fake.stageUploadReturnsOnCall[i] = struct {
		result1 snapshot.StagedUpload
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataStore) Unpin(arg1 context.Context, arg2 snapshot.DigestLease, arg3 int, arg4 string, arg5 snapshot.SnapshotRef) error {
	fake.unpinMutex.Lock()
	ret, specificReturn := fake.unpinReturnsOnCall[len(fake.unpinArgsForCall)]
	fake.unpinArgsForCall = append(fake.unpinArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.DigestLease
		arg3 int
		arg4 string
		arg5 snapshot.SnapshotRef
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.UnpinStub
	fakeReturns := fake.unpinReturns
	fake.recordInvocation("Unpin", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.unpinMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMetadataStore) UnpinCallCount() int {
	fake.unpinMutex.RLock()
	defer fake.unpinMutex.RUnlock()
	return len(fake.unpinArgsForCall)
}

func (fake *FakeMetadataStore) UnpinCalls(stub func(context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef) error) {
	fake.unpinMutex.Lock()
	defer fake.unpinMutex.Unlock()
	fake.UnpinStub = stub
}

func (fake *FakeMetadataStore) UnpinArgsForCall(i int) (context.Context, snapshot.DigestLease, int, string, snapshot.SnapshotRef) {
	fake.unpinMutex.RLock()
	defer fake.unpinMutex.RUnlock()
	argsForCall := fake.unpinArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMetadataStore) UnpinReturns(result1 error) {
	fake.unpinMutex.Lock()
	defer fake.unpinMutex.Unlock()
	fake.UnpinStub = nil
	fake.unpinReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) UnpinReturnsOnCall(i int, result1 error) {
	fake.unpinMutex.Lock()
	defer fake.unpinMutex.Unlock()
	fake.UnpinStub = nil
	if fake.unpinReturnsOnCall == nil {
		fake.unpinReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unpinReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetadataStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetadataStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ snapshot.MetadataStore = new(FakeMetadataStore)
