// Code generated by counterfeiter. DO NOT EDIT.
package credentialsfakes

import (
	"sync"
	"time"

	"github.com/concourse/concourse/agent/credentials"
)

type FakeStore struct {
	DeleteStub        func(int, string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 int
		arg2 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	ExpiringWithinStub        func(time.Duration) ([]credentials.Credential, error)
	expiringWithinMutex       sync.RWMutex
	expiringWithinArgsForCall []struct {
		arg1 time.Duration
	}
	expiringWithinReturns struct {
		result1 []credentials.Credential
		result2 error
	}
	expiringWithinReturnsOnCall map[int]struct {
		result1 []credentials.Credential
		result2 error
	}
	PutStub        func(int, string, string, string, time.Time) error
	putMutex       sync.RWMutex
	putArgsForCall []struct {
		arg1 int
		arg2 string
		arg3 string
		arg4 string
		arg5 time.Time
	}
	putReturns struct {
		result1 error
	}
	putReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveStub        func(int, string) (*credentials.Credential, bool, error)
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 int
		arg2 string
	}
	resolveReturns struct {
		result1 *credentials.Credential
		result2 bool
		result3 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 *credentials.Credential
		result2 bool
		result3 error
	}
	StatusStub        func(int) ([]credentials.Credential, error)
	statusMutex       sync.RWMutex
	statusArgsForCall []struct {
		arg1 int
	}
	statusReturns struct {
		result1 []credentials.Credential
		result2 error
	}
	statusReturnsOnCall map[int]struct {
		result1 []credentials.Credential
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) Delete(arg1 int, arg2 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeStore) DeleteCalls(stub func(int, string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeStore) DeleteArgsForCall(i int) (int, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) ExpiringWithin(arg1 time.Duration) ([]credentials.Credential, error) {
	fake.expiringWithinMutex.Lock()
	ret, specificReturn := fake.expiringWithinReturnsOnCall[len(fake.expiringWithinArgsForCall)]
	fake.expiringWithinArgsForCall = append(fake.expiringWithinArgsForCall, struct {
		arg1 time.Duration
	}{arg1})
	stub := fake.ExpiringWithinStub
	fakeReturns := fake.expiringWithinReturns
	fake.recordInvocation("ExpiringWithin", []interface{}{arg1})
	fake.expiringWithinMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ExpiringWithinCallCount() int {
	fake.expiringWithinMutex.RLock()
	defer fake.expiringWithinMutex.RUnlock()
	return len(fake.expiringWithinArgsForCall)
}

func (fake *FakeStore) ExpiringWithinCalls(stub func(time.Duration) ([]credentials.Credential, error)) {
	fake.expiringWithinMutex.Lock()
	defer fake.expiringWithinMutex.Unlock()
	fake.ExpiringWithinStub = stub
}

func (fake *FakeStore) ExpiringWithinArgsForCall(i int) time.Duration {
	fake.expiringWithinMutex.RLock()
	defer fake.expiringWithinMutex.RUnlock()
	argsForCall := fake.expiringWithinArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) ExpiringWithinReturns(result1 []credentials.Credential, result2 error) {
	fake.expiringWithinMutex.Lock()
	defer fake.expiringWithinMutex.Unlock()
	fake.ExpiringWithinStub = nil
	fake.expiringWithinReturns = struct {
		result1 []credentials.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ExpiringWithinReturnsOnCall(i int, result1 []credentials.Credential, result2 error) {
	fake.expiringWithinMutex.Lock()
	defer fake.expiringWithinMutex.Unlock()
	fake.ExpiringWithinStub = nil
	if fake.expiringWithinReturnsOnCall == nil {
		fake.expiringWithinReturnsOnCall = make(map[int]struct {
			result1 []credentials.Credential
			result2 error
		})
	}
	fake.expiringWithinReturnsOnCall[i] = struct {
		result1 []credentials.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Put(arg1 int, arg2 string, arg3 string, arg4 string, arg5 time.Time) error {
	fake.putMutex.Lock()
	ret, specificReturn := fake.putReturnsOnCall[len(fake.putArgsForCall)]
	fake.putArgsForCall = append(fake.putArgsForCall, struct {
		arg1 int
		arg2 string
		arg3 string
		arg4 string
		arg5 time.Time
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PutStub
	fakeReturns := fake.putReturns
	fake.recordInvocation("Put", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.putMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) PutCallCount() int {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	return len(fake.putArgsForCall)
}

func (fake *FakeStore) PutCalls(stub func(int, string, string, string, time.Time) error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = stub
}

func (fake *FakeStore) PutArgsForCall(i int) (int, string, string, string, time.Time) {
	fake.putMutex.RLock()
	defer fake.putMutex.RUnlock()
	argsForCall := fake.putArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeStore) PutReturns(result1 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	fake.putReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) PutReturnsOnCall(i int, result1 error) {
	fake.putMutex.Lock()
	defer fake.putMutex.Unlock()
	fake.PutStub = nil
	if fake.putReturnsOnCall == nil {
		fake.putReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) Resolve(arg1 int, arg2 string) (*credentials.Credential, bool, error) {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	stub := fake.ResolveStub
	fakeReturns := fake.resolveReturns
	fake.recordInvocation("Resolve", []interface{}{arg1, arg2})
	fake.resolveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeStore) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *FakeStore) ResolveCalls(stub func(int, string) (*credentials.Credential, bool, error)) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *FakeStore) ResolveArgsForCall(i int) (int, string) {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) ResolveReturns(result1 *credentials.Credential, result2 bool, result3 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 *credentials.Credential
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStore) ResolveReturnsOnCall(i int, result1 *credentials.Credential, result2 bool, result3 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 *credentials.Credential
			result2 bool
			result3 error
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 *credentials.Credential
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStore) Status(arg1 int) ([]credentials.Credential, error) {
	fake.statusMutex.Lock()
	ret, specificReturn := fake.statusReturnsOnCall[len(fake.statusArgsForCall)]
	fake.statusArgsForCall = append(fake.statusArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.StatusStub
	fakeReturns := fake.statusReturns
	fake.recordInvocation("Status", []interface{}{arg1})
	fake.statusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) StatusCallCount() int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return len(fake.statusArgsForCall)
}

func (fake *FakeStore) StatusCalls(stub func(int) ([]credentials.Credential, error)) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = stub
}

func (fake *FakeStore) StatusArgsForCall(i int) int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	argsForCall := fake.statusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) StatusReturns(result1 []credentials.Credential, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	fake.statusReturns = struct {
		result1 []credentials.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) StatusReturnsOnCall(i int, result1 []credentials.Credential, result2 error) {
	fake.statusMutex.Lock()
	defer fake.statusMutex.Unlock()
	fake.StatusStub = nil
	if fake.statusReturnsOnCall == nil {
		fake.statusReturnsOnCall = make(map[int]struct {
			result1 []credentials.Credential
			result2 error
		})
	}
	fake.statusReturnsOnCall[i] = struct {
		result1 []credentials.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ credentials.Store = new(FakeStore)
