// Code generated by counterfeiter. DO NOT EDIT.
package budgetfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/budget"
)

type FakeTicketBudgets struct {
	BudgetUSDStub        func(int) (float64, bool, error)
	budgetUSDMutex       sync.RWMutex
	budgetUSDArgsForCall []struct {
		arg1 int
	}
	budgetUSDReturns struct {
		result1 float64
		result2 bool
		result3 error
	}
	budgetUSDReturnsOnCall map[int]struct {
		result1 float64
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTicketBudgets) BudgetUSD(arg1 int) (float64, bool, error) {
	fake.budgetUSDMutex.Lock()
	ret, specificReturn := fake.budgetUSDReturnsOnCall[len(fake.budgetUSDArgsForCall)]
	fake.budgetUSDArgsForCall = append(fake.budgetUSDArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.BudgetUSDStub
	fakeReturns := fake.budgetUSDReturns
	fake.recordInvocation("BudgetUSD", []interface{}{arg1})
	fake.budgetUSDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeTicketBudgets) BudgetUSDCallCount() int {
	fake.budgetUSDMutex.RLock()
	defer fake.budgetUSDMutex.RUnlock()
	return len(fake.budgetUSDArgsForCall)
}

func (fake *FakeTicketBudgets) BudgetUSDCalls(stub func(int) (float64, bool, error)) {
	fake.budgetUSDMutex.Lock()
	defer fake.budgetUSDMutex.Unlock()
	fake.BudgetUSDStub = stub
}

func (fake *FakeTicketBudgets) BudgetUSDArgsForCall(i int) int {
	fake.budgetUSDMutex.RLock()
	defer fake.budgetUSDMutex.RUnlock()
	argsForCall := fake.budgetUSDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTicketBudgets) BudgetUSDReturns(result1 float64, result2 bool, result3 error) {
	fake.budgetUSDMutex.Lock()
	defer fake.budgetUSDMutex.Unlock()
	fake.BudgetUSDStub = nil
	fake.budgetUSDReturns = struct {
		result1 float64
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeTicketBudgets) BudgetUSDReturnsOnCall(i int, result1 float64, result2 bool, result3 error) {
	fake.budgetUSDMutex.Lock()
	defer fake.budgetUSDMutex.Unlock()
	fake.BudgetUSDStub = nil
	if fake.budgetUSDReturnsOnCall == nil {
		fake.budgetUSDReturnsOnCall = make(map[int]struct {
			result1 float64
			result2 bool
			result3 error
		})
	}
	fake.budgetUSDReturnsOnCall[i] = struct {
		result1 float64
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeTicketBudgets) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTicketBudgets) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ budget.TicketBudgets = new(FakeTicketBudgets)
