// Code generated by counterfeiter. DO NOT EDIT.
package budgetfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/budget"
)

type FakeChecker struct {
	GlobalDailyRemainingStub        func() (budget.Remaining, error)
	globalDailyRemainingMutex       sync.RWMutex
	globalDailyRemainingArgsForCall []struct {
	}
	globalDailyRemainingReturns struct {
		result1 budget.Remaining
		result2 error
	}
	globalDailyRemainingReturnsOnCall map[int]struct {
		result1 budget.Remaining
		result2 error
	}
	RecordStub        func(budget.LedgerEntry) error
	recordMutex       sync.RWMutex
	recordArgsForCall []struct {
		arg1 budget.LedgerEntry
	}
	recordReturns struct {
		result1 error
	}
	recordReturnsOnCall map[int]struct {
		result1 error
	}
	StepSliceStub        func(int, float64) (budget.Remaining, error)
	stepSliceMutex       sync.RWMutex
	stepSliceArgsForCall []struct {
		arg1 int
		arg2 float64
	}
	stepSliceReturns struct {
		result1 budget.Remaining
		result2 error
	}
	stepSliceReturnsOnCall map[int]struct {
		result1 budget.Remaining
		result2 error
	}
	TicketRemainingStub        func(int) (budget.Remaining, error)
	ticketRemainingMutex       sync.RWMutex
	ticketRemainingArgsForCall []struct {
		arg1 int
	}
	ticketRemainingReturns struct {
		result1 budget.Remaining
		result2 error
	}
	ticketRemainingReturnsOnCall map[int]struct {
		result1 budget.Remaining
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChecker) GlobalDailyRemaining() (budget.Remaining, error) {
	fake.globalDailyRemainingMutex.Lock()
	ret, specificReturn := fake.globalDailyRemainingReturnsOnCall[len(fake.globalDailyRemainingArgsForCall)]
	fake.globalDailyRemainingArgsForCall = append(fake.globalDailyRemainingArgsForCall, struct {
	}{})
	stub := fake.GlobalDailyRemainingStub
	fakeReturns := fake.globalDailyRemainingReturns
	fake.recordInvocation("GlobalDailyRemaining", []interface{}{})
	fake.globalDailyRemainingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) GlobalDailyRemainingCallCount() int {
	fake.globalDailyRemainingMutex.RLock()
	defer fake.globalDailyRemainingMutex.RUnlock()
	return len(fake.globalDailyRemainingArgsForCall)
}

func (fake *FakeChecker) GlobalDailyRemainingCalls(stub func() (budget.Remaining, error)) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = stub
}

func (fake *FakeChecker) GlobalDailyRemainingReturns(result1 budget.Remaining, result2 error) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = nil
	fake.globalDailyRemainingReturns = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) GlobalDailyRemainingReturnsOnCall(i int, result1 budget.Remaining, result2 error) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = nil
	if fake.globalDailyRemainingReturnsOnCall == nil {
		fake.globalDailyRemainingReturnsOnCall = make(map[int]struct {
			result1 budget.Remaining
			result2 error
		})
	}
	fake.globalDailyRemainingReturnsOnCall[i] = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) Record(arg1 budget.LedgerEntry) error {
	fake.recordMutex.Lock()
	ret, specificReturn := fake.recordReturnsOnCall[len(fake.recordArgsForCall)]
	fake.recordArgsForCall = append(fake.recordArgsForCall, struct {
		arg1 budget.LedgerEntry
	}{arg1})
	stub := fake.RecordStub
	fakeReturns := fake.recordReturns
	fake.recordInvocation("Record", []interface{}{arg1})
	fake.recordMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChecker) RecordCallCount() int {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	return len(fake.recordArgsForCall)
}

func (fake *FakeChecker) RecordCalls(stub func(budget.LedgerEntry) error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = stub
}

func (fake *FakeChecker) RecordArgsForCall(i int) budget.LedgerEntry {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	argsForCall := fake.recordArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) RecordReturns(result1 error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = nil
	fake.recordReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeChecker) RecordReturnsOnCall(i int, result1 error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = nil
	if fake.recordReturnsOnCall == nil {
		fake.recordReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.recordReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeChecker) StepSlice(arg1 int, arg2 float64) (budget.Remaining, error) {
	fake.stepSliceMutex.Lock()
	ret, specificReturn := fake.stepSliceReturnsOnCall[len(fake.stepSliceArgsForCall)]
	fake.stepSliceArgsForCall = append(fake.stepSliceArgsForCall, struct {
		arg1 int
		arg2 float64
	}{arg1, arg2})
	stub := fake.StepSliceStub
	fakeReturns := fake.stepSliceReturns
	fake.recordInvocation("StepSlice", []interface{}{arg1, arg2})
	fake.stepSliceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) StepSliceCallCount() int {
	fake.stepSliceMutex.RLock()
	defer fake.stepSliceMutex.RUnlock()
	return len(fake.stepSliceArgsForCall)
}

func (fake *FakeChecker) StepSliceCalls(stub func(int, float64) (budget.Remaining, error)) {
	fake.stepSliceMutex.Lock()
	defer fake.stepSliceMutex.Unlock()
	fake.StepSliceStub = stub
}

func (fake *FakeChecker) StepSliceArgsForCall(i int) (int, float64) {
	fake.stepSliceMutex.RLock()
	defer fake.stepSliceMutex.RUnlock()
	argsForCall := fake.stepSliceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeChecker) StepSliceReturns(result1 budget.Remaining, result2 error) {
	fake.stepSliceMutex.Lock()
	defer fake.stepSliceMutex.Unlock()
	fake.StepSliceStub = nil
	fake.stepSliceReturns = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) StepSliceReturnsOnCall(i int, result1 budget.Remaining, result2 error) {
	fake.stepSliceMutex.Lock()
	defer fake.stepSliceMutex.Unlock()
	fake.StepSliceStub = nil
	if fake.stepSliceReturnsOnCall == nil {
		fake.stepSliceReturnsOnCall = make(map[int]struct {
			result1 budget.Remaining
			result2 error
		})
	}
	fake.stepSliceReturnsOnCall[i] = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) TicketRemaining(arg1 int) (budget.Remaining, error) {
	fake.ticketRemainingMutex.Lock()
	ret, specificReturn := fake.ticketRemainingReturnsOnCall[len(fake.ticketRemainingArgsForCall)]
	fake.ticketRemainingArgsForCall = append(fake.ticketRemainingArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.TicketRemainingStub
	fakeReturns := fake.ticketRemainingReturns
	fake.recordInvocation("TicketRemaining", []interface{}{arg1})
	fake.ticketRemainingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) TicketRemainingCallCount() int {
	fake.ticketRemainingMutex.RLock()
	defer fake.ticketRemainingMutex.RUnlock()
	return len(fake.ticketRemainingArgsForCall)
}

func (fake *FakeChecker) TicketRemainingCalls(stub func(int) (budget.Remaining, error)) {
	fake.ticketRemainingMutex.Lock()
	defer fake.ticketRemainingMutex.Unlock()
	fake.TicketRemainingStub = stub
}

func (fake *FakeChecker) TicketRemainingArgsForCall(i int) int {
	fake.ticketRemainingMutex.RLock()
	defer fake.ticketRemainingMutex.RUnlock()
	argsForCall := fake.ticketRemainingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) TicketRemainingReturns(result1 budget.Remaining, result2 error) {
	fake.ticketRemainingMutex.Lock()
	defer fake.ticketRemainingMutex.Unlock()
	fake.TicketRemainingStub = nil
	fake.ticketRemainingReturns = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) TicketRemainingReturnsOnCall(i int, result1 budget.Remaining, result2 error) {
	fake.ticketRemainingMutex.Lock()
	defer fake.ticketRemainingMutex.Unlock()
	fake.TicketRemainingStub = nil
	if fake.ticketRemainingReturnsOnCall == nil {
		fake.ticketRemainingReturnsOnCall = make(map[int]struct {
			result1 budget.Remaining
			result2 error
		})
	}
	fake.ticketRemainingReturnsOnCall[i] = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ budget.Checker = new(FakeChecker)
