// Code generated by counterfeiter. DO NOT EDIT.
package budgetfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/budget"
)

type FakeChecker struct {
	GlobalDailyRemainingStub        func() (budget.Remaining, error)
	globalDailyRemainingMutex       sync.RWMutex
	globalDailyRemainingArgsForCall []struct {
	}
	globalDailyRemainingReturns struct {
		result1 budget.Remaining
		result2 error
	}
	globalDailyRemainingReturnsOnCall map[int]struct {
		result1 budget.Remaining
		result2 error
	}
	RecordStub        func(budget.LedgerEntry) error
	recordMutex       sync.RWMutex
	recordArgsForCall []struct {
		arg1 budget.LedgerEntry
	}
	recordReturns struct {
		result1 error
	}
	recordReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChecker) GlobalDailyRemaining() (budget.Remaining, error) {
	fake.globalDailyRemainingMutex.Lock()
	ret, specificReturn := fake.globalDailyRemainingReturnsOnCall[len(fake.globalDailyRemainingArgsForCall)]
	fake.globalDailyRemainingArgsForCall = append(fake.globalDailyRemainingArgsForCall, struct {
	}{})
	stub := fake.GlobalDailyRemainingStub
	fakeReturns := fake.globalDailyRemainingReturns
	fake.recordInvocation("GlobalDailyRemaining", []interface{}{})
	fake.globalDailyRemainingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) GlobalDailyRemainingCallCount() int {
	fake.globalDailyRemainingMutex.RLock()
	defer fake.globalDailyRemainingMutex.RUnlock()
	return len(fake.globalDailyRemainingArgsForCall)
}

func (fake *FakeChecker) GlobalDailyRemainingCalls(stub func() (budget.Remaining, error)) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = stub
}

func (fake *FakeChecker) GlobalDailyRemainingReturns(result1 budget.Remaining, result2 error) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = nil
	fake.globalDailyRemainingReturns = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) GlobalDailyRemainingReturnsOnCall(i int, result1 budget.Remaining, result2 error) {
	fake.globalDailyRemainingMutex.Lock()
	defer fake.globalDailyRemainingMutex.Unlock()
	fake.GlobalDailyRemainingStub = nil
	if fake.globalDailyRemainingReturnsOnCall == nil {
		fake.globalDailyRemainingReturnsOnCall = make(map[int]struct {
			result1 budget.Remaining
			result2 error
		})
	}
	fake.globalDailyRemainingReturnsOnCall[i] = struct {
		result1 budget.Remaining
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) Record(arg1 budget.LedgerEntry) error {
	fake.recordMutex.Lock()
	ret, specificReturn := fake.recordReturnsOnCall[len(fake.recordArgsForCall)]
	fake.recordArgsForCall = append(fake.recordArgsForCall, struct {
		arg1 budget.LedgerEntry
	}{arg1})
	stub := fake.RecordStub
	fakeReturns := fake.recordReturns
	fake.recordInvocation("Record", []interface{}{arg1})
	fake.recordMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChecker) RecordCallCount() int {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	return len(fake.recordArgsForCall)
}

func (fake *FakeChecker) RecordCalls(stub func(budget.LedgerEntry) error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = stub
}

func (fake *FakeChecker) RecordArgsForCall(i int) budget.LedgerEntry {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	argsForCall := fake.recordArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) RecordReturns(result1 error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = nil
	fake.recordReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeChecker) RecordReturnsOnCall(i int, result1 error) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = nil
	if fake.recordReturnsOnCall == nil {
		fake.recordReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.recordReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ budget.Checker = new(FakeChecker)
