package concourse

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

type mockGuardPackage struct {
	ImportPath     string
	Name           string
	Dir            string
	Incomplete     bool
	Error          *mockGuardPackageError
	DepsErrors     []*mockGuardPackageError
	GoFiles        []string
	CgoFiles       []string
	TestGoFiles    []string
	XTestGoFiles   []string
	IgnoredGoFiles []string
	InvalidGoFiles []string
}

type mockGuardPackageError struct {
	Err string
}

func moduleGoFiles(t *testing.T) ([]mockGuardPackage, []string) {
	t.Helper()

	cmd := exec.Command("go", "list", "-e", "-json", "./...")
	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			t.Fatalf("go list failed: %v\n%s", err, exitErr.Stderr)
		}
		t.Fatalf("go list failed: %v", err)
	}

	var packages []mockGuardPackage
	fileSet := map[string]struct{}{}
	decoder := json.NewDecoder(strings.NewReader(string(out)))
	for {
		var pkg mockGuardPackage
		err := decoder.Decode(&pkg)
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			t.Fatalf("decode go list output: %v", err)
		}
		if pkg.Error != nil {
			t.Fatalf("go list reported an error for %s: %s", pkg.ImportPath, pkg.Error.Err)
		}
		if pkg.Incomplete {
			t.Fatalf("go list reported incomplete package %s", pkg.ImportPath)
		}
		if len(pkg.DepsErrors) > 0 {
			t.Fatalf("go list reported dependency errors for %s: %s", pkg.ImportPath, pkg.DepsErrors[0].Err)
		}
		if len(pkg.InvalidGoFiles) > 0 {
			t.Fatalf("go list reported invalid Go files for %s: %v", pkg.ImportPath, pkg.InvalidGoFiles)
		}

		packages = append(packages, pkg)
		for _, group := range [][]string{pkg.GoFiles, pkg.CgoFiles, pkg.TestGoFiles, pkg.XTestGoFiles, pkg.IgnoredGoFiles} {
			for _, name := range group {
				fileSet[filepath.Join(pkg.Dir, name)] = struct{}{}
			}
		}
	}

	if len(packages) < 50 {
		t.Fatalf("go list returned only %d packages; guard would be vacuous", len(packages))
	}
	if len(fileSet) < 500 {
		t.Fatalf("go list returned only %d Go files; guard would be vacuous", len(fileSet))
	}

	files := make([]string, 0, len(fileSet))
	for path := range fileSet {
		files = append(files, path)
	}
	sort.Strings(files)
	return packages, files
}

var forbiddenMockImports = []string{
	"github.com/maxbrunsfeld/counterfeiter",
	"github.com/golang/mock",
	"go.uber.org/mock",
	"github.com/stretchr/testify/mock",
	"github.com/vektra/mockery",
	"github.com/matryer/moq",
	"github.com/tedsuo/ifrit/fake_runner_v2",
}

var forbiddenMockSuffixes = []string{
	"callcount", "argsforcall", "returns", "returnsoncall", "invocations", "calls",
}

func forbiddenMockName(name string) bool {
	name = strings.ToLower(name)
	for _, suffix := range forbiddenMockSuffixes {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}
	return false
}

func isGoTestEntry(decl *ast.FuncDecl) bool {
	if decl.Recv != nil {
		return false
	}
	for _, prefix := range []string{"Test", "Benchmark", "Fuzz", "Example"} {
		if strings.HasPrefix(decl.Name.Name, prefix) {
			return true
		}
	}
	return false
}

func TestNoInteractionMocks(t *testing.T) {
	packages, files := moduleGoFiles(t)
	t.Logf("scanning %d packages and %d Go files", len(packages), len(files))
	fset := token.NewFileSet()
	var violations []string

	for _, pkg := range packages {
		lastSlash := strings.LastIndex(pkg.ImportPath, "/")
		importComponent := pkg.ImportPath[lastSlash+1:]
		mockPackage := false
		for _, component := range []string{pkg.Name, importComponent} {
			component = strings.ToLower(component)
			if strings.HasSuffix(component, "fakes") || strings.HasSuffix(component, "mocks") {
				mockPackage = true
			}
		}
		if mockPackage {
			violations = append(violations, pkg.ImportPath+": mock package")
		}
	}

	for _, path := range files {
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			t.Errorf("parse %s: %v", path, err)
			continue
		}
		report := func(pos token.Pos, reason string) {
			violations = append(violations, fmt.Sprintf("%s: %s", fset.Position(pos), reason))
		}

		for _, group := range file.Comments {
			text := strings.ToLower(group.Text())
			generatorDirective := strings.Contains(text, "go:generate") &&
				(strings.Contains(text, "counterfeiter") || strings.Contains(text, "mockgen") ||
					strings.Contains(text, "mockery") || strings.Contains(text, "moq"))
			if strings.Contains(text, "counterfeiter:generate") || generatorDirective ||
				(strings.Contains(text, "code generated by") &&
					(strings.Contains(text, "counterfeiter") || strings.Contains(text, "mockgen") ||
						strings.Contains(text, "mockery") || strings.Contains(text, "moq"))) {
				report(group.Pos(), "generated-mock directive or header")
			}
		}

		for _, spec := range file.Imports {
			importPath, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				report(spec.Pos(), "invalid import path")
				continue
			}
			for _, prefix := range forbiddenMockImports {
				if importPath == prefix || strings.HasPrefix(importPath, prefix+"/") {
					report(spec.Pos(), "mocking framework import "+importPath)
				}
			}
		}

		ast.Inspect(file, func(node ast.Node) bool {
			switch value := node.(type) {
			case *ast.FuncDecl:
				if !isGoTestEntry(value) && forbiddenMockName(value.Name.Name) {
					report(value.Name.Pos(), "spy-shaped function "+value.Name.Name)
				}
			case *ast.StructType:
				for _, field := range value.Fields.List {
					_, isFunc := field.Type.(*ast.FuncType)
					for _, name := range field.Names {
						lowerName := strings.ToLower(name.Name)
						if forbiddenMockName(name.Name) || (isFunc && (strings.HasPrefix(lowerName, "stub") || strings.HasSuffix(lowerName, "stub"))) {
							report(name.Pos(), "spy-shaped field "+name.Name)
						}
					}
				}
			case *ast.CallExpr:
				selector, ok := value.Fun.(*ast.SelectorExpr)
				if !ok {
					break
				}
				switch selector.Sel.Name {
				case "Actions", "PrependReactor", "AddReactor":
					report(selector.Sel.Pos(), "interaction inspection or non-watch reactor "+selector.Sel.Name)
				}
			}
			return true
		})
	}

	sort.Strings(violations)
	for _, violation := range violations {
		t.Error(violation)
	}
}
