// Code generated by counterfeiter. DO NOT EDIT.
package execfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/exec"
)

type FakeAgentRunVerifier struct {
	RunBelongsToPipelineStub        func(int, int) (bool, error)
	runBelongsToPipelineMutex       sync.RWMutex
	runBelongsToPipelineArgsForCall []struct {
		arg1 int
		arg2 int
	}
	runBelongsToPipelineReturns struct {
		result1 bool
		result2 error
	}
	runBelongsToPipelineReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipeline(arg1 int, arg2 int) (bool, error) {
	fake.runBelongsToPipelineMutex.Lock()
	ret, specificReturn := fake.runBelongsToPipelineReturnsOnCall[len(fake.runBelongsToPipelineArgsForCall)]
	fake.runBelongsToPipelineArgsForCall = append(fake.runBelongsToPipelineArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	stub := fake.RunBelongsToPipelineStub
	fakeReturns := fake.runBelongsToPipelineReturns
	fake.recordInvocation("RunBelongsToPipeline", []interface{}{arg1, arg2})
	fake.runBelongsToPipelineMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipelineCallCount() int {
	fake.runBelongsToPipelineMutex.RLock()
	defer fake.runBelongsToPipelineMutex.RUnlock()
	return len(fake.runBelongsToPipelineArgsForCall)
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipelineCalls(stub func(int, int) (bool, error)) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = stub
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipelineArgsForCall(i int) (int, int) {
	fake.runBelongsToPipelineMutex.RLock()
	defer fake.runBelongsToPipelineMutex.RUnlock()
	argsForCall := fake.runBelongsToPipelineArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipelineReturns(result1 bool, result2 error) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = nil
	fake.runBelongsToPipelineReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunVerifier) RunBelongsToPipelineReturnsOnCall(i int, result1 bool, result2 error) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = nil
	if fake.runBelongsToPipelineReturnsOnCall == nil {
		fake.runBelongsToPipelineReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.runBelongsToPipelineReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunVerifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentRunVerifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ exec.AgentRunVerifier = new(FakeAgentRunVerifier)
