// Code generated by counterfeiter. DO NOT EDIT.
package execfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/atc/exec"
)

type FakeChildRunAdmitter struct {
	AdmitChildRunStub        func(context.Context, exec.ChildRunRequest) (exec.ChildRun, error)
	admitChildRunMutex       sync.RWMutex
	admitChildRunArgsForCall []struct {
		arg1 context.Context
		arg2 exec.ChildRunRequest
	}
	admitChildRunReturns struct {
		result1 exec.ChildRun
		result2 error
	}
	admitChildRunReturnsOnCall map[int]struct {
		result1 exec.ChildRun
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChildRunAdmitter) AdmitChildRun(arg1 context.Context, arg2 exec.ChildRunRequest) (exec.ChildRun, error) {
	fake.admitChildRunMutex.Lock()
	ret, specificReturn := fake.admitChildRunReturnsOnCall[len(fake.admitChildRunArgsForCall)]
	fake.admitChildRunArgsForCall = append(fake.admitChildRunArgsForCall, struct {
		arg1 context.Context
		arg2 exec.ChildRunRequest
	}{arg1, arg2})
	stub := fake.AdmitChildRunStub
	fakeReturns := fake.admitChildRunReturns
	fake.recordInvocation("AdmitChildRun", []interface{}{arg1, arg2})
	fake.admitChildRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChildRunAdmitter) AdmitChildRunCallCount() int {
	fake.admitChildRunMutex.RLock()
	defer fake.admitChildRunMutex.RUnlock()
	return len(fake.admitChildRunArgsForCall)
}

func (fake *FakeChildRunAdmitter) AdmitChildRunCalls(stub func(context.Context, exec.ChildRunRequest) (exec.ChildRun, error)) {
	fake.admitChildRunMutex.Lock()
	defer fake.admitChildRunMutex.Unlock()
	fake.AdmitChildRunStub = stub
}

func (fake *FakeChildRunAdmitter) AdmitChildRunArgsForCall(i int) (context.Context, exec.ChildRunRequest) {
	fake.admitChildRunMutex.RLock()
	defer fake.admitChildRunMutex.RUnlock()
	argsForCall := fake.admitChildRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeChildRunAdmitter) AdmitChildRunReturns(result1 exec.ChildRun, result2 error) {
	fake.admitChildRunMutex.Lock()
	defer fake.admitChildRunMutex.Unlock()
	fake.AdmitChildRunStub = nil
	fake.admitChildRunReturns = struct {
		result1 exec.ChildRun
		result2 error
	}{result1, result2}
}

func (fake *FakeChildRunAdmitter) AdmitChildRunReturnsOnCall(i int, result1 exec.ChildRun, result2 error) {
	fake.admitChildRunMutex.Lock()
	defer fake.admitChildRunMutex.Unlock()
	fake.AdmitChildRunStub = nil
	if fake.admitChildRunReturnsOnCall == nil {
		fake.admitChildRunReturnsOnCall = make(map[int]struct {
			result1 exec.ChildRun
			result2 error
		})
	}
	fake.admitChildRunReturnsOnCall[i] = struct {
		result1 exec.ChildRun
		result2 error
	}{result1, result2}
}

func (fake *FakeChildRunAdmitter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChildRunAdmitter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ exec.ChildRunAdmitter = new(FakeChildRunAdmitter)
