// Code generated by counterfeiter. DO NOT EDIT.
package workflowrunfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/agent/workflowrun"
	"github.com/concourse/concourse/atc/db"
)

type FakeWorkflowRunStore struct {
	CreateWithInputsStub        func(context.Context, db.AgentWorkflowRunCreateRequest) (db.AgentWorkflowRun, bool, error)
	createWithInputsMutex       sync.RWMutex
	createWithInputsArgsForCall []struct {
		arg1 context.Context
		arg2 db.AgentWorkflowRunCreateRequest
	}
	createWithInputsReturns struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}
	createWithInputsReturnsOnCall map[int]struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}
	FindByIdempotencyKeyStub        func(context.Context, int, string) (db.AgentWorkflowRun, bool, error)
	findByIdempotencyKeyMutex       sync.RWMutex
	findByIdempotencyKeyArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 string
	}
	findByIdempotencyKeyReturns struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}
	findByIdempotencyKeyReturnsOnCall map[int]struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}
	SnapshotsStub        func(context.Context, snapshot.WorkflowRunID) ([]db.AgentWorkflowRunSnapshotBinding, error)
	snapshotsMutex       sync.RWMutex
	snapshotsArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
	}
	snapshotsReturns struct {
		result1 []db.AgentWorkflowRunSnapshotBinding
		result2 error
	}
	snapshotsReturnsOnCall map[int]struct {
		result1 []db.AgentWorkflowRunSnapshotBinding
		result2 error
	}
	TransitionStub        func(context.Context, snapshot.WorkflowRunID, db.AgentWorkflowRunStatus, db.AgentWorkflowRunStatus, string) (bool, error)
	transitionMutex       sync.RWMutex
	transitionArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
		arg3 db.AgentWorkflowRunStatus
		arg4 db.AgentWorkflowRunStatus
		arg5 string
	}
	transitionReturns struct {
		result1 bool
		result2 error
	}
	transitionReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWorkflowRunStore) CreateWithInputs(arg1 context.Context, arg2 db.AgentWorkflowRunCreateRequest) (db.AgentWorkflowRun, bool, error) {
	fake.createWithInputsMutex.Lock()
	ret, specificReturn := fake.createWithInputsReturnsOnCall[len(fake.createWithInputsArgsForCall)]
	fake.createWithInputsArgsForCall = append(fake.createWithInputsArgsForCall, struct {
		arg1 context.Context
		arg2 db.AgentWorkflowRunCreateRequest
	}{arg1, arg2})
	stub := fake.CreateWithInputsStub
	fakeReturns := fake.createWithInputsReturns
	fake.recordInvocation("CreateWithInputs", []interface{}{arg1, arg2})
	fake.createWithInputsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeWorkflowRunStore) CreateWithInputsCallCount() int {
	fake.createWithInputsMutex.RLock()
	defer fake.createWithInputsMutex.RUnlock()
	return len(fake.createWithInputsArgsForCall)
}

func (fake *FakeWorkflowRunStore) CreateWithInputsCalls(stub func(context.Context, db.AgentWorkflowRunCreateRequest) (db.AgentWorkflowRun, bool, error)) {
	fake.createWithInputsMutex.Lock()
	defer fake.createWithInputsMutex.Unlock()
	fake.CreateWithInputsStub = stub
}

func (fake *FakeWorkflowRunStore) CreateWithInputsArgsForCall(i int) (context.Context, db.AgentWorkflowRunCreateRequest) {
	fake.createWithInputsMutex.RLock()
	defer fake.createWithInputsMutex.RUnlock()
	argsForCall := fake.createWithInputsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeWorkflowRunStore) CreateWithInputsReturns(result1 db.AgentWorkflowRun, result2 bool, result3 error) {
	fake.createWithInputsMutex.Lock()
	defer fake.createWithInputsMutex.Unlock()
	fake.CreateWithInputsStub = nil
	fake.createWithInputsReturns = struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkflowRunStore) CreateWithInputsReturnsOnCall(i int, result1 db.AgentWorkflowRun, result2 bool, result3 error) {
	fake.createWithInputsMutex.Lock()
	defer fake.createWithInputsMutex.Unlock()
	fake.CreateWithInputsStub = nil
	if fake.createWithInputsReturnsOnCall == nil {
		fake.createWithInputsReturnsOnCall = make(map[int]struct {
			result1 db.AgentWorkflowRun
			result2 bool
			result3 error
		})
	}
	fake.createWithInputsReturnsOnCall[i] = struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKey(arg1 context.Context, arg2 int, arg3 string) (db.AgentWorkflowRun, bool, error) {
	fake.findByIdempotencyKeyMutex.Lock()
	ret, specificReturn := fake.findByIdempotencyKeyReturnsOnCall[len(fake.findByIdempotencyKeyArgsForCall)]
	fake.findByIdempotencyKeyArgsForCall = append(fake.findByIdempotencyKeyArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindByIdempotencyKeyStub
	fakeReturns := fake.findByIdempotencyKeyReturns
	fake.recordInvocation("FindByIdempotencyKey", []interface{}{arg1, arg2, arg3})
	fake.findByIdempotencyKeyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKeyCallCount() int {
	fake.findByIdempotencyKeyMutex.RLock()
	defer fake.findByIdempotencyKeyMutex.RUnlock()
	return len(fake.findByIdempotencyKeyArgsForCall)
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKeyCalls(stub func(context.Context, int, string) (db.AgentWorkflowRun, bool, error)) {
	fake.findByIdempotencyKeyMutex.Lock()
	defer fake.findByIdempotencyKeyMutex.Unlock()
	fake.FindByIdempotencyKeyStub = stub
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKeyArgsForCall(i int) (context.Context, int, string) {
	fake.findByIdempotencyKeyMutex.RLock()
	defer fake.findByIdempotencyKeyMutex.RUnlock()
	argsForCall := fake.findByIdempotencyKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKeyReturns(result1 db.AgentWorkflowRun, result2 bool, result3 error) {
	fake.findByIdempotencyKeyMutex.Lock()
	defer fake.findByIdempotencyKeyMutex.Unlock()
	fake.FindByIdempotencyKeyStub = nil
	fake.findByIdempotencyKeyReturns = struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkflowRunStore) FindByIdempotencyKeyReturnsOnCall(i int, result1 db.AgentWorkflowRun, result2 bool, result3 error) {
	fake.findByIdempotencyKeyMutex.Lock()
	defer fake.findByIdempotencyKeyMutex.Unlock()
	fake.FindByIdempotencyKeyStub = nil
	if fake.findByIdempotencyKeyReturnsOnCall == nil {
		fake.findByIdempotencyKeyReturnsOnCall = make(map[int]struct {
			result1 db.AgentWorkflowRun
			result2 bool
			result3 error
		})
	}
	fake.findByIdempotencyKeyReturnsOnCall[i] = struct {
		result1 db.AgentWorkflowRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkflowRunStore) Snapshots(arg1 context.Context, arg2 snapshot.WorkflowRunID) ([]db.AgentWorkflowRunSnapshotBinding, error) {
	fake.snapshotsMutex.Lock()
	ret, specificReturn := fake.snapshotsReturnsOnCall[len(fake.snapshotsArgsForCall)]
	fake.snapshotsArgsForCall = append(fake.snapshotsArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
	}{arg1, arg2})
	stub := fake.SnapshotsStub
	fakeReturns := fake.snapshotsReturns
	fake.recordInvocation("Snapshots", []interface{}{arg1, arg2})
	fake.snapshotsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWorkflowRunStore) SnapshotsCallCount() int {
	fake.snapshotsMutex.RLock()
	defer fake.snapshotsMutex.RUnlock()
	return len(fake.snapshotsArgsForCall)
}

func (fake *FakeWorkflowRunStore) SnapshotsCalls(stub func(context.Context, snapshot.WorkflowRunID) ([]db.AgentWorkflowRunSnapshotBinding, error)) {
	fake.snapshotsMutex.Lock()
	defer fake.snapshotsMutex.Unlock()
	fake.SnapshotsStub = stub
}

func (fake *FakeWorkflowRunStore) SnapshotsArgsForCall(i int) (context.Context, snapshot.WorkflowRunID) {
	fake.snapshotsMutex.RLock()
	defer fake.snapshotsMutex.RUnlock()
	argsForCall := fake.snapshotsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeWorkflowRunStore) SnapshotsReturns(result1 []db.AgentWorkflowRunSnapshotBinding, result2 error) {
	fake.snapshotsMutex.Lock()
	defer fake.snapshotsMutex.Unlock()
	fake.SnapshotsStub = nil
	fake.snapshotsReturns = struct {
		result1 []db.AgentWorkflowRunSnapshotBinding
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkflowRunStore) SnapshotsReturnsOnCall(i int, result1 []db.AgentWorkflowRunSnapshotBinding, result2 error) {
	fake.snapshotsMutex.Lock()
	defer fake.snapshotsMutex.Unlock()
	fake.SnapshotsStub = nil
	if fake.snapshotsReturnsOnCall == nil {
		fake.snapshotsReturnsOnCall = make(map[int]struct {
			result1 []db.AgentWorkflowRunSnapshotBinding
			result2 error
		})
	}
	fake.snapshotsReturnsOnCall[i] = struct {
		result1 []db.AgentWorkflowRunSnapshotBinding
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkflowRunStore) Transition(arg1 context.Context, arg2 snapshot.WorkflowRunID, arg3 db.AgentWorkflowRunStatus, arg4 db.AgentWorkflowRunStatus, arg5 string) (bool, error) {
	fake.transitionMutex.Lock()
	ret, specificReturn := fake.transitionReturnsOnCall[len(fake.transitionArgsForCall)]
	fake.transitionArgsForCall = append(fake.transitionArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
		arg3 db.AgentWorkflowRunStatus
		arg4 db.AgentWorkflowRunStatus
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.TransitionStub
	fakeReturns := fake.transitionReturns
	fake.recordInvocation("Transition", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.transitionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWorkflowRunStore) TransitionCallCount() int {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	return len(fake.transitionArgsForCall)
}

func (fake *FakeWorkflowRunStore) TransitionCalls(stub func(context.Context, snapshot.WorkflowRunID, db.AgentWorkflowRunStatus, db.AgentWorkflowRunStatus, string) (bool, error)) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = stub
}

func (fake *FakeWorkflowRunStore) TransitionArgsForCall(i int) (context.Context, snapshot.WorkflowRunID, db.AgentWorkflowRunStatus, db.AgentWorkflowRunStatus, string) {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	argsForCall := fake.transitionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeWorkflowRunStore) TransitionReturns(result1 bool, result2 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	fake.transitionReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkflowRunStore) TransitionReturnsOnCall(i int, result1 bool, result2 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	if fake.transitionReturnsOnCall == nil {
		fake.transitionReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.transitionReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkflowRunStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWorkflowRunStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ workflowrun.WorkflowRunStore = new(FakeWorkflowRunStore)
