// Code generated by counterfeiter. DO NOT EDIT.
package workflowrunfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/agent/workflowrun"
)

type FakePipelineRunCreator struct {
	CreateRunForWorkflowRunStub        func(context.Context, snapshot.WorkflowRunID, workflowrun.WorkflowRunTemplateRef, map[string]any, string, workflowrun.BeforeWorkflowRunCommit) (workflowrun.WorkflowRunExecution, bool, error)
	createRunForWorkflowRunMutex       sync.RWMutex
	createRunForWorkflowRunArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
		arg3 workflowrun.WorkflowRunTemplateRef
		arg4 map[string]any
		arg5 string
		arg6 workflowrun.BeforeWorkflowRunCommit
	}
	createRunForWorkflowRunReturns struct {
		result1 workflowrun.WorkflowRunExecution
		result2 bool
		result3 error
	}
	createRunForWorkflowRunReturnsOnCall map[int]struct {
		result1 workflowrun.WorkflowRunExecution
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRun(arg1 context.Context, arg2 snapshot.WorkflowRunID, arg3 workflowrun.WorkflowRunTemplateRef, arg4 map[string]any, arg5 string, arg6 workflowrun.BeforeWorkflowRunCommit) (workflowrun.WorkflowRunExecution, bool, error) {
	fake.createRunForWorkflowRunMutex.Lock()
	ret, specificReturn := fake.createRunForWorkflowRunReturnsOnCall[len(fake.createRunForWorkflowRunArgsForCall)]
	fake.createRunForWorkflowRunArgsForCall = append(fake.createRunForWorkflowRunArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.WorkflowRunID
		arg3 workflowrun.WorkflowRunTemplateRef
		arg4 map[string]any
		arg5 string
		arg6 workflowrun.BeforeWorkflowRunCommit
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CreateRunForWorkflowRunStub
	fakeReturns := fake.createRunForWorkflowRunReturns
	fake.recordInvocation("CreateRunForWorkflowRun", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.createRunForWorkflowRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRunCallCount() int {
	fake.createRunForWorkflowRunMutex.RLock()
	defer fake.createRunForWorkflowRunMutex.RUnlock()
	return len(fake.createRunForWorkflowRunArgsForCall)
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRunCalls(stub func(context.Context, snapshot.WorkflowRunID, workflowrun.WorkflowRunTemplateRef, map[string]any, string, workflowrun.BeforeWorkflowRunCommit) (workflowrun.WorkflowRunExecution, bool, error)) {
	fake.createRunForWorkflowRunMutex.Lock()
	defer fake.createRunForWorkflowRunMutex.Unlock()
	fake.CreateRunForWorkflowRunStub = stub
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRunArgsForCall(i int) (context.Context, snapshot.WorkflowRunID, workflowrun.WorkflowRunTemplateRef, map[string]any, string, workflowrun.BeforeWorkflowRunCommit) {
	fake.createRunForWorkflowRunMutex.RLock()
	defer fake.createRunForWorkflowRunMutex.RUnlock()
	argsForCall := fake.createRunForWorkflowRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRunReturns(result1 workflowrun.WorkflowRunExecution, result2 bool, result3 error) {
	fake.createRunForWorkflowRunMutex.Lock()
	defer fake.createRunForWorkflowRunMutex.Unlock()
	fake.CreateRunForWorkflowRunStub = nil
	fake.createRunForWorkflowRunReturns = struct {
		result1 workflowrun.WorkflowRunExecution
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunCreator) CreateRunForWorkflowRunReturnsOnCall(i int, result1 workflowrun.WorkflowRunExecution, result2 bool, result3 error) {
	fake.createRunForWorkflowRunMutex.Lock()
	defer fake.createRunForWorkflowRunMutex.Unlock()
	fake.CreateRunForWorkflowRunStub = nil
	if fake.createRunForWorkflowRunReturnsOnCall == nil {
		fake.createRunForWorkflowRunReturnsOnCall = make(map[int]struct {
			result1 workflowrun.WorkflowRunExecution
			result2 bool
			result3 error
		})
	}
	fake.createRunForWorkflowRunReturnsOnCall[i] = struct {
		result1 workflowrun.WorkflowRunExecution
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePipelineRunCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ workflowrun.PipelineRunCreator = new(FakePipelineRunCreator)
