// Code generated by counterfeiter. DO NOT EDIT.
package workflowrunfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/agent/workflowrun"
)

type FakeSnapshotAuthorizer struct {
	GetAuthorizedStub        func(context.Context, int, snapshot.SnapshotID) (snapshot.Snapshot, bool, error)
	getAuthorizedMutex       sync.RWMutex
	getAuthorizedArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotID
	}
	getAuthorizedReturns struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}
	getAuthorizedReturnsOnCall map[int]struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSnapshotAuthorizer) GetAuthorized(arg1 context.Context, arg2 int, arg3 snapshot.SnapshotID) (snapshot.Snapshot, bool, error) {
	fake.getAuthorizedMutex.Lock()
	ret, specificReturn := fake.getAuthorizedReturnsOnCall[len(fake.getAuthorizedArgsForCall)]
	fake.getAuthorizedArgsForCall = append(fake.getAuthorizedArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 snapshot.SnapshotID
	}{arg1, arg2, arg3})
	stub := fake.GetAuthorizedStub
	fakeReturns := fake.getAuthorizedReturns
	fake.recordInvocation("GetAuthorized", []interface{}{arg1, arg2, arg3})
	fake.getAuthorizedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSnapshotAuthorizer) GetAuthorizedCallCount() int {
	fake.getAuthorizedMutex.RLock()
	defer fake.getAuthorizedMutex.RUnlock()
	return len(fake.getAuthorizedArgsForCall)
}

func (fake *FakeSnapshotAuthorizer) GetAuthorizedCalls(stub func(context.Context, int, snapshot.SnapshotID) (snapshot.Snapshot, bool, error)) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = stub
}

func (fake *FakeSnapshotAuthorizer) GetAuthorizedArgsForCall(i int) (context.Context, int, snapshot.SnapshotID) {
	fake.getAuthorizedMutex.RLock()
	defer fake.getAuthorizedMutex.RUnlock()
	argsForCall := fake.getAuthorizedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSnapshotAuthorizer) GetAuthorizedReturns(result1 snapshot.Snapshot, result2 bool, result3 error) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = nil
	fake.getAuthorizedReturns = struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSnapshotAuthorizer) GetAuthorizedReturnsOnCall(i int, result1 snapshot.Snapshot, result2 bool, result3 error) {
	fake.getAuthorizedMutex.Lock()
	defer fake.getAuthorizedMutex.Unlock()
	fake.GetAuthorizedStub = nil
	if fake.getAuthorizedReturnsOnCall == nil {
		fake.getAuthorizedReturnsOnCall = make(map[int]struct {
			result1 snapshot.Snapshot
			result2 bool
			result3 error
		})
	}
	fake.getAuthorizedReturnsOnCall[i] = struct {
		result1 snapshot.Snapshot
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSnapshotAuthorizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSnapshotAuthorizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ workflowrun.SnapshotAuthorizer = new(FakeSnapshotAuthorizer)
