// Code generated by counterfeiter. DO NOT EDIT.
package workflowrunfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/workflowrun"
)

type FakeBudgetAdmitter struct {
	AdmitStub        func(context.Context, workflowrun.BudgetAdmission) error
	admitMutex       sync.RWMutex
	admitArgsForCall []struct {
		arg1 context.Context
		arg2 workflowrun.BudgetAdmission
	}
	admitReturns struct {
		result1 error
	}
	admitReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBudgetAdmitter) Admit(arg1 context.Context, arg2 workflowrun.BudgetAdmission) error {
	fake.admitMutex.Lock()
	ret, specificReturn := fake.admitReturnsOnCall[len(fake.admitArgsForCall)]
	fake.admitArgsForCall = append(fake.admitArgsForCall, struct {
		arg1 context.Context
		arg2 workflowrun.BudgetAdmission
	}{arg1, arg2})
	stub := fake.AdmitStub
	fakeReturns := fake.admitReturns
	fake.recordInvocation("Admit", []interface{}{arg1, arg2})
	fake.admitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBudgetAdmitter) AdmitCallCount() int {
	fake.admitMutex.RLock()
	defer fake.admitMutex.RUnlock()
	return len(fake.admitArgsForCall)
}

func (fake *FakeBudgetAdmitter) AdmitCalls(stub func(context.Context, workflowrun.BudgetAdmission) error) {
	fake.admitMutex.Lock()
	defer fake.admitMutex.Unlock()
	fake.AdmitStub = stub
}

func (fake *FakeBudgetAdmitter) AdmitArgsForCall(i int) (context.Context, workflowrun.BudgetAdmission) {
	fake.admitMutex.RLock()
	defer fake.admitMutex.RUnlock()
	argsForCall := fake.admitArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBudgetAdmitter) AdmitReturns(result1 error) {
	fake.admitMutex.Lock()
	defer fake.admitMutex.Unlock()
	fake.AdmitStub = nil
	fake.admitReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBudgetAdmitter) AdmitReturnsOnCall(i int, result1 error) {
	fake.admitMutex.Lock()
	defer fake.admitMutex.Unlock()
	fake.AdmitStub = nil
	if fake.admitReturnsOnCall == nil {
		fake.admitReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.admitReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBudgetAdmitter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBudgetAdmitter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ workflowrun.BudgetAdmitter = new(FakeBudgetAdmitter)
