// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/native_agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_native_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type ExecEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecEvent_Stdout
	//	*ExecEvent_Stderr
	//	*ExecEvent_ExitStatus
	//	*ExecEvent_Error
	Event         isExecEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_proto_native_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecEvent) GetEvent() isExecEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecEvent) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecEvent) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecEvent) GetExitStatus() int32 {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_ExitStatus); ok {
			return x.ExitStatus
		}
	}
	return 0
}

func (x *ExecEvent) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isExecEvent_Event interface {
	isExecEvent_Event()
}

type ExecEvent_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecEvent_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecEvent_ExitStatus struct {
	ExitStatus int32 `protobuf:"varint,3,opt,name=exit_status,json=exitStatus,proto3,oneof"`
}

type ExecEvent_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ExecEvent_Stdout) isExecEvent_Event() {}

func (*ExecEvent_Stderr) isExecEvent_Event() {}

func (*ExecEvent_ExitStatus) isExecEvent_Event() {}

func (*ExecEvent_Error) isExecEvent_Event() {}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_proto_native_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{2}
}

func (x *KillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_proto_native_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{3}
}

type StreamInMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*StreamInMessage_Meta
	//	*StreamInMessage_Data
	Message       isStreamInMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInMessage) Reset() {
	*x = StreamInMessage{}
	mi := &file_proto_native_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInMessage) ProtoMessage() {}

func (x *StreamInMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInMessage.ProtoReflect.Descriptor instead.
func (*StreamInMessage) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StreamInMessage) GetMessage() isStreamInMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamInMessage) GetMeta() *StreamInMeta {
	if x != nil {
		if x, ok := x.Message.(*StreamInMessage_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *StreamInMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Message.(*StreamInMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isStreamInMessage_Message interface {
	isStreamInMessage_Message()
}

type StreamInMessage_Meta struct {
	Meta *StreamInMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type StreamInMessage_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*StreamInMessage_Meta) isStreamInMessage_Message() {}

func (*StreamInMessage_Data) isStreamInMessage_Message() {}

type StreamInMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInMeta) Reset() {
	*x = StreamInMeta{}
	mi := &file_proto_native_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInMeta) ProtoMessage() {}

func (x *StreamInMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInMeta.ProtoReflect.Descriptor instead.
func (*StreamInMeta) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamInMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamInMeta) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *StreamInMeta) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StreamInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInResponse) Reset() {
	*x = StreamInResponse{}
	mi := &file_proto_native_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInResponse) ProtoMessage() {}

func (x *StreamInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInResponse.ProtoReflect.Descriptor instead.
func (*StreamInResponse) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{6}
}

type StreamOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutRequest) Reset() {
	*x = StreamOutRequest{}
	mi := &file_proto_native_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutRequest) ProtoMessage() {}

func (x *StreamOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutRequest.ProtoReflect.Descriptor instead.
func (*StreamOutRequest) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOutRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamOutRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *StreamOutRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StreamOutChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutChunk) Reset() {
	*x = StreamOutChunk{}
	mi := &file_proto_native_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutChunk) ProtoMessage() {}

func (x *StreamOutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutChunk.ProtoReflect.Descriptor instead.
func (*StreamOutChunk) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StreamOutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_native_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_native_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_native_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_native_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PingResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_native_agent_proto protoreflect.FileDescriptor

const file_proto_native_agent_proto_rawDesc = "" +
	"\n" +
	"\x18proto/native_agent.proto\x12\x06native\"\x7f\n" +
	"\vExecRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\fR\x05stdin\"\x83\x01\n" +
	"\tExecEvent\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12!\n" +
	"\vexit_status\x18\x03 \x01(\x05H\x00R\n" +
	"exitStatus\x12\x16\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05errorB\a\n" +
	"\x05event\"\x1d\n" +
	"\vKillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fKillResponse\"^\n" +
	"\x0fStreamInMessage\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.native.StreamInMetaH\x00R\x04meta\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\amessage\"a\n" +
	"\fStreamInMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"\x12\n" +
	"\x10StreamInResponse\"e\n" +
	"\x10StreamOutRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"$\n" +
	"\x0eStreamOutChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\r\n" +
	"\vPingRequest\"X\n" +
	"\fPingResponse\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xa7\x02\n" +
	"\vNativeAgent\x120\n" +
	"\x04Exec\x12\x13.native.ExecRequest\x1a\x11.native.ExecEvent0\x01\x121\n" +
	"\x04Kill\x12\x13.native.KillRequest\x1a\x14.native.KillResponse\x12?\n" +
	"\bStreamIn\x12\x17.native.StreamInMessage\x1a\x18.native.StreamInResponse(\x01\x12?\n" +
	"\tStreamOut\x12\x18.native.StreamOutRequest\x1a\x16.native.StreamOutChunk0\x01\x121\n" +
	"\x04Ping\x12\x13.native.PingRequest\x1a\x14.native.PingResponseB:Z8github.com/concourse/concourse/atc/worker/native/agentpbb\x06proto3"

var (
	file_proto_native_agent_proto_rawDescOnce sync.Once
	file_proto_native_agent_proto_rawDescData []byte
)

func file_proto_native_agent_proto_rawDescGZIP() []byte {
	file_proto_native_agent_proto_rawDescOnce.Do(func() {
		file_proto_native_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_native_agent_proto_rawDesc), len(file_proto_native_agent_proto_rawDesc)))
	})
	return file_proto_native_agent_proto_rawDescData
}

var file_proto_native_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_native_agent_proto_goTypes = []any{
	(*ExecRequest)(nil),      // 0: native.ExecRequest
	(*ExecEvent)(nil),        // 1: native.ExecEvent
	(*KillRequest)(nil),      // 2: native.KillRequest
	(*KillResponse)(nil),     // 3: native.KillResponse
	(*StreamInMessage)(nil),  // 4: native.StreamInMessage
	(*StreamInMeta)(nil),     // 5: native.StreamInMeta
	(*StreamInResponse)(nil), // 6: native.StreamInResponse
	(*StreamOutRequest)(nil), // 7: native.StreamOutRequest
	(*StreamOutChunk)(nil),   // 8: native.StreamOutChunk
	(*PingRequest)(nil),      // 9: native.PingRequest
	(*PingResponse)(nil),     // 10: native.PingResponse
}
var file_proto_native_agent_proto_depIdxs = []int32{
	5,  // 0: native.StreamInMessage.meta:type_name -> native.StreamInMeta
	0,  // 1: native.NativeAgent.Exec:input_type -> native.ExecRequest
	2,  // 2: native.NativeAgent.Kill:input_type -> native.KillRequest
	4,  // 3: native.NativeAgent.StreamIn:input_type -> native.StreamInMessage
	7,  // 4: native.NativeAgent.StreamOut:input_type -> native.StreamOutRequest
	9,  // 5: native.NativeAgent.Ping:input_type -> native.PingRequest
	1,  // 6: native.NativeAgent.Exec:output_type -> native.ExecEvent
	3,  // 7: native.NativeAgent.Kill:output_type -> native.KillResponse
	6,  // 8: native.NativeAgent.StreamIn:output_type -> native.StreamInResponse
	8,  // 9: native.NativeAgent.StreamOut:output_type -> native.StreamOutChunk
	10, // 10: native.NativeAgent.Ping:output_type -> native.PingResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_native_agent_proto_init() }
func file_proto_native_agent_proto_init() {
	if File_proto_native_agent_proto != nil {
		return
	}
	file_proto_native_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecEvent_Stdout)(nil),
		(*ExecEvent_Stderr)(nil),
		(*ExecEvent_ExitStatus)(nil),
		(*ExecEvent_Error)(nil),
	}
	file_proto_native_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*StreamInMessage_Meta)(nil),
		(*StreamInMessage_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_native_agent_proto_rawDesc), len(file_proto_native_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_native_agent_proto_goTypes,
		DependencyIndexes: file_proto_native_agent_proto_depIdxs,
		MessageInfos:      file_proto_native_agent_proto_msgTypes,
	}.Build()
	File_proto_native_agent_proto = out.File
	file_proto_native_agent_proto_goTypes = nil
	file_proto_native_agent_proto_depIdxs = nil
}
