// Code generated by counterfeiter. DO NOT EDIT.
package metricsfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/api/metrics"
	"github.com/concourse/concourse/agent/schema"
)

type FakeStore struct {
	GetByBuildStub        func(int) ([]schema.RunMetrics, error)
	getByBuildMutex       sync.RWMutex
	getByBuildArgsForCall []struct {
		arg1 int
	}
	getByBuildReturns struct {
		result1 []schema.RunMetrics
		result2 error
	}
	getByBuildReturnsOnCall map[int]struct {
		result1 []schema.RunMetrics
		result2 error
	}
	InsertIfAbsentStub        func(*schema.RunMetrics) (bool, error)
	insertIfAbsentMutex       sync.RWMutex
	insertIfAbsentArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	insertIfAbsentReturns struct {
		result1 bool
		result2 error
	}
	insertIfAbsentReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ListByTicketStub        func(int) ([]schema.RunMetrics, error)
	listByTicketMutex       sync.RWMutex
	listByTicketArgsForCall []struct {
		arg1 int
	}
	listByTicketReturns struct {
		result1 []schema.RunMetrics
		result2 error
	}
	listByTicketReturnsOnCall map[int]struct {
		result1 []schema.RunMetrics
		result2 error
	}
	UpsertStub        func(*schema.RunMetrics) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	UpsertReturningInsertedStub        func(*schema.RunMetrics) (bool, error)
	upsertReturningInsertedMutex       sync.RWMutex
	upsertReturningInsertedArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	upsertReturningInsertedReturns struct {
		result1 bool
		result2 error
	}
	upsertReturningInsertedReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) GetByBuild(arg1 int) ([]schema.RunMetrics, error) {
	fake.getByBuildMutex.Lock()
	ret, specificReturn := fake.getByBuildReturnsOnCall[len(fake.getByBuildArgsForCall)]
	fake.getByBuildArgsForCall = append(fake.getByBuildArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetByBuildStub
	fakeReturns := fake.getByBuildReturns
	fake.recordInvocation("GetByBuild", []interface{}{arg1})
	fake.getByBuildMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetByBuildCallCount() int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	return len(fake.getByBuildArgsForCall)
}

func (fake *FakeStore) GetByBuildCalls(stub func(int) ([]schema.RunMetrics, error)) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = stub
}

func (fake *FakeStore) GetByBuildArgsForCall(i int) int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	argsForCall := fake.getByBuildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) GetByBuildReturns(result1 []schema.RunMetrics, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	fake.getByBuildReturns = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetByBuildReturnsOnCall(i int, result1 []schema.RunMetrics, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	if fake.getByBuildReturnsOnCall == nil {
		fake.getByBuildReturnsOnCall = make(map[int]struct {
			result1 []schema.RunMetrics
			result2 error
		})
	}
	fake.getByBuildReturnsOnCall[i] = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertIfAbsent(arg1 *schema.RunMetrics) (bool, error) {
	fake.insertIfAbsentMutex.Lock()
	ret, specificReturn := fake.insertIfAbsentReturnsOnCall[len(fake.insertIfAbsentArgsForCall)]
	fake.insertIfAbsentArgsForCall = append(fake.insertIfAbsentArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.InsertIfAbsentStub
	fakeReturns := fake.insertIfAbsentReturns
	fake.recordInvocation("InsertIfAbsent", []interface{}{arg1})
	fake.insertIfAbsentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) InsertIfAbsentCallCount() int {
	fake.insertIfAbsentMutex.RLock()
	defer fake.insertIfAbsentMutex.RUnlock()
	return len(fake.insertIfAbsentArgsForCall)
}

func (fake *FakeStore) InsertIfAbsentCalls(stub func(*schema.RunMetrics) (bool, error)) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = stub
}

func (fake *FakeStore) InsertIfAbsentArgsForCall(i int) *schema.RunMetrics {
	fake.insertIfAbsentMutex.RLock()
	defer fake.insertIfAbsentMutex.RUnlock()
	argsForCall := fake.insertIfAbsentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) InsertIfAbsentReturns(result1 bool, result2 error) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = nil
	fake.insertIfAbsentReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) InsertIfAbsentReturnsOnCall(i int, result1 bool, result2 error) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = nil
	if fake.insertIfAbsentReturnsOnCall == nil {
		fake.insertIfAbsentReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.insertIfAbsentReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListByTicket(arg1 int) ([]schema.RunMetrics, error) {
	fake.listByTicketMutex.Lock()
	ret, specificReturn := fake.listByTicketReturnsOnCall[len(fake.listByTicketArgsForCall)]
	fake.listByTicketArgsForCall = append(fake.listByTicketArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.ListByTicketStub
	fakeReturns := fake.listByTicketReturns
	fake.recordInvocation("ListByTicket", []interface{}{arg1})
	fake.listByTicketMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) ListByTicketCallCount() int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	return len(fake.listByTicketArgsForCall)
}

func (fake *FakeStore) ListByTicketCalls(stub func(int) ([]schema.RunMetrics, error)) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = stub
}

func (fake *FakeStore) ListByTicketArgsForCall(i int) int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	argsForCall := fake.listByTicketArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) ListByTicketReturns(result1 []schema.RunMetrics, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	fake.listByTicketReturns = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) ListByTicketReturnsOnCall(i int, result1 []schema.RunMetrics, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	if fake.listByTicketReturnsOnCall == nil {
		fake.listByTicketReturnsOnCall = make(map[int]struct {
			result1 []schema.RunMetrics
			result2 error
		})
	}
	fake.listByTicketReturnsOnCall[i] = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Upsert(arg1 *schema.RunMetrics) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeStore) UpsertCalls(stub func(*schema.RunMetrics) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeStore) UpsertArgsForCall(i int) *schema.RunMetrics {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) UpsertReturningInserted(arg1 *schema.RunMetrics) (bool, error) {
	fake.upsertReturningInsertedMutex.Lock()
	ret, specificReturn := fake.upsertReturningInsertedReturnsOnCall[len(fake.upsertReturningInsertedArgsForCall)]
	fake.upsertReturningInsertedArgsForCall = append(fake.upsertReturningInsertedArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.UpsertReturningInsertedStub
	fakeReturns := fake.upsertReturningInsertedReturns
	fake.recordInvocation("UpsertReturningInserted", []interface{}{arg1})
	fake.upsertReturningInsertedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) UpsertReturningInsertedCallCount() int {
	fake.upsertReturningInsertedMutex.RLock()
	defer fake.upsertReturningInsertedMutex.RUnlock()
	return len(fake.upsertReturningInsertedArgsForCall)
}

func (fake *FakeStore) UpsertReturningInsertedCalls(stub func(*schema.RunMetrics) (bool, error)) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = stub
}

func (fake *FakeStore) UpsertReturningInsertedArgsForCall(i int) *schema.RunMetrics {
	fake.upsertReturningInsertedMutex.RLock()
	defer fake.upsertReturningInsertedMutex.RUnlock()
	argsForCall := fake.upsertReturningInsertedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) UpsertReturningInsertedReturns(result1 bool, result2 error) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = nil
	fake.upsertReturningInsertedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) UpsertReturningInsertedReturnsOnCall(i int, result1 bool, result2 error) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = nil
	if fake.upsertReturningInsertedReturnsOnCall == nil {
		fake.upsertReturningInsertedReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.upsertReturningInsertedReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Store = new(FakeStore)
