name: 📥 Add Work Item
description: Create an issue for concrete work that anyone in the community can work on.

body:
  - type: markdown
    attributes:
      value: |
        This issue should be for any feature work that needs to be tracked.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the task to be completed.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links to any related discussions, issues, or RFC
      placeholder: |
        Discussion Post(s):
        Related Issue(s):
        RFC:
