// Code generated by counterfeiter. DO NOT EDIT.
package credsfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/creds"
	"github.com/concourse/concourse/vars"
)

type FakeSecretRefProvider struct {
	GetSecretRefStub        func(string) (*vars.SecretRef, bool)
	getSecretRefMutex       sync.RWMutex
	getSecretRefArgsForCall []struct {
		arg1 string
	}
	getSecretRefReturns struct {
		result1 *vars.SecretRef
		result2 bool
	}
	getSecretRefReturnsOnCall map[int]struct {
		result1 *vars.SecretRef
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSecretRefProvider) GetSecretRef(arg1 string) (*vars.SecretRef, bool) {
	fake.getSecretRefMutex.Lock()
	ret, specificReturn := fake.getSecretRefReturnsOnCall[len(fake.getSecretRefArgsForCall)]
	fake.getSecretRefArgsForCall = append(fake.getSecretRefArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetSecretRefStub
	fakeReturns := fake.getSecretRefReturns
	fake.recordInvocation("GetSecretRef", []interface{}{arg1})
	fake.getSecretRefMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSecretRefProvider) GetSecretRefCallCount() int {
	fake.getSecretRefMutex.RLock()
	defer fake.getSecretRefMutex.RUnlock()
	return len(fake.getSecretRefArgsForCall)
}

func (fake *FakeSecretRefProvider) GetSecretRefCalls(stub func(string) (*vars.SecretRef, bool)) {
	fake.getSecretRefMutex.Lock()
	defer fake.getSecretRefMutex.Unlock()
	fake.GetSecretRefStub = stub
}

func (fake *FakeSecretRefProvider) GetSecretRefArgsForCall(i int) string {
	fake.getSecretRefMutex.RLock()
	defer fake.getSecretRefMutex.RUnlock()
	argsForCall := fake.getSecretRefArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSecretRefProvider) GetSecretRefReturns(result1 *vars.SecretRef, result2 bool) {
	fake.getSecretRefMutex.Lock()
	defer fake.getSecretRefMutex.Unlock()
	fake.GetSecretRefStub = nil
	fake.getSecretRefReturns = struct {
		result1 *vars.SecretRef
		result2 bool
	}{result1, result2}
}

func (fake *FakeSecretRefProvider) GetSecretRefReturnsOnCall(i int, result1 *vars.SecretRef, result2 bool) {
	fake.getSecretRefMutex.Lock()
	defer fake.getSecretRefMutex.Unlock()
	fake.GetSecretRefStub = nil
	if fake.getSecretRefReturnsOnCall == nil {
		fake.getSecretRefReturnsOnCall = make(map[int]struct {
			result1 *vars.SecretRef
			result2 bool
		})
	}
	fake.getSecretRefReturnsOnCall[i] = struct {
		result1 *vars.SecretRef
		result2 bool
	}{result1, result2}
}

func (fake *FakeSecretRefProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretRefProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ creds.SecretRefProvider = new(FakeSecretRefProvider)
