// Code generated by counterfeiter. DO NOT EDIT.
package componentfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/component"
	"github.com/concourse/concourse/atc/db"
)

type FakeNotificationsBus struct {
	ListenSignalStub        func(string) (*db.NotifySignal, error)
	listenSignalMutex       sync.RWMutex
	listenSignalArgsForCall []struct {
		arg1 string
	}
	listenSignalReturns struct {
		result1 *db.NotifySignal
		result2 error
	}
	listenSignalReturnsOnCall map[int]struct {
		result1 *db.NotifySignal
		result2 error
	}
	UnlistenSignalStub        func(string, *db.NotifySignal) error
	unlistenSignalMutex       sync.RWMutex
	unlistenSignalArgsForCall []struct {
		arg1 string
		arg2 *db.NotifySignal
	}
	unlistenSignalReturns struct {
		result1 error
	}
	unlistenSignalReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNotificationsBus) ListenSignal(arg1 string) (*db.NotifySignal, error) {
	fake.listenSignalMutex.Lock()
	ret, specificReturn := fake.listenSignalReturnsOnCall[len(fake.listenSignalArgsForCall)]
	fake.listenSignalArgsForCall = append(fake.listenSignalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListenSignalStub
	fakeReturns := fake.listenSignalReturns
	fake.recordInvocation("ListenSignal", []interface{}{arg1})
	fake.listenSignalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNotificationsBus) ListenSignalCallCount() int {
	fake.listenSignalMutex.RLock()
	defer fake.listenSignalMutex.RUnlock()
	return len(fake.listenSignalArgsForCall)
}

func (fake *FakeNotificationsBus) ListenSignalCalls(stub func(string) (*db.NotifySignal, error)) {
	fake.listenSignalMutex.Lock()
	defer fake.listenSignalMutex.Unlock()
	fake.ListenSignalStub = stub
}

func (fake *FakeNotificationsBus) ListenSignalArgsForCall(i int) string {
	fake.listenSignalMutex.RLock()
	defer fake.listenSignalMutex.RUnlock()
	argsForCall := fake.listenSignalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNotificationsBus) ListenSignalReturns(result1 *db.NotifySignal, result2 error) {
	fake.listenSignalMutex.Lock()
	defer fake.listenSignalMutex.Unlock()
	fake.ListenSignalStub = nil
	fake.listenSignalReturns = struct {
		result1 *db.NotifySignal
		result2 error
	}{result1, result2}
}

func (fake *FakeNotificationsBus) ListenSignalReturnsOnCall(i int, result1 *db.NotifySignal, result2 error) {
	fake.listenSignalMutex.Lock()
	defer fake.listenSignalMutex.Unlock()
	fake.ListenSignalStub = nil
	if fake.listenSignalReturnsOnCall == nil {
		fake.listenSignalReturnsOnCall = make(map[int]struct {
			result1 *db.NotifySignal
			result2 error
		})
	}
	fake.listenSignalReturnsOnCall[i] = struct {
		result1 *db.NotifySignal
		result2 error
	}{result1, result2}
}

func (fake *FakeNotificationsBus) UnlistenSignal(arg1 string, arg2 *db.NotifySignal) error {
	fake.unlistenSignalMutex.Lock()
	ret, specificReturn := fake.unlistenSignalReturnsOnCall[len(fake.unlistenSignalArgsForCall)]
	fake.unlistenSignalArgsForCall = append(fake.unlistenSignalArgsForCall, struct {
		arg1 string
		arg2 *db.NotifySignal
	}{arg1, arg2})
	stub := fake.UnlistenSignalStub
	fakeReturns := fake.unlistenSignalReturns
	fake.recordInvocation("UnlistenSignal", []interface{}{arg1, arg2})
	fake.unlistenSignalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNotificationsBus) UnlistenSignalCallCount() int {
	fake.unlistenSignalMutex.RLock()
	defer fake.unlistenSignalMutex.RUnlock()
	return len(fake.unlistenSignalArgsForCall)
}

func (fake *FakeNotificationsBus) UnlistenSignalCalls(stub func(string, *db.NotifySignal) error) {
	fake.unlistenSignalMutex.Lock()
	defer fake.unlistenSignalMutex.Unlock()
	fake.UnlistenSignalStub = stub
}

func (fake *FakeNotificationsBus) UnlistenSignalArgsForCall(i int) (string, *db.NotifySignal) {
	fake.unlistenSignalMutex.RLock()
	defer fake.unlistenSignalMutex.RUnlock()
	argsForCall := fake.unlistenSignalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNotificationsBus) UnlistenSignalReturns(result1 error) {
	fake.unlistenSignalMutex.Lock()
	defer fake.unlistenSignalMutex.Unlock()
	fake.UnlistenSignalStub = nil
	fake.unlistenSignalReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNotificationsBus) UnlistenSignalReturnsOnCall(i int, result1 error) {
	fake.unlistenSignalMutex.Lock()
	defer fake.unlistenSignalMutex.Unlock()
	fake.UnlistenSignalStub = nil
	if fake.unlistenSignalReturnsOnCall == nil {
		fake.unlistenSignalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unlistenSignalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNotificationsBus) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNotificationsBus) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ component.NotificationsBus = new(FakeNotificationsBus)
