// Package executioncontrol is the protocol by which the web learns and settles
// one exact execution's fate on its node.
//
// It answers exactly four questions, and nothing else:
//
//	Classify                     what is durably known about this exact execution
//	ObserveFinishOrStop          the durable acknowledgement, never an inference
//	RequestSourcePreservingStop  interrupt the command without destroying anything
//	DestructiveCleanupEligible   may its remains be deleted yet
//
// It has one consumer, the pipeline Run. Durable output capture extends it in
// hangar/output: the extension references the same Identity and
// ActivationEpoch rather than declaring its own, so an execution has one
// truth however many gates hang off it. A base acknowledgement carries no
// capture, source-hold, handle-generation or output field; those live only on
// the extension's own acknowledgement.
//
// The wire contract is frozen, language-neutrally, in testdata/protocol-v1.
// The Go types here are one implementation of it; the fixtures are the
// contract. Every enum is closed: an unknown or newly added member is refused
// at decode, never absorbed into a zero value.
//
// This package is a leaf. It imports nothing first-party — not even hangar,
// because an exact TreeRef is an output concept and this protocol has no
// outputs.
package executioncontrol

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"time"
)

// ProtocolVersion is the only version of this protocol that exists. It is
// carried on every message rather than negotiated once, so a message that
// outlived its protocol is refused where it is read.
const ProtocolVersion = "hangar-execution-control-v1"

// ReadyLabel says a node's daemon serves this protocol. It is a scheduling
// hint and never an authority: the capability the daemon verifies is.
//
// It is deliberately distinct from concourse.dev/hangar-v1, which advertises
// strict inputs only, and from concourse.dev/hangar-output-v1, which
// advertises the durable capture extension on top of this one.
const ReadyLabel = "concourse.dev/hangar-execution-control-v1"

// LedgerVersion is the on-node record format the acknowledgements below are
// read from. It moves independently of ProtocolVersion: a node may gain a
// ledger format without the wire changing, and the handshake reports both.
const LedgerVersion = "hangar-execution-ledger-v1"

var (
	// ErrUnsupportedProtocol is a message in a protocol version this daemon does not speak.
	ErrUnsupportedProtocol = errors.New("hangar/executioncontrol: unsupported protocol version")
	// ErrUnknownMember is a closed vocabulary asked to accept a member it does
	// not have. It is deliberately not "unknown, treat as zero".
	ErrUnknownMember = errors.New("hangar/executioncontrol: unknown closed-vocabulary member")
	// ErrInvalidIdentity is a malformed or absent exact identity.
	ErrInvalidIdentity = errors.New("hangar/executioncontrol: invalid execution identity")
	// ErrIncomplete is a structurally valid message whose parts contradict each
	// other -- an authoritative classification with no acknowledgement behind
	// it, for instance.
	ErrIncomplete = errors.New("hangar/executioncontrol: incomplete message")
	// ErrStaleFence is an operation offered under a fence that has been
	// superseded.
	ErrStaleFence = errors.New("hangar/executioncontrol: stale fencing epoch")
)

// uuidPattern is RFC 4122 text form. The nil UUID is rejected separately: an
// all-zero identity is what an uninitialized caller sends.
var uuidPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

func validateUUID(what, value string) error {
	if value == "" {
		return fmt.Errorf("%w: %s is empty", ErrInvalidIdentity, what)
	}
	if !uuidPattern.MatchString(value) {
		return fmt.Errorf("%w: %s %q is not a lowercase RFC 4122 UUID", ErrInvalidIdentity, what, value)
	}

	return nil
}

// ExecutionID is an opaque, globally unique identity for one exact execution
// of one command. It is generated by the caller, carries no meaning Hangar can
// read, and is never reused: a second attempt is a second execution.
type ExecutionID string

func (id ExecutionID) Validate() error { return validateUUID("execution id", string(id)) }

// Fence is the monotonic fencing epoch for an execution's control. Takeover
// advances it; a holder of an older fence may observe but never act.
type Fence uint64

// ActivationEpoch is the control-key generation an execution was admitted
// under: which capability key and node control key speak for it. One
// generation covers both the base facet and, when enabled, the capture facet;
// there is never a second one for the same execution. It does not decide
// whether the output plane is in service; the web's hangar_enabled row does.
type ActivationEpoch uint64

// LedgerSequence orders the records on one node's control ledger. It is
// meaningful only alongside the NodeUID that produced it.
type LedgerSequence uint64

// NodeUID identifies the node whose daemon holds the ledger. It is the
// Kubernetes node UID, not its name: a name can be reused for new hardware.
type NodeUID string

// PodUID identifies the exact Pod incarnation. A recreated Pod is a new UID
// and, for capture, a new incarnation that may not write.
type PodUID string

// ProcessIdentity is the daemon's opaque handle for the exact OS process. A PID
// alone is not one: PIDs are reused.
type ProcessIdentity string

// ControlCapability is an attenuated, opaque bearer capability for one
// execution's control operations. It authorizes stop and observation, never
// deletion, and is not a credential for any object store.
type ControlCapability string

// Identity is the exact identity of one controlled execution under one fence.
//
// Every message in this protocol carries it, and the capture extension in
// hangar/output references this type rather than restating its parts. That is
// the whole reason an optional extension cannot fork the base truth.
type Identity struct {
	ExecutionID ExecutionID `json:"execution_id"`
	Fence       Fence       `json:"fence"`
}

func (identity Identity) Validate() error {
	return identity.ExecutionID.Validate()
}

// Envelope is what a control plane hands a node when it admits an execution.
//
// It is the base envelope in the literal sense: everything an execution needs
// to be controllable, and not one field about what the execution is for.
//
// It names NO Pod, and the omission is the protocol's, not an oversight. An
// admission has to precede the Pod: `buildPod` mounts the capture's step
// directory, so admission cannot wait for a UID the API server has not
// assigned yet. What
// admission binds is therefore the execution identity, its fence and the node
// -- the three facts that exist before the Pod does. The Pod UID is bound once,
// later and elsewhere: the capture control init presents its own Downward API
// value at the hold, and a start acknowledgement carries the UID the ATC
// recorded the start for.
type Envelope struct {
	ProtocolVersion string `json:"protocol_version"`
	Identity
	ActivationEpoch ActivationEpoch   `json:"activation_epoch"`
	NodeUID         NodeUID           `json:"node_uid"`
	Capability      ControlCapability `json:"capability"`
}

func (envelope Envelope) Validate() error {
	if err := validateProtocol(envelope.ProtocolVersion); err != nil {
		return err
	}
	if err := envelope.Identity.Validate(); err != nil {
		return err
	}
	if envelope.ActivationEpoch == 0 {
		return fmt.Errorf("%w: activation epoch is zero", ErrIncomplete)
	}
	if envelope.NodeUID == "" {
		return fmt.Errorf("%w: node uid is empty", ErrIncomplete)
	}
	if envelope.Capability == "" {
		return fmt.Errorf("%w: control capability is empty", ErrIncomplete)
	}

	return nil
}

func validateProtocol(version string) error {
	if version != ProtocolVersion {
		return fmt.Errorf("%w: %q, this daemon speaks %q", ErrUnsupportedProtocol, version, ProtocolVersion)
	}

	return nil
}

// Timestamp is an instant on the wire: RFC 3339, UTC, exactly nine fractional
// digits, always.
//
// time.Time's own encoding trims trailing zeros, so the same instant has more
// than one representation and a golden fixture cannot be compared byte for
// byte. A wire contract other languages must reproduce needs one spelling per
// value, so this type fixes the width and requires UTC.
type Timestamp struct {
	time.Time
}

const timestampLayout = "2006-01-02T15:04:05.000000000Z07:00"

func NewTimestamp(at time.Time) Timestamp { return Timestamp{at.UTC()} }

func (ts Timestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(ts.UTC().Format(timestampLayout))
}

func (ts *Timestamp) UnmarshalJSON(raw []byte) error {
	var text string
	if err := json.Unmarshal(raw, &text); err != nil {
		return err
	}
	parsed, err := time.Parse(time.RFC3339Nano, text)
	if err != nil {
		return fmt.Errorf("hangar/executioncontrol: timestamp %q is not RFC 3339: %w", text, err)
	}
	if parsed.Location() != time.UTC {
		return fmt.Errorf("hangar/executioncontrol: timestamp %q is not UTC; the wire has one spelling per instant", text)
	}
	ts.Time = parsed

	return nil
}

func (ts Timestamp) Validate() error {
	if ts.IsZero() {
		return fmt.Errorf("%w: timestamp is zero", ErrIncomplete)
	}

	return nil
}
