// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/api/reviews"
	"github.com/concourse/concourse/agent/projection"
	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentReviewsFactory struct {
	FindReviewInputStub        func(context.Context, snapshot.SnapshotID) (projection.ReviewInput, bool, error)
	findReviewInputMutex       sync.RWMutex
	findReviewInputArgsForCall []struct {
		arg1 context.Context
		arg2 snapshot.SnapshotID
	}
	findReviewInputReturns struct {
		result1 projection.ReviewInput
		result2 bool
		result3 error
	}
	findReviewInputReturnsOnCall map[int]struct {
		result1 projection.ReviewInput
		result2 bool
		result3 error
	}
	GetByBuildStub        func(int) ([]reviews.StoredReview, error)
	getByBuildMutex       sync.RWMutex
	getByBuildArgsForCall []struct {
		arg1 int
	}
	getByBuildReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	getByBuildReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	GetBySnapshotStub        func(string, snapshot.SnapshotID) (reviews.StoredReview, bool, error)
	getBySnapshotMutex       sync.RWMutex
	getBySnapshotArgsForCall []struct {
		arg1 string
		arg2 snapshot.SnapshotID
	}
	getBySnapshotReturns struct {
		result1 reviews.StoredReview
		result2 bool
		result3 error
	}
	getBySnapshotReturnsOnCall map[int]struct {
		result1 reviews.StoredReview
		result2 bool
		result3 error
	}
	ListByTeamStub        func(string, reviews.ListFilter) ([]reviews.StoredReview, error)
	listByTeamMutex       sync.RWMutex
	listByTeamArgsForCall []struct {
		arg1 string
		arg2 reviews.ListFilter
	}
	listByTeamReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	listByTeamReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	ListByTicketStub        func(int) ([]reviews.StoredReview, error)
	listByTicketMutex       sync.RWMutex
	listByTicketArgsForCall []struct {
		arg1 int
	}
	listByTicketReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	listByTicketReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	ListByWorkflowRunStub        func(string, string, snapshot.WorkflowRunID) ([]reviews.StoredReview, error)
	listByWorkflowRunMutex       sync.RWMutex
	listByWorkflowRunArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 snapshot.WorkflowRunID
	}
	listByWorkflowRunReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	listByWorkflowRunReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	ListUnprojectedReviewsStub        func(context.Context, int) ([]snapshot.SnapshotRef, error)
	listUnprojectedReviewsMutex       sync.RWMutex
	listUnprojectedReviewsArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	listUnprojectedReviewsReturns struct {
		result1 []snapshot.SnapshotRef
		result2 error
	}
	listUnprojectedReviewsReturnsOnCall map[int]struct {
		result1 []snapshot.SnapshotRef
		result2 error
	}
	UpsertStub        func(*reviews.StoredReview) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 *reviews.StoredReview
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	UpsertReviewProjectionStub        func(context.Context, *reviews.StoredReview) error
	upsertReviewProjectionMutex       sync.RWMutex
	upsertReviewProjectionArgsForCall []struct {
		arg1 context.Context
		arg2 *reviews.StoredReview
	}
	upsertReviewProjectionReturns struct {
		result1 error
	}
	upsertReviewProjectionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentReviewsFactory) FindReviewInput(arg1 context.Context, arg2 snapshot.SnapshotID) (projection.ReviewInput, bool, error) {
	fake.findReviewInputMutex.Lock()
	ret, specificReturn := fake.findReviewInputReturnsOnCall[len(fake.findReviewInputArgsForCall)]
	fake.findReviewInputArgsForCall = append(fake.findReviewInputArgsForCall, struct {
		arg1 context.Context
		arg2 snapshot.SnapshotID
	}{arg1, arg2})
	stub := fake.FindReviewInputStub
	fakeReturns := fake.findReviewInputReturns
	fake.recordInvocation("FindReviewInput", []interface{}{arg1, arg2})
	fake.findReviewInputMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentReviewsFactory) FindReviewInputCallCount() int {
	fake.findReviewInputMutex.RLock()
	defer fake.findReviewInputMutex.RUnlock()
	return len(fake.findReviewInputArgsForCall)
}

func (fake *FakeAgentReviewsFactory) FindReviewInputCalls(stub func(context.Context, snapshot.SnapshotID) (projection.ReviewInput, bool, error)) {
	fake.findReviewInputMutex.Lock()
	defer fake.findReviewInputMutex.Unlock()
	fake.FindReviewInputStub = stub
}

func (fake *FakeAgentReviewsFactory) FindReviewInputArgsForCall(i int) (context.Context, snapshot.SnapshotID) {
	fake.findReviewInputMutex.RLock()
	defer fake.findReviewInputMutex.RUnlock()
	argsForCall := fake.findReviewInputArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) FindReviewInputReturns(result1 projection.ReviewInput, result2 bool, result3 error) {
	fake.findReviewInputMutex.Lock()
	defer fake.findReviewInputMutex.Unlock()
	fake.FindReviewInputStub = nil
	fake.findReviewInputReturns = struct {
		result1 projection.ReviewInput
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentReviewsFactory) FindReviewInputReturnsOnCall(i int, result1 projection.ReviewInput, result2 bool, result3 error) {
	fake.findReviewInputMutex.Lock()
	defer fake.findReviewInputMutex.Unlock()
	fake.FindReviewInputStub = nil
	if fake.findReviewInputReturnsOnCall == nil {
		fake.findReviewInputReturnsOnCall = make(map[int]struct {
			result1 projection.ReviewInput
			result2 bool
			result3 error
		})
	}
	fake.findReviewInputReturnsOnCall[i] = struct {
		result1 projection.ReviewInput
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentReviewsFactory) GetByBuild(arg1 int) ([]reviews.StoredReview, error) {
	fake.getByBuildMutex.Lock()
	ret, specificReturn := fake.getByBuildReturnsOnCall[len(fake.getByBuildArgsForCall)]
	fake.getByBuildArgsForCall = append(fake.getByBuildArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetByBuildStub
	fakeReturns := fake.getByBuildReturns
	fake.recordInvocation("GetByBuild", []interface{}{arg1})
	fake.getByBuildMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) GetByBuildCallCount() int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	return len(fake.getByBuildArgsForCall)
}

func (fake *FakeAgentReviewsFactory) GetByBuildCalls(stub func(int) ([]reviews.StoredReview, error)) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = stub
}

func (fake *FakeAgentReviewsFactory) GetByBuildArgsForCall(i int) int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	argsForCall := fake.getByBuildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) GetByBuildReturns(result1 []reviews.StoredReview, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	fake.getByBuildReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) GetByBuildReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	if fake.getByBuildReturnsOnCall == nil {
		fake.getByBuildReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.getByBuildReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) GetBySnapshot(arg1 string, arg2 snapshot.SnapshotID) (reviews.StoredReview, bool, error) {
	fake.getBySnapshotMutex.Lock()
	ret, specificReturn := fake.getBySnapshotReturnsOnCall[len(fake.getBySnapshotArgsForCall)]
	fake.getBySnapshotArgsForCall = append(fake.getBySnapshotArgsForCall, struct {
		arg1 string
		arg2 snapshot.SnapshotID
	}{arg1, arg2})
	stub := fake.GetBySnapshotStub
	fakeReturns := fake.getBySnapshotReturns
	fake.recordInvocation("GetBySnapshot", []interface{}{arg1, arg2})
	fake.getBySnapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentReviewsFactory) GetBySnapshotCallCount() int {
	fake.getBySnapshotMutex.RLock()
	defer fake.getBySnapshotMutex.RUnlock()
	return len(fake.getBySnapshotArgsForCall)
}

func (fake *FakeAgentReviewsFactory) GetBySnapshotCalls(stub func(string, snapshot.SnapshotID) (reviews.StoredReview, bool, error)) {
	fake.getBySnapshotMutex.Lock()
	defer fake.getBySnapshotMutex.Unlock()
	fake.GetBySnapshotStub = stub
}

func (fake *FakeAgentReviewsFactory) GetBySnapshotArgsForCall(i int) (string, snapshot.SnapshotID) {
	fake.getBySnapshotMutex.RLock()
	defer fake.getBySnapshotMutex.RUnlock()
	argsForCall := fake.getBySnapshotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) GetBySnapshotReturns(result1 reviews.StoredReview, result2 bool, result3 error) {
	fake.getBySnapshotMutex.Lock()
	defer fake.getBySnapshotMutex.Unlock()
	fake.GetBySnapshotStub = nil
	fake.getBySnapshotReturns = struct {
		result1 reviews.StoredReview
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentReviewsFactory) GetBySnapshotReturnsOnCall(i int, result1 reviews.StoredReview, result2 bool, result3 error) {
	fake.getBySnapshotMutex.Lock()
	defer fake.getBySnapshotMutex.Unlock()
	fake.GetBySnapshotStub = nil
	if fake.getBySnapshotReturnsOnCall == nil {
		fake.getBySnapshotReturnsOnCall = make(map[int]struct {
			result1 reviews.StoredReview
			result2 bool
			result3 error
		})
	}
	fake.getBySnapshotReturnsOnCall[i] = struct {
		result1 reviews.StoredReview
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentReviewsFactory) ListByTeam(arg1 string, arg2 reviews.ListFilter) ([]reviews.StoredReview, error) {
	fake.listByTeamMutex.Lock()
	ret, specificReturn := fake.listByTeamReturnsOnCall[len(fake.listByTeamArgsForCall)]
	fake.listByTeamArgsForCall = append(fake.listByTeamArgsForCall, struct {
		arg1 string
		arg2 reviews.ListFilter
	}{arg1, arg2})
	stub := fake.ListByTeamStub
	fakeReturns := fake.listByTeamReturns
	fake.recordInvocation("ListByTeam", []interface{}{arg1, arg2})
	fake.listByTeamMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListByTeamCallCount() int {
	fake.listByTeamMutex.RLock()
	defer fake.listByTeamMutex.RUnlock()
	return len(fake.listByTeamArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListByTeamCalls(stub func(string, reviews.ListFilter) ([]reviews.StoredReview, error)) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = stub
}

func (fake *FakeAgentReviewsFactory) ListByTeamArgsForCall(i int) (string, reviews.ListFilter) {
	fake.listByTeamMutex.RLock()
	defer fake.listByTeamMutex.RUnlock()
	argsForCall := fake.listByTeamArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) ListByTeamReturns(result1 []reviews.StoredReview, result2 error) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = nil
	fake.listByTeamReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTeamReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = nil
	if fake.listByTeamReturnsOnCall == nil {
		fake.listByTeamReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.listByTeamReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTicket(arg1 int) ([]reviews.StoredReview, error) {
	fake.listByTicketMutex.Lock()
	ret, specificReturn := fake.listByTicketReturnsOnCall[len(fake.listByTicketArgsForCall)]
	fake.listByTicketArgsForCall = append(fake.listByTicketArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.ListByTicketStub
	fakeReturns := fake.listByTicketReturns
	fake.recordInvocation("ListByTicket", []interface{}{arg1})
	fake.listByTicketMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListByTicketCallCount() int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	return len(fake.listByTicketArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListByTicketCalls(stub func(int) ([]reviews.StoredReview, error)) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = stub
}

func (fake *FakeAgentReviewsFactory) ListByTicketArgsForCall(i int) int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	argsForCall := fake.listByTicketArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) ListByTicketReturns(result1 []reviews.StoredReview, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	fake.listByTicketReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTicketReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	if fake.listByTicketReturnsOnCall == nil {
		fake.listByTicketReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.listByTicketReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRun(arg1, arg2 string, arg3 snapshot.WorkflowRunID) ([]reviews.StoredReview, error) {
	fake.listByWorkflowRunMutex.Lock()
	ret, specificReturn := fake.listByWorkflowRunReturnsOnCall[len(fake.listByWorkflowRunArgsForCall)]
	fake.listByWorkflowRunArgsForCall = append(fake.listByWorkflowRunArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 snapshot.WorkflowRunID
	}{arg1, arg2, arg3})
	stub := fake.ListByWorkflowRunStub
	fakeReturns := fake.listByWorkflowRunReturns
	fake.recordInvocation("ListByWorkflowRun", []interface{}{arg1, arg2, arg3})
	fake.listByWorkflowRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRunCallCount() int {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	return len(fake.listByWorkflowRunArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRunCalls(stub func(string, string, snapshot.WorkflowRunID) ([]reviews.StoredReview, error)) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = stub
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRunArgsForCall(i int) (string, string, snapshot.WorkflowRunID) {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	argsForCall := fake.listByWorkflowRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRunReturns(result1 []reviews.StoredReview, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	fake.listByWorkflowRunReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByWorkflowRunReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	if fake.listByWorkflowRunReturnsOnCall == nil {
		fake.listByWorkflowRunReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.listByWorkflowRunReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviews(arg1 context.Context, arg2 int) ([]snapshot.SnapshotRef, error) {
	fake.listUnprojectedReviewsMutex.Lock()
	ret, specificReturn := fake.listUnprojectedReviewsReturnsOnCall[len(fake.listUnprojectedReviewsArgsForCall)]
	fake.listUnprojectedReviewsArgsForCall = append(fake.listUnprojectedReviewsArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.ListUnprojectedReviewsStub
	fakeReturns := fake.listUnprojectedReviewsReturns
	fake.recordInvocation("ListUnprojectedReviews", []interface{}{arg1, arg2})
	fake.listUnprojectedReviewsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviewsCallCount() int {
	fake.listUnprojectedReviewsMutex.RLock()
	defer fake.listUnprojectedReviewsMutex.RUnlock()
	return len(fake.listUnprojectedReviewsArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviewsCalls(stub func(context.Context, int) ([]snapshot.SnapshotRef, error)) {
	fake.listUnprojectedReviewsMutex.Lock()
	defer fake.listUnprojectedReviewsMutex.Unlock()
	fake.ListUnprojectedReviewsStub = stub
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviewsArgsForCall(i int) (context.Context, int) {
	fake.listUnprojectedReviewsMutex.RLock()
	defer fake.listUnprojectedReviewsMutex.RUnlock()
	argsForCall := fake.listUnprojectedReviewsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviewsReturns(result1 []snapshot.SnapshotRef, result2 error) {
	fake.listUnprojectedReviewsMutex.Lock()
	defer fake.listUnprojectedReviewsMutex.Unlock()
	fake.ListUnprojectedReviewsStub = nil
	fake.listUnprojectedReviewsReturns = struct {
		result1 []snapshot.SnapshotRef
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListUnprojectedReviewsReturnsOnCall(i int, result1 []snapshot.SnapshotRef, result2 error) {
	fake.listUnprojectedReviewsMutex.Lock()
	defer fake.listUnprojectedReviewsMutex.Unlock()
	fake.ListUnprojectedReviewsStub = nil
	if fake.listUnprojectedReviewsReturnsOnCall == nil {
		fake.listUnprojectedReviewsReturnsOnCall = make(map[int]struct {
			result1 []snapshot.SnapshotRef
			result2 error
		})
	}
	fake.listUnprojectedReviewsReturnsOnCall[i] = struct {
		result1 []snapshot.SnapshotRef
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) Upsert(arg1 *reviews.StoredReview) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 *reviews.StoredReview
	}{arg1})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentReviewsFactory) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeAgentReviewsFactory) UpsertCalls(stub func(*reviews.StoredReview) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeAgentReviewsFactory) UpsertArgsForCall(i int) *reviews.StoredReview {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjection(arg1 context.Context, arg2 *reviews.StoredReview) error {
	fake.upsertReviewProjectionMutex.Lock()
	ret, specificReturn := fake.upsertReviewProjectionReturnsOnCall[len(fake.upsertReviewProjectionArgsForCall)]
	fake.upsertReviewProjectionArgsForCall = append(fake.upsertReviewProjectionArgsForCall, struct {
		arg1 context.Context
		arg2 *reviews.StoredReview
	}{arg1, arg2})
	stub := fake.UpsertReviewProjectionStub
	fakeReturns := fake.upsertReviewProjectionReturns
	fake.recordInvocation("UpsertReviewProjection", []interface{}{arg1, arg2})
	fake.upsertReviewProjectionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjectionCallCount() int {
	fake.upsertReviewProjectionMutex.RLock()
	defer fake.upsertReviewProjectionMutex.RUnlock()
	return len(fake.upsertReviewProjectionArgsForCall)
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjectionCalls(stub func(context.Context, *reviews.StoredReview) error) {
	fake.upsertReviewProjectionMutex.Lock()
	defer fake.upsertReviewProjectionMutex.Unlock()
	fake.UpsertReviewProjectionStub = stub
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjectionArgsForCall(i int) (context.Context, *reviews.StoredReview) {
	fake.upsertReviewProjectionMutex.RLock()
	defer fake.upsertReviewProjectionMutex.RUnlock()
	argsForCall := fake.upsertReviewProjectionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjectionReturns(result1 error) {
	fake.upsertReviewProjectionMutex.Lock()
	defer fake.upsertReviewProjectionMutex.Unlock()
	fake.UpsertReviewProjectionStub = nil
	fake.upsertReviewProjectionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) UpsertReviewProjectionReturnsOnCall(i int, result1 error) {
	fake.upsertReviewProjectionMutex.Lock()
	defer fake.upsertReviewProjectionMutex.Unlock()
	fake.UpsertReviewProjectionStub = nil
	if fake.upsertReviewProjectionReturnsOnCall == nil {
		fake.upsertReviewProjectionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReviewProjectionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentReviewsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentReviewsFactory = new(FakeAgentReviewsFactory)
