// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"context"
	"sync"

	"github.com/concourse/concourse/agent/api/tickets"
	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/agent/workitem"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentTicketsFactory struct {
	ActivePlanStub        func(int) ([]tickets.Task, error)
	activePlanMutex       sync.RWMutex
	activePlanArgsForCall []struct {
		arg1 int
	}
	activePlanReturns struct {
		result1 []tickets.Task
		result2 error
	}
	activePlanReturnsOnCall map[int]struct {
		result1 []tickets.Task
		result2 error
	}
	AnswerCommentStub        func(int, int, string, string) error
	answerCommentMutex       sync.RWMutex
	answerCommentArgsForCall []struct {
		arg1 int
		arg2 int
		arg3 string
		arg4 string
	}
	answerCommentReturns struct {
		result1 error
	}
	answerCommentReturnsOnCall map[int]struct {
		result1 error
	}
	AppendCommentStub        func(int, tickets.Comment) (int, error)
	appendCommentMutex       sync.RWMutex
	appendCommentArgsForCall []struct {
		arg1 int
		arg2 tickets.Comment
	}
	appendCommentReturns struct {
		result1 int
		result2 error
	}
	appendCommentReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	AppendTaskNoteStub        func(int, int, int, string) error
	appendTaskNoteMutex       sync.RWMutex
	appendTaskNoteArgsForCall []struct {
		arg1 int
		arg2 int
		arg3 int
		arg4 string
	}
	appendTaskNoteReturns struct {
		result1 error
	}
	appendTaskNoteReturnsOnCall map[int]struct {
		result1 error
	}
	CaptureRevisionStub        func(context.Context, int) (workitem.CapturedRevision, bool, error)
	captureRevisionMutex       sync.RWMutex
	captureRevisionArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	captureRevisionReturns struct {
		result1 workitem.CapturedRevision
		result2 bool
		result3 error
	}
	captureRevisionReturnsOnCall map[int]struct {
		result1 workitem.CapturedRevision
		result2 bool
		result3 error
	}
	CommentsStub        func(int) ([]tickets.Comment, error)
	commentsMutex       sync.RWMutex
	commentsArgsForCall []struct {
		arg1 int
	}
	commentsReturns struct {
		result1 []tickets.Comment
		result2 error
	}
	commentsReturnsOnCall map[int]struct {
		result1 []tickets.Comment
		result2 error
	}
	CreateStub        func(*tickets.Ticket) (int, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *tickets.Ticket
	}
	createReturns struct {
		result1 int
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	GetStub        func(int) (*tickets.Ticket, bool, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 int
	}
	getReturns struct {
		result1 *tickets.Ticket
		result2 bool
		result3 error
	}
	getReturnsOnCall map[int]struct {
		result1 *tickets.Ticket
		result2 bool
		result3 error
	}
	LatestSpecStub        func(int) (*tickets.Spec, bool, error)
	latestSpecMutex       sync.RWMutex
	latestSpecArgsForCall []struct {
		arg1 int
	}
	latestSpecReturns struct {
		result1 *tickets.Spec
		result2 bool
		result3 error
	}
	latestSpecReturnsOnCall map[int]struct {
		result1 *tickets.Spec
		result2 bool
		result3 error
	}
	ListStub        func(tickets.ListFilter) ([]tickets.Ticket, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 tickets.ListFilter
	}
	listReturns struct {
		result1 []tickets.Ticket
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []tickets.Ticket
		result2 error
	}
	RecordDispatchRunStub        func(context.Context, int, string, snapshot.WorkflowRunID, int) error
	recordDispatchRunMutex       sync.RWMutex
	recordDispatchRunArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 string
		arg4 snapshot.WorkflowRunID
		arg5 int
	}
	recordDispatchRunReturns struct {
		result1 error
	}
	recordDispatchRunReturnsOnCall map[int]struct {
		result1 error
	}
	RecordDispatchWorkItemStub        func(context.Context, int, string, int64, snapshot.SnapshotID) error
	recordDispatchWorkItemMutex       sync.RWMutex
	recordDispatchWorkItemArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 string
		arg4 int64
		arg5 snapshot.SnapshotID
	}
	recordDispatchWorkItemReturns struct {
		result1 error
	}
	recordDispatchWorkItemReturnsOnCall map[int]struct {
		result1 error
	}
	ReserveDispatchStub        func(context.Context, int, tickets.DispatchReservationRequest) (tickets.DispatchReservation, error)
	reserveDispatchMutex       sync.RWMutex
	reserveDispatchArgsForCall []struct {
		arg1 context.Context
		arg2 int
		arg3 tickets.DispatchReservationRequest
	}
	reserveDispatchReturns struct {
		result1 tickets.DispatchReservation
		result2 error
	}
	reserveDispatchReturnsOnCall map[int]struct {
		result1 tickets.DispatchReservation
		result2 error
	}
	SubmitPlanStub        func(int, []tickets.Task) (int, error)
	submitPlanMutex       sync.RWMutex
	submitPlanArgsForCall []struct {
		arg1 int
		arg2 []tickets.Task
	}
	submitPlanReturns struct {
		result1 int
		result2 error
	}
	submitPlanReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	SubmitSpecStub        func(int, tickets.Spec) (int, error)
	submitSpecMutex       sync.RWMutex
	submitSpecArgsForCall []struct {
		arg1 int
		arg2 tickets.Spec
	}
	submitSpecReturns struct {
		result1 int
		result2 error
	}
	submitSpecReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	TransitionStub        func(int, tickets.State, tickets.State, tickets.TransitionMeta) error
	transitionMutex       sync.RWMutex
	transitionArgsForCall []struct {
		arg1 int
		arg2 tickets.State
		arg3 tickets.State
		arg4 tickets.TransitionMeta
	}
	transitionReturns struct {
		result1 error
	}
	transitionReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStub        func(int, tickets.Update) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 int
		arg2 tickets.Update
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateActiveTaskStub        func(int, int, tickets.TaskStatus, string) (int, error)
	updateActiveTaskMutex       sync.RWMutex
	updateActiveTaskArgsForCall []struct {
		arg1 int
		arg2 int
		arg3 tickets.TaskStatus
		arg4 string
	}
	updateActiveTaskReturns struct {
		result1 int
		result2 error
	}
	updateActiveTaskReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	UpdateTaskStatusStub        func(int, int, int, tickets.TaskStatus) error
	updateTaskStatusMutex       sync.RWMutex
	updateTaskStatusArgsForCall []struct {
		arg1 int
		arg2 int
		arg3 int
		arg4 tickets.TaskStatus
	}
	updateTaskStatusReturns struct {
		result1 error
	}
	updateTaskStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentTicketsFactory) ActivePlan(arg1 int) ([]tickets.Task, error) {
	fake.activePlanMutex.Lock()
	ret, specificReturn := fake.activePlanReturnsOnCall[len(fake.activePlanArgsForCall)]
	fake.activePlanArgsForCall = append(fake.activePlanArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.ActivePlanStub
	fakeReturns := fake.activePlanReturns
	fake.recordInvocation("ActivePlan", []interface{}{arg1})
	fake.activePlanMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) ActivePlanCallCount() int {
	fake.activePlanMutex.RLock()
	defer fake.activePlanMutex.RUnlock()
	return len(fake.activePlanArgsForCall)
}

func (fake *FakeAgentTicketsFactory) ActivePlanCalls(stub func(int) ([]tickets.Task, error)) {
	fake.activePlanMutex.Lock()
	defer fake.activePlanMutex.Unlock()
	fake.ActivePlanStub = stub
}

func (fake *FakeAgentTicketsFactory) ActivePlanArgsForCall(i int) int {
	fake.activePlanMutex.RLock()
	defer fake.activePlanMutex.RUnlock()
	argsForCall := fake.activePlanArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) ActivePlanReturns(result1 []tickets.Task, result2 error) {
	fake.activePlanMutex.Lock()
	defer fake.activePlanMutex.Unlock()
	fake.ActivePlanStub = nil
	fake.activePlanReturns = struct {
		result1 []tickets.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) ActivePlanReturnsOnCall(i int, result1 []tickets.Task, result2 error) {
	fake.activePlanMutex.Lock()
	defer fake.activePlanMutex.Unlock()
	fake.ActivePlanStub = nil
	if fake.activePlanReturnsOnCall == nil {
		fake.activePlanReturnsOnCall = make(map[int]struct {
			result1 []tickets.Task
			result2 error
		})
	}
	fake.activePlanReturnsOnCall[i] = struct {
		result1 []tickets.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) AnswerComment(arg1 int, arg2 int, arg3 string, arg4 string) error {
	fake.answerCommentMutex.Lock()
	ret, specificReturn := fake.answerCommentReturnsOnCall[len(fake.answerCommentArgsForCall)]
	fake.answerCommentArgsForCall = append(fake.answerCommentArgsForCall, struct {
		arg1 int
		arg2 int
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.AnswerCommentStub
	fakeReturns := fake.answerCommentReturns
	fake.recordInvocation("AnswerComment", []interface{}{arg1, arg2, arg3, arg4})
	fake.answerCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) AnswerCommentCallCount() int {
	fake.answerCommentMutex.RLock()
	defer fake.answerCommentMutex.RUnlock()
	return len(fake.answerCommentArgsForCall)
}

func (fake *FakeAgentTicketsFactory) AnswerCommentCalls(stub func(int, int, string, string) error) {
	fake.answerCommentMutex.Lock()
	defer fake.answerCommentMutex.Unlock()
	fake.AnswerCommentStub = stub
}

func (fake *FakeAgentTicketsFactory) AnswerCommentArgsForCall(i int) (int, int, string, string) {
	fake.answerCommentMutex.RLock()
	defer fake.answerCommentMutex.RUnlock()
	argsForCall := fake.answerCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAgentTicketsFactory) AnswerCommentReturns(result1 error) {
	fake.answerCommentMutex.Lock()
	defer fake.answerCommentMutex.Unlock()
	fake.AnswerCommentStub = nil
	fake.answerCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) AnswerCommentReturnsOnCall(i int, result1 error) {
	fake.answerCommentMutex.Lock()
	defer fake.answerCommentMutex.Unlock()
	fake.AnswerCommentStub = nil
	if fake.answerCommentReturnsOnCall == nil {
		fake.answerCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.answerCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) AppendComment(arg1 int, arg2 tickets.Comment) (int, error) {
	fake.appendCommentMutex.Lock()
	ret, specificReturn := fake.appendCommentReturnsOnCall[len(fake.appendCommentArgsForCall)]
	fake.appendCommentArgsForCall = append(fake.appendCommentArgsForCall, struct {
		arg1 int
		arg2 tickets.Comment
	}{arg1, arg2})
	stub := fake.AppendCommentStub
	fakeReturns := fake.appendCommentReturns
	fake.recordInvocation("AppendComment", []interface{}{arg1, arg2})
	fake.appendCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) AppendCommentCallCount() int {
	fake.appendCommentMutex.RLock()
	defer fake.appendCommentMutex.RUnlock()
	return len(fake.appendCommentArgsForCall)
}

func (fake *FakeAgentTicketsFactory) AppendCommentCalls(stub func(int, tickets.Comment) (int, error)) {
	fake.appendCommentMutex.Lock()
	defer fake.appendCommentMutex.Unlock()
	fake.AppendCommentStub = stub
}

func (fake *FakeAgentTicketsFactory) AppendCommentArgsForCall(i int) (int, tickets.Comment) {
	fake.appendCommentMutex.RLock()
	defer fake.appendCommentMutex.RUnlock()
	argsForCall := fake.appendCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentTicketsFactory) AppendCommentReturns(result1 int, result2 error) {
	fake.appendCommentMutex.Lock()
	defer fake.appendCommentMutex.Unlock()
	fake.AppendCommentStub = nil
	fake.appendCommentReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) AppendCommentReturnsOnCall(i int, result1 int, result2 error) {
	fake.appendCommentMutex.Lock()
	defer fake.appendCommentMutex.Unlock()
	fake.AppendCommentStub = nil
	if fake.appendCommentReturnsOnCall == nil {
		fake.appendCommentReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.appendCommentReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) AppendTaskNote(arg1 int, arg2 int, arg3 int, arg4 string) error {
	fake.appendTaskNoteMutex.Lock()
	ret, specificReturn := fake.appendTaskNoteReturnsOnCall[len(fake.appendTaskNoteArgsForCall)]
	fake.appendTaskNoteArgsForCall = append(fake.appendTaskNoteArgsForCall, struct {
		arg1 int
		arg2 int
		arg3 int
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.AppendTaskNoteStub
	fakeReturns := fake.appendTaskNoteReturns
	fake.recordInvocation("AppendTaskNote", []interface{}{arg1, arg2, arg3, arg4})
	fake.appendTaskNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) AppendTaskNoteCallCount() int {
	fake.appendTaskNoteMutex.RLock()
	defer fake.appendTaskNoteMutex.RUnlock()
	return len(fake.appendTaskNoteArgsForCall)
}

func (fake *FakeAgentTicketsFactory) AppendTaskNoteCalls(stub func(int, int, int, string) error) {
	fake.appendTaskNoteMutex.Lock()
	defer fake.appendTaskNoteMutex.Unlock()
	fake.AppendTaskNoteStub = stub
}

func (fake *FakeAgentTicketsFactory) AppendTaskNoteArgsForCall(i int) (int, int, int, string) {
	fake.appendTaskNoteMutex.RLock()
	defer fake.appendTaskNoteMutex.RUnlock()
	argsForCall := fake.appendTaskNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAgentTicketsFactory) AppendTaskNoteReturns(result1 error) {
	fake.appendTaskNoteMutex.Lock()
	defer fake.appendTaskNoteMutex.Unlock()
	fake.AppendTaskNoteStub = nil
	fake.appendTaskNoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) AppendTaskNoteReturnsOnCall(i int, result1 error) {
	fake.appendTaskNoteMutex.Lock()
	defer fake.appendTaskNoteMutex.Unlock()
	fake.AppendTaskNoteStub = nil
	if fake.appendTaskNoteReturnsOnCall == nil {
		fake.appendTaskNoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appendTaskNoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) CaptureRevision(arg1 context.Context, arg2 int) (workitem.CapturedRevision, bool, error) {
	fake.captureRevisionMutex.Lock()
	ret, specificReturn := fake.captureRevisionReturnsOnCall[len(fake.captureRevisionArgsForCall)]
	fake.captureRevisionArgsForCall = append(fake.captureRevisionArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.CaptureRevisionStub
	fakeReturns := fake.captureRevisionReturns
	fake.recordInvocation("CaptureRevision", []interface{}{arg1, arg2})
	fake.captureRevisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentTicketsFactory) CaptureRevisionCallCount() int {
	fake.captureRevisionMutex.RLock()
	defer fake.captureRevisionMutex.RUnlock()
	return len(fake.captureRevisionArgsForCall)
}

func (fake *FakeAgentTicketsFactory) CaptureRevisionCalls(stub func(context.Context, int) (workitem.CapturedRevision, bool, error)) {
	fake.captureRevisionMutex.Lock()
	defer fake.captureRevisionMutex.Unlock()
	fake.CaptureRevisionStub = stub
}

func (fake *FakeAgentTicketsFactory) CaptureRevisionArgsForCall(i int) (context.Context, int) {
	fake.captureRevisionMutex.RLock()
	defer fake.captureRevisionMutex.RUnlock()
	argsForCall := fake.captureRevisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentTicketsFactory) CaptureRevisionReturns(result1 workitem.CapturedRevision, result2 bool, result3 error) {
	fake.captureRevisionMutex.Lock()
	defer fake.captureRevisionMutex.Unlock()
	fake.CaptureRevisionStub = nil
	fake.captureRevisionReturns = struct {
		result1 workitem.CapturedRevision
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) CaptureRevisionReturnsOnCall(i int, result1 workitem.CapturedRevision, result2 bool, result3 error) {
	fake.captureRevisionMutex.Lock()
	defer fake.captureRevisionMutex.Unlock()
	fake.CaptureRevisionStub = nil
	if fake.captureRevisionReturnsOnCall == nil {
		fake.captureRevisionReturnsOnCall = make(map[int]struct {
			result1 workitem.CapturedRevision
			result2 bool
			result3 error
		})
	}
	fake.captureRevisionReturnsOnCall[i] = struct {
		result1 workitem.CapturedRevision
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) Comments(arg1 int) ([]tickets.Comment, error) {
	fake.commentsMutex.Lock()
	ret, specificReturn := fake.commentsReturnsOnCall[len(fake.commentsArgsForCall)]
	fake.commentsArgsForCall = append(fake.commentsArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.CommentsStub
	fakeReturns := fake.commentsReturns
	fake.recordInvocation("Comments", []interface{}{arg1})
	fake.commentsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) CommentsCallCount() int {
	fake.commentsMutex.RLock()
	defer fake.commentsMutex.RUnlock()
	return len(fake.commentsArgsForCall)
}

func (fake *FakeAgentTicketsFactory) CommentsCalls(stub func(int) ([]tickets.Comment, error)) {
	fake.commentsMutex.Lock()
	defer fake.commentsMutex.Unlock()
	fake.CommentsStub = stub
}

func (fake *FakeAgentTicketsFactory) CommentsArgsForCall(i int) int {
	fake.commentsMutex.RLock()
	defer fake.commentsMutex.RUnlock()
	argsForCall := fake.commentsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) CommentsReturns(result1 []tickets.Comment, result2 error) {
	fake.commentsMutex.Lock()
	defer fake.commentsMutex.Unlock()
	fake.CommentsStub = nil
	fake.commentsReturns = struct {
		result1 []tickets.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) CommentsReturnsOnCall(i int, result1 []tickets.Comment, result2 error) {
	fake.commentsMutex.Lock()
	defer fake.commentsMutex.Unlock()
	fake.CommentsStub = nil
	if fake.commentsReturnsOnCall == nil {
		fake.commentsReturnsOnCall = make(map[int]struct {
			result1 []tickets.Comment
			result2 error
		})
	}
	fake.commentsReturnsOnCall[i] = struct {
		result1 []tickets.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) Create(arg1 *tickets.Ticket) (int, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *tickets.Ticket
	}{arg1})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeAgentTicketsFactory) CreateCalls(stub func(*tickets.Ticket) (int, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeAgentTicketsFactory) CreateArgsForCall(i int) *tickets.Ticket {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) CreateReturns(result1 int, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) CreateReturnsOnCall(i int, result1 int, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) Get(arg1 int) (*tickets.Ticket, bool, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentTicketsFactory) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeAgentTicketsFactory) GetCalls(stub func(int) (*tickets.Ticket, bool, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeAgentTicketsFactory) GetArgsForCall(i int) int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) GetReturns(result1 *tickets.Ticket, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *tickets.Ticket
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) GetReturnsOnCall(i int, result1 *tickets.Ticket, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *tickets.Ticket
			result2 bool
			result3 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *tickets.Ticket
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) LatestSpec(arg1 int) (*tickets.Spec, bool, error) {
	fake.latestSpecMutex.Lock()
	ret, specificReturn := fake.latestSpecReturnsOnCall[len(fake.latestSpecArgsForCall)]
	fake.latestSpecArgsForCall = append(fake.latestSpecArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.LatestSpecStub
	fakeReturns := fake.latestSpecReturns
	fake.recordInvocation("LatestSpec", []interface{}{arg1})
	fake.latestSpecMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentTicketsFactory) LatestSpecCallCount() int {
	fake.latestSpecMutex.RLock()
	defer fake.latestSpecMutex.RUnlock()
	return len(fake.latestSpecArgsForCall)
}

func (fake *FakeAgentTicketsFactory) LatestSpecCalls(stub func(int) (*tickets.Spec, bool, error)) {
	fake.latestSpecMutex.Lock()
	defer fake.latestSpecMutex.Unlock()
	fake.LatestSpecStub = stub
}

func (fake *FakeAgentTicketsFactory) LatestSpecArgsForCall(i int) int {
	fake.latestSpecMutex.RLock()
	defer fake.latestSpecMutex.RUnlock()
	argsForCall := fake.latestSpecArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) LatestSpecReturns(result1 *tickets.Spec, result2 bool, result3 error) {
	fake.latestSpecMutex.Lock()
	defer fake.latestSpecMutex.Unlock()
	fake.LatestSpecStub = nil
	fake.latestSpecReturns = struct {
		result1 *tickets.Spec
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) LatestSpecReturnsOnCall(i int, result1 *tickets.Spec, result2 bool, result3 error) {
	fake.latestSpecMutex.Lock()
	defer fake.latestSpecMutex.Unlock()
	fake.LatestSpecStub = nil
	if fake.latestSpecReturnsOnCall == nil {
		fake.latestSpecReturnsOnCall = make(map[int]struct {
			result1 *tickets.Spec
			result2 bool
			result3 error
		})
	}
	fake.latestSpecReturnsOnCall[i] = struct {
		result1 *tickets.Spec
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentTicketsFactory) List(arg1 tickets.ListFilter) ([]tickets.Ticket, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 tickets.ListFilter
	}{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeAgentTicketsFactory) ListCalls(stub func(tickets.ListFilter) ([]tickets.Ticket, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeAgentTicketsFactory) ListArgsForCall(i int) tickets.ListFilter {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentTicketsFactory) ListReturns(result1 []tickets.Ticket, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []tickets.Ticket
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) ListReturnsOnCall(i int, result1 []tickets.Ticket, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []tickets.Ticket
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []tickets.Ticket
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRun(arg1 context.Context, arg2 int, arg3 string, arg4 snapshot.WorkflowRunID, arg5 int) error {
	fake.recordDispatchRunMutex.Lock()
	ret, specificReturn := fake.recordDispatchRunReturnsOnCall[len(fake.recordDispatchRunArgsForCall)]
	fake.recordDispatchRunArgsForCall = append(fake.recordDispatchRunArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 string
		arg4 snapshot.WorkflowRunID
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RecordDispatchRunStub
	fakeReturns := fake.recordDispatchRunReturns
	fake.recordInvocation("RecordDispatchRun", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.recordDispatchRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRunCallCount() int {
	fake.recordDispatchRunMutex.RLock()
	defer fake.recordDispatchRunMutex.RUnlock()
	return len(fake.recordDispatchRunArgsForCall)
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRunCalls(stub func(context.Context, int, string, snapshot.WorkflowRunID, int) error) {
	fake.recordDispatchRunMutex.Lock()
	defer fake.recordDispatchRunMutex.Unlock()
	fake.RecordDispatchRunStub = stub
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRunArgsForCall(i int) (context.Context, int, string, snapshot.WorkflowRunID, int) {
	fake.recordDispatchRunMutex.RLock()
	defer fake.recordDispatchRunMutex.RUnlock()
	argsForCall := fake.recordDispatchRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRunReturns(result1 error) {
	fake.recordDispatchRunMutex.Lock()
	defer fake.recordDispatchRunMutex.Unlock()
	fake.RecordDispatchRunStub = nil
	fake.recordDispatchRunReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) RecordDispatchRunReturnsOnCall(i int, result1 error) {
	fake.recordDispatchRunMutex.Lock()
	defer fake.recordDispatchRunMutex.Unlock()
	fake.RecordDispatchRunStub = nil
	if fake.recordDispatchRunReturnsOnCall == nil {
		fake.recordDispatchRunReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.recordDispatchRunReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItem(arg1 context.Context, arg2 int, arg3 string, arg4 int64, arg5 snapshot.SnapshotID) error {
	fake.recordDispatchWorkItemMutex.Lock()
	ret, specificReturn := fake.recordDispatchWorkItemReturnsOnCall[len(fake.recordDispatchWorkItemArgsForCall)]
	fake.recordDispatchWorkItemArgsForCall = append(fake.recordDispatchWorkItemArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 string
		arg4 int64
		arg5 snapshot.SnapshotID
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RecordDispatchWorkItemStub
	fakeReturns := fake.recordDispatchWorkItemReturns
	fake.recordInvocation("RecordDispatchWorkItem", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.recordDispatchWorkItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItemCallCount() int {
	fake.recordDispatchWorkItemMutex.RLock()
	defer fake.recordDispatchWorkItemMutex.RUnlock()
	return len(fake.recordDispatchWorkItemArgsForCall)
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItemCalls(stub func(context.Context, int, string, int64, snapshot.SnapshotID) error) {
	fake.recordDispatchWorkItemMutex.Lock()
	defer fake.recordDispatchWorkItemMutex.Unlock()
	fake.RecordDispatchWorkItemStub = stub
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItemArgsForCall(i int) (context.Context, int, string, int64, snapshot.SnapshotID) {
	fake.recordDispatchWorkItemMutex.RLock()
	defer fake.recordDispatchWorkItemMutex.RUnlock()
	argsForCall := fake.recordDispatchWorkItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItemReturns(result1 error) {
	fake.recordDispatchWorkItemMutex.Lock()
	defer fake.recordDispatchWorkItemMutex.Unlock()
	fake.RecordDispatchWorkItemStub = nil
	fake.recordDispatchWorkItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) RecordDispatchWorkItemReturnsOnCall(i int, result1 error) {
	fake.recordDispatchWorkItemMutex.Lock()
	defer fake.recordDispatchWorkItemMutex.Unlock()
	fake.RecordDispatchWorkItemStub = nil
	if fake.recordDispatchWorkItemReturnsOnCall == nil {
		fake.recordDispatchWorkItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.recordDispatchWorkItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) ReserveDispatch(arg1 context.Context, arg2 int, arg3 tickets.DispatchReservationRequest) (tickets.DispatchReservation, error) {
	fake.reserveDispatchMutex.Lock()
	ret, specificReturn := fake.reserveDispatchReturnsOnCall[len(fake.reserveDispatchArgsForCall)]
	fake.reserveDispatchArgsForCall = append(fake.reserveDispatchArgsForCall, struct {
		arg1 context.Context
		arg2 int
		arg3 tickets.DispatchReservationRequest
	}{arg1, arg2, arg3})
	stub := fake.ReserveDispatchStub
	fakeReturns := fake.reserveDispatchReturns
	fake.recordInvocation("ReserveDispatch", []interface{}{arg1, arg2, arg3})
	fake.reserveDispatchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) ReserveDispatchCallCount() int {
	fake.reserveDispatchMutex.RLock()
	defer fake.reserveDispatchMutex.RUnlock()
	return len(fake.reserveDispatchArgsForCall)
}

func (fake *FakeAgentTicketsFactory) ReserveDispatchCalls(stub func(context.Context, int, tickets.DispatchReservationRequest) (tickets.DispatchReservation, error)) {
	fake.reserveDispatchMutex.Lock()
	defer fake.reserveDispatchMutex.Unlock()
	fake.ReserveDispatchStub = stub
}

func (fake *FakeAgentTicketsFactory) ReserveDispatchArgsForCall(i int) (context.Context, int, tickets.DispatchReservationRequest) {
	fake.reserveDispatchMutex.RLock()
	defer fake.reserveDispatchMutex.RUnlock()
	argsForCall := fake.reserveDispatchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAgentTicketsFactory) ReserveDispatchReturns(result1 tickets.DispatchReservation, result2 error) {
	fake.reserveDispatchMutex.Lock()
	defer fake.reserveDispatchMutex.Unlock()
	fake.ReserveDispatchStub = nil
	fake.reserveDispatchReturns = struct {
		result1 tickets.DispatchReservation
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) ReserveDispatchReturnsOnCall(i int, result1 tickets.DispatchReservation, result2 error) {
	fake.reserveDispatchMutex.Lock()
	defer fake.reserveDispatchMutex.Unlock()
	fake.ReserveDispatchStub = nil
	if fake.reserveDispatchReturnsOnCall == nil {
		fake.reserveDispatchReturnsOnCall = make(map[int]struct {
			result1 tickets.DispatchReservation
			result2 error
		})
	}
	fake.reserveDispatchReturnsOnCall[i] = struct {
		result1 tickets.DispatchReservation
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) SubmitPlan(arg1 int, arg2 []tickets.Task) (int, error) {
	var arg2Copy []tickets.Task
	if arg2 != nil {
		arg2Copy = make([]tickets.Task, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.submitPlanMutex.Lock()
	ret, specificReturn := fake.submitPlanReturnsOnCall[len(fake.submitPlanArgsForCall)]
	fake.submitPlanArgsForCall = append(fake.submitPlanArgsForCall, struct {
		arg1 int
		arg2 []tickets.Task
	}{arg1, arg2Copy})
	stub := fake.SubmitPlanStub
	fakeReturns := fake.submitPlanReturns
	fake.recordInvocation("SubmitPlan", []interface{}{arg1, arg2Copy})
	fake.submitPlanMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) SubmitPlanCallCount() int {
	fake.submitPlanMutex.RLock()
	defer fake.submitPlanMutex.RUnlock()
	return len(fake.submitPlanArgsForCall)
}

func (fake *FakeAgentTicketsFactory) SubmitPlanCalls(stub func(int, []tickets.Task) (int, error)) {
	fake.submitPlanMutex.Lock()
	defer fake.submitPlanMutex.Unlock()
	fake.SubmitPlanStub = stub
}

func (fake *FakeAgentTicketsFactory) SubmitPlanArgsForCall(i int) (int, []tickets.Task) {
	fake.submitPlanMutex.RLock()
	defer fake.submitPlanMutex.RUnlock()
	argsForCall := fake.submitPlanArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentTicketsFactory) SubmitPlanReturns(result1 int, result2 error) {
	fake.submitPlanMutex.Lock()
	defer fake.submitPlanMutex.Unlock()
	fake.SubmitPlanStub = nil
	fake.submitPlanReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) SubmitPlanReturnsOnCall(i int, result1 int, result2 error) {
	fake.submitPlanMutex.Lock()
	defer fake.submitPlanMutex.Unlock()
	fake.SubmitPlanStub = nil
	if fake.submitPlanReturnsOnCall == nil {
		fake.submitPlanReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.submitPlanReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) SubmitSpec(arg1 int, arg2 tickets.Spec) (int, error) {
	fake.submitSpecMutex.Lock()
	ret, specificReturn := fake.submitSpecReturnsOnCall[len(fake.submitSpecArgsForCall)]
	fake.submitSpecArgsForCall = append(fake.submitSpecArgsForCall, struct {
		arg1 int
		arg2 tickets.Spec
	}{arg1, arg2})
	stub := fake.SubmitSpecStub
	fakeReturns := fake.submitSpecReturns
	fake.recordInvocation("SubmitSpec", []interface{}{arg1, arg2})
	fake.submitSpecMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) SubmitSpecCallCount() int {
	fake.submitSpecMutex.RLock()
	defer fake.submitSpecMutex.RUnlock()
	return len(fake.submitSpecArgsForCall)
}

func (fake *FakeAgentTicketsFactory) SubmitSpecCalls(stub func(int, tickets.Spec) (int, error)) {
	fake.submitSpecMutex.Lock()
	defer fake.submitSpecMutex.Unlock()
	fake.SubmitSpecStub = stub
}

func (fake *FakeAgentTicketsFactory) SubmitSpecArgsForCall(i int) (int, tickets.Spec) {
	fake.submitSpecMutex.RLock()
	defer fake.submitSpecMutex.RUnlock()
	argsForCall := fake.submitSpecArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentTicketsFactory) SubmitSpecReturns(result1 int, result2 error) {
	fake.submitSpecMutex.Lock()
	defer fake.submitSpecMutex.Unlock()
	fake.SubmitSpecStub = nil
	fake.submitSpecReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) SubmitSpecReturnsOnCall(i int, result1 int, result2 error) {
	fake.submitSpecMutex.Lock()
	defer fake.submitSpecMutex.Unlock()
	fake.SubmitSpecStub = nil
	if fake.submitSpecReturnsOnCall == nil {
		fake.submitSpecReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.submitSpecReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) Transition(arg1 int, arg2 tickets.State, arg3 tickets.State, arg4 tickets.TransitionMeta) error {
	fake.transitionMutex.Lock()
	ret, specificReturn := fake.transitionReturnsOnCall[len(fake.transitionArgsForCall)]
	fake.transitionArgsForCall = append(fake.transitionArgsForCall, struct {
		arg1 int
		arg2 tickets.State
		arg3 tickets.State
		arg4 tickets.TransitionMeta
	}{arg1, arg2, arg3, arg4})
	stub := fake.TransitionStub
	fakeReturns := fake.transitionReturns
	fake.recordInvocation("Transition", []interface{}{arg1, arg2, arg3, arg4})
	fake.transitionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) TransitionCallCount() int {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	return len(fake.transitionArgsForCall)
}

func (fake *FakeAgentTicketsFactory) TransitionCalls(stub func(int, tickets.State, tickets.State, tickets.TransitionMeta) error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = stub
}

func (fake *FakeAgentTicketsFactory) TransitionArgsForCall(i int) (int, tickets.State, tickets.State, tickets.TransitionMeta) {
	fake.transitionMutex.RLock()
	defer fake.transitionMutex.RUnlock()
	argsForCall := fake.transitionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAgentTicketsFactory) TransitionReturns(result1 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	fake.transitionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) TransitionReturnsOnCall(i int, result1 error) {
	fake.transitionMutex.Lock()
	defer fake.transitionMutex.Unlock()
	fake.TransitionStub = nil
	if fake.transitionReturnsOnCall == nil {
		fake.transitionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.transitionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) Update(arg1 int, arg2 tickets.Update) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 int
		arg2 tickets.Update
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeAgentTicketsFactory) UpdateCalls(stub func(int, tickets.Update) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeAgentTicketsFactory) UpdateArgsForCall(i int) (int, tickets.Update) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentTicketsFactory) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTask(arg1 int, arg2 int, arg3 tickets.TaskStatus, arg4 string) (int, error) {
	fake.updateActiveTaskMutex.Lock()
	ret, specificReturn := fake.updateActiveTaskReturnsOnCall[len(fake.updateActiveTaskArgsForCall)]
	fake.updateActiveTaskArgsForCall = append(fake.updateActiveTaskArgsForCall, struct {
		arg1 int
		arg2 int
		arg3 tickets.TaskStatus
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateActiveTaskStub
	fakeReturns := fake.updateActiveTaskReturns
	fake.recordInvocation("UpdateActiveTask", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateActiveTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTaskCallCount() int {
	fake.updateActiveTaskMutex.RLock()
	defer fake.updateActiveTaskMutex.RUnlock()
	return len(fake.updateActiveTaskArgsForCall)
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTaskCalls(stub func(int, int, tickets.TaskStatus, string) (int, error)) {
	fake.updateActiveTaskMutex.Lock()
	defer fake.updateActiveTaskMutex.Unlock()
	fake.UpdateActiveTaskStub = stub
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTaskArgsForCall(i int) (int, int, tickets.TaskStatus, string) {
	fake.updateActiveTaskMutex.RLock()
	defer fake.updateActiveTaskMutex.RUnlock()
	argsForCall := fake.updateActiveTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTaskReturns(result1 int, result2 error) {
	fake.updateActiveTaskMutex.Lock()
	defer fake.updateActiveTaskMutex.Unlock()
	fake.UpdateActiveTaskStub = nil
	fake.updateActiveTaskReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) UpdateActiveTaskReturnsOnCall(i int, result1 int, result2 error) {
	fake.updateActiveTaskMutex.Lock()
	defer fake.updateActiveTaskMutex.Unlock()
	fake.UpdateActiveTaskStub = nil
	if fake.updateActiveTaskReturnsOnCall == nil {
		fake.updateActiveTaskReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.updateActiveTaskReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatus(arg1 int, arg2 int, arg3 int, arg4 tickets.TaskStatus) error {
	fake.updateTaskStatusMutex.Lock()
	ret, specificReturn := fake.updateTaskStatusReturnsOnCall[len(fake.updateTaskStatusArgsForCall)]
	fake.updateTaskStatusArgsForCall = append(fake.updateTaskStatusArgsForCall, struct {
		arg1 int
		arg2 int
		arg3 int
		arg4 tickets.TaskStatus
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateTaskStatusStub
	fakeReturns := fake.updateTaskStatusReturns
	fake.recordInvocation("UpdateTaskStatus", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateTaskStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatusCallCount() int {
	fake.updateTaskStatusMutex.RLock()
	defer fake.updateTaskStatusMutex.RUnlock()
	return len(fake.updateTaskStatusArgsForCall)
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatusCalls(stub func(int, int, int, tickets.TaskStatus) error) {
	fake.updateTaskStatusMutex.Lock()
	defer fake.updateTaskStatusMutex.Unlock()
	fake.UpdateTaskStatusStub = stub
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatusArgsForCall(i int) (int, int, int, tickets.TaskStatus) {
	fake.updateTaskStatusMutex.RLock()
	defer fake.updateTaskStatusMutex.RUnlock()
	argsForCall := fake.updateTaskStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatusReturns(result1 error) {
	fake.updateTaskStatusMutex.Lock()
	defer fake.updateTaskStatusMutex.Unlock()
	fake.UpdateTaskStatusStub = nil
	fake.updateTaskStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) UpdateTaskStatusReturnsOnCall(i int, result1 error) {
	fake.updateTaskStatusMutex.Lock()
	defer fake.updateTaskStatusMutex.Unlock()
	fake.UpdateTaskStatusStub = nil
	if fake.updateTaskStatusReturnsOnCall == nil {
		fake.updateTaskStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateTaskStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentTicketsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentTicketsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentTicketsFactory = new(FakeAgentTicketsFactory)
