// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/workflow"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentWorkflowsFactory struct {
	GetStub        func(string, int) (*workflow.Definition, bool, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 string
		arg2 int
	}
	getReturns struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	getReturnsOnCall map[int]struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	ImportStub        func(string, []byte, string) (*workflow.Definition, error)
	importMutex       sync.RWMutex
	importArgsForCall []struct {
		arg1 string
		arg2 []byte
		arg3 string
	}
	importReturns struct {
		result1 *workflow.Definition
		result2 error
	}
	importReturnsOnCall map[int]struct {
		result1 *workflow.Definition
		result2 error
	}
	ImportManifestStub        func(string, workflow.Manifest, string) (*workflow.Definition, error)
	importManifestMutex       sync.RWMutex
	importManifestArgsForCall []struct {
		arg1 string
		arg2 workflow.Manifest
		arg3 string
	}
	importManifestReturns struct {
		result1 *workflow.Definition
		result2 error
	}
	importManifestReturnsOnCall map[int]struct {
		result1 *workflow.Definition
		result2 error
	}
	LatestStub        func(string) (*workflow.Definition, bool, error)
	latestMutex       sync.RWMutex
	latestArgsForCall []struct {
		arg1 string
	}
	latestReturns struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	latestReturnsOnCall map[int]struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	ListStub        func() ([]workflow.Definition, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
	}
	listReturns struct {
		result1 []workflow.Definition
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 []workflow.Definition
		result2 error
	}
	LiveStub        func(string) (*workflow.Definition, bool, error)
	liveMutex       sync.RWMutex
	liveArgsForCall []struct {
		arg1 string
	}
	liveReturns struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	liveReturnsOnCall map[int]struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}
	LiveVersionsStub        func() (map[string]int, error)
	liveVersionsMutex       sync.RWMutex
	liveVersionsArgsForCall []struct {
	}
	liveVersionsReturns struct {
		result1 map[string]int
		result2 error
	}
	liveVersionsReturnsOnCall map[int]struct {
		result1 map[string]int
		result2 error
	}
	PromoteStub        func(string, int, string) error
	promoteMutex       sync.RWMutex
	promoteArgsForCall []struct {
		arg1 string
		arg2 int
		arg3 string
	}
	promoteReturns struct {
		result1 error
	}
	promoteReturnsOnCall map[int]struct {
		result1 error
	}
	VersionsStub        func(string) ([]workflow.Definition, error)
	versionsMutex       sync.RWMutex
	versionsArgsForCall []struct {
		arg1 string
	}
	versionsReturns struct {
		result1 []workflow.Definition
		result2 error
	}
	versionsReturnsOnCall map[int]struct {
		result1 []workflow.Definition
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentWorkflowsFactory) Get(arg1 string, arg2 int) (*workflow.Definition, bool, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 string
		arg2 int
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentWorkflowsFactory) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) GetCalls(stub func(string, int) (*workflow.Definition, bool, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeAgentWorkflowsFactory) GetArgsForCall(i int) (string, int) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentWorkflowsFactory) GetReturns(result1 *workflow.Definition, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) GetReturnsOnCall(i int, result1 *workflow.Definition, result2 bool, result3 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *workflow.Definition
			result2 bool
			result3 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) Import(arg1 string, arg2 []byte, arg3 string) (*workflow.Definition, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.importMutex.Lock()
	ret, specificReturn := fake.importReturnsOnCall[len(fake.importArgsForCall)]
	fake.importArgsForCall = append(fake.importArgsForCall, struct {
		arg1 string
		arg2 []byte
		arg3 string
	}{arg1, arg2Copy, arg3})
	stub := fake.ImportStub
	fakeReturns := fake.importReturns
	fake.recordInvocation("Import", []interface{}{arg1, arg2Copy, arg3})
	fake.importMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentWorkflowsFactory) ImportCallCount() int {
	fake.importMutex.RLock()
	defer fake.importMutex.RUnlock()
	return len(fake.importArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) ImportCalls(stub func(string, []byte, string) (*workflow.Definition, error)) {
	fake.importMutex.Lock()
	defer fake.importMutex.Unlock()
	fake.ImportStub = stub
}

func (fake *FakeAgentWorkflowsFactory) ImportArgsForCall(i int) (string, []byte, string) {
	fake.importMutex.RLock()
	defer fake.importMutex.RUnlock()
	argsForCall := fake.importArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAgentWorkflowsFactory) ImportReturns(result1 *workflow.Definition, result2 error) {
	fake.importMutex.Lock()
	defer fake.importMutex.Unlock()
	fake.ImportStub = nil
	fake.importReturns = struct {
		result1 *workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) ImportReturnsOnCall(i int, result1 *workflow.Definition, result2 error) {
	fake.importMutex.Lock()
	defer fake.importMutex.Unlock()
	fake.ImportStub = nil
	if fake.importReturnsOnCall == nil {
		fake.importReturnsOnCall = make(map[int]struct {
			result1 *workflow.Definition
			result2 error
		})
	}
	fake.importReturnsOnCall[i] = struct {
		result1 *workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) ImportManifest(arg1 string, arg2 workflow.Manifest, arg3 string) (*workflow.Definition, error) {
	fake.importManifestMutex.Lock()
	ret, specificReturn := fake.importManifestReturnsOnCall[len(fake.importManifestArgsForCall)]
	fake.importManifestArgsForCall = append(fake.importManifestArgsForCall, struct {
		arg1 string
		arg2 workflow.Manifest
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ImportManifestStub
	fakeReturns := fake.importManifestReturns
	fake.recordInvocation("ImportManifest", []interface{}{arg1, arg2, arg3})
	fake.importManifestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentWorkflowsFactory) ImportManifestCallCount() int {
	fake.importManifestMutex.RLock()
	defer fake.importManifestMutex.RUnlock()
	return len(fake.importManifestArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) ImportManifestCalls(stub func(string, workflow.Manifest, string) (*workflow.Definition, error)) {
	fake.importManifestMutex.Lock()
	defer fake.importManifestMutex.Unlock()
	fake.ImportManifestStub = stub
}

func (fake *FakeAgentWorkflowsFactory) ImportManifestArgsForCall(i int) (string, workflow.Manifest, string) {
	fake.importManifestMutex.RLock()
	defer fake.importManifestMutex.RUnlock()
	argsForCall := fake.importManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAgentWorkflowsFactory) ImportManifestReturns(result1 *workflow.Definition, result2 error) {
	fake.importManifestMutex.Lock()
	defer fake.importManifestMutex.Unlock()
	fake.ImportManifestStub = nil
	fake.importManifestReturns = struct {
		result1 *workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) ImportManifestReturnsOnCall(i int, result1 *workflow.Definition, result2 error) {
	fake.importManifestMutex.Lock()
	defer fake.importManifestMutex.Unlock()
	fake.ImportManifestStub = nil
	if fake.importManifestReturnsOnCall == nil {
		fake.importManifestReturnsOnCall = make(map[int]struct {
			result1 *workflow.Definition
			result2 error
		})
	}
	fake.importManifestReturnsOnCall[i] = struct {
		result1 *workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) Latest(arg1 string) (*workflow.Definition, bool, error) {
	fake.latestMutex.Lock()
	ret, specificReturn := fake.latestReturnsOnCall[len(fake.latestArgsForCall)]
	fake.latestArgsForCall = append(fake.latestArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LatestStub
	fakeReturns := fake.latestReturns
	fake.recordInvocation("Latest", []interface{}{arg1})
	fake.latestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentWorkflowsFactory) LatestCallCount() int {
	fake.latestMutex.RLock()
	defer fake.latestMutex.RUnlock()
	return len(fake.latestArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) LatestCalls(stub func(string) (*workflow.Definition, bool, error)) {
	fake.latestMutex.Lock()
	defer fake.latestMutex.Unlock()
	fake.LatestStub = stub
}

func (fake *FakeAgentWorkflowsFactory) LatestArgsForCall(i int) string {
	fake.latestMutex.RLock()
	defer fake.latestMutex.RUnlock()
	argsForCall := fake.latestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentWorkflowsFactory) LatestReturns(result1 *workflow.Definition, result2 bool, result3 error) {
	fake.latestMutex.Lock()
	defer fake.latestMutex.Unlock()
	fake.LatestStub = nil
	fake.latestReturns = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) LatestReturnsOnCall(i int, result1 *workflow.Definition, result2 bool, result3 error) {
	fake.latestMutex.Lock()
	defer fake.latestMutex.Unlock()
	fake.LatestStub = nil
	if fake.latestReturnsOnCall == nil {
		fake.latestReturnsOnCall = make(map[int]struct {
			result1 *workflow.Definition
			result2 bool
			result3 error
		})
	}
	fake.latestReturnsOnCall[i] = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) List() ([]workflow.Definition, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
	}{})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentWorkflowsFactory) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) ListCalls(stub func() ([]workflow.Definition, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeAgentWorkflowsFactory) ListReturns(result1 []workflow.Definition, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) ListReturnsOnCall(i int, result1 []workflow.Definition, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []workflow.Definition
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) Live(arg1 string) (*workflow.Definition, bool, error) {
	fake.liveMutex.Lock()
	ret, specificReturn := fake.liveReturnsOnCall[len(fake.liveArgsForCall)]
	fake.liveArgsForCall = append(fake.liveArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LiveStub
	fakeReturns := fake.liveReturns
	fake.recordInvocation("Live", []interface{}{arg1})
	fake.liveMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentWorkflowsFactory) LiveCallCount() int {
	fake.liveMutex.RLock()
	defer fake.liveMutex.RUnlock()
	return len(fake.liveArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) LiveCalls(stub func(string) (*workflow.Definition, bool, error)) {
	fake.liveMutex.Lock()
	defer fake.liveMutex.Unlock()
	fake.LiveStub = stub
}

func (fake *FakeAgentWorkflowsFactory) LiveArgsForCall(i int) string {
	fake.liveMutex.RLock()
	defer fake.liveMutex.RUnlock()
	argsForCall := fake.liveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentWorkflowsFactory) LiveReturns(result1 *workflow.Definition, result2 bool, result3 error) {
	fake.liveMutex.Lock()
	defer fake.liveMutex.Unlock()
	fake.LiveStub = nil
	fake.liveReturns = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) LiveReturnsOnCall(i int, result1 *workflow.Definition, result2 bool, result3 error) {
	fake.liveMutex.Lock()
	defer fake.liveMutex.Unlock()
	fake.LiveStub = nil
	if fake.liveReturnsOnCall == nil {
		fake.liveReturnsOnCall = make(map[int]struct {
			result1 *workflow.Definition
			result2 bool
			result3 error
		})
	}
	fake.liveReturnsOnCall[i] = struct {
		result1 *workflow.Definition
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentWorkflowsFactory) LiveVersions() (map[string]int, error) {
	fake.liveVersionsMutex.Lock()
	ret, specificReturn := fake.liveVersionsReturnsOnCall[len(fake.liveVersionsArgsForCall)]
	fake.liveVersionsArgsForCall = append(fake.liveVersionsArgsForCall, struct {
	}{})
	stub := fake.LiveVersionsStub
	fakeReturns := fake.liveVersionsReturns
	fake.recordInvocation("LiveVersions", []interface{}{})
	fake.liveVersionsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentWorkflowsFactory) LiveVersionsCallCount() int {
	fake.liveVersionsMutex.RLock()
	defer fake.liveVersionsMutex.RUnlock()
	return len(fake.liveVersionsArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) LiveVersionsCalls(stub func() (map[string]int, error)) {
	fake.liveVersionsMutex.Lock()
	defer fake.liveVersionsMutex.Unlock()
	fake.LiveVersionsStub = stub
}

func (fake *FakeAgentWorkflowsFactory) LiveVersionsReturns(result1 map[string]int, result2 error) {
	fake.liveVersionsMutex.Lock()
	defer fake.liveVersionsMutex.Unlock()
	fake.LiveVersionsStub = nil
	fake.liveVersionsReturns = struct {
		result1 map[string]int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) LiveVersionsReturnsOnCall(i int, result1 map[string]int, result2 error) {
	fake.liveVersionsMutex.Lock()
	defer fake.liveVersionsMutex.Unlock()
	fake.LiveVersionsStub = nil
	if fake.liveVersionsReturnsOnCall == nil {
		fake.liveVersionsReturnsOnCall = make(map[int]struct {
			result1 map[string]int
			result2 error
		})
	}
	fake.liveVersionsReturnsOnCall[i] = struct {
		result1 map[string]int
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) Promote(arg1 string, arg2 int, arg3 string) error {
	fake.promoteMutex.Lock()
	ret, specificReturn := fake.promoteReturnsOnCall[len(fake.promoteArgsForCall)]
	fake.promoteArgsForCall = append(fake.promoteArgsForCall, struct {
		arg1 string
		arg2 int
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PromoteStub
	fakeReturns := fake.promoteReturns
	fake.recordInvocation("Promote", []interface{}{arg1, arg2, arg3})
	fake.promoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentWorkflowsFactory) PromoteCallCount() int {
	fake.promoteMutex.RLock()
	defer fake.promoteMutex.RUnlock()
	return len(fake.promoteArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) PromoteCalls(stub func(string, int, string) error) {
	fake.promoteMutex.Lock()
	defer fake.promoteMutex.Unlock()
	fake.PromoteStub = stub
}

func (fake *FakeAgentWorkflowsFactory) PromoteArgsForCall(i int) (string, int, string) {
	fake.promoteMutex.RLock()
	defer fake.promoteMutex.RUnlock()
	argsForCall := fake.promoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAgentWorkflowsFactory) PromoteReturns(result1 error) {
	fake.promoteMutex.Lock()
	defer fake.promoteMutex.Unlock()
	fake.PromoteStub = nil
	fake.promoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentWorkflowsFactory) PromoteReturnsOnCall(i int, result1 error) {
	fake.promoteMutex.Lock()
	defer fake.promoteMutex.Unlock()
	fake.PromoteStub = nil
	if fake.promoteReturnsOnCall == nil {
		fake.promoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.promoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentWorkflowsFactory) Versions(arg1 string) ([]workflow.Definition, error) {
	fake.versionsMutex.Lock()
	ret, specificReturn := fake.versionsReturnsOnCall[len(fake.versionsArgsForCall)]
	fake.versionsArgsForCall = append(fake.versionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.VersionsStub
	fakeReturns := fake.versionsReturns
	fake.recordInvocation("Versions", []interface{}{arg1})
	fake.versionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentWorkflowsFactory) VersionsCallCount() int {
	fake.versionsMutex.RLock()
	defer fake.versionsMutex.RUnlock()
	return len(fake.versionsArgsForCall)
}

func (fake *FakeAgentWorkflowsFactory) VersionsCalls(stub func(string) ([]workflow.Definition, error)) {
	fake.versionsMutex.Lock()
	defer fake.versionsMutex.Unlock()
	fake.VersionsStub = stub
}

func (fake *FakeAgentWorkflowsFactory) VersionsArgsForCall(i int) string {
	fake.versionsMutex.RLock()
	defer fake.versionsMutex.RUnlock()
	argsForCall := fake.versionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentWorkflowsFactory) VersionsReturns(result1 []workflow.Definition, result2 error) {
	fake.versionsMutex.Lock()
	defer fake.versionsMutex.Unlock()
	fake.VersionsStub = nil
	fake.versionsReturns = struct {
		result1 []workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) VersionsReturnsOnCall(i int, result1 []workflow.Definition, result2 error) {
	fake.versionsMutex.Lock()
	defer fake.versionsMutex.Unlock()
	fake.VersionsStub = nil
	if fake.versionsReturnsOnCall == nil {
		fake.versionsReturnsOnCall = make(map[int]struct {
			result1 []workflow.Definition
			result2 error
		})
	}
	fake.versionsReturnsOnCall[i] = struct {
		result1 []workflow.Definition
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentWorkflowsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentWorkflowsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentWorkflowsFactory = new(FakeAgentWorkflowsFactory)
