// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/api/reviews"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentReviewsFactory struct {
	GetByBuildStub        func(int) ([]reviews.StoredReview, error)
	getByBuildMutex       sync.RWMutex
	getByBuildArgsForCall []struct {
		arg1 int
	}
	getByBuildReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	getByBuildReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	ListByTeamStub        func(string, reviews.ListFilter) ([]reviews.StoredReview, error)
	listByTeamMutex       sync.RWMutex
	listByTeamArgsForCall []struct {
		arg1 string
		arg2 reviews.ListFilter
	}
	listByTeamReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	listByTeamReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	ListByTicketStub        func(int) ([]reviews.StoredReview, error)
	listByTicketMutex       sync.RWMutex
	listByTicketArgsForCall []struct {
		arg1 int
	}
	listByTicketReturns struct {
		result1 []reviews.StoredReview
		result2 error
	}
	listByTicketReturnsOnCall map[int]struct {
		result1 []reviews.StoredReview
		result2 error
	}
	UpsertStub        func(*reviews.StoredReview) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 *reviews.StoredReview
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentReviewsFactory) GetByBuild(arg1 int) ([]reviews.StoredReview, error) {
	fake.getByBuildMutex.Lock()
	ret, specificReturn := fake.getByBuildReturnsOnCall[len(fake.getByBuildArgsForCall)]
	fake.getByBuildArgsForCall = append(fake.getByBuildArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetByBuildStub
	fakeReturns := fake.getByBuildReturns
	fake.recordInvocation("GetByBuild", []interface{}{arg1})
	fake.getByBuildMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) GetByBuildCallCount() int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	return len(fake.getByBuildArgsForCall)
}

func (fake *FakeAgentReviewsFactory) GetByBuildCalls(stub func(int) ([]reviews.StoredReview, error)) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = stub
}

func (fake *FakeAgentReviewsFactory) GetByBuildArgsForCall(i int) int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	argsForCall := fake.getByBuildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) GetByBuildReturns(result1 []reviews.StoredReview, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	fake.getByBuildReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) GetByBuildReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	if fake.getByBuildReturnsOnCall == nil {
		fake.getByBuildReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.getByBuildReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTeam(arg1 string, arg2 reviews.ListFilter) ([]reviews.StoredReview, error) {
	fake.listByTeamMutex.Lock()
	ret, specificReturn := fake.listByTeamReturnsOnCall[len(fake.listByTeamArgsForCall)]
	fake.listByTeamArgsForCall = append(fake.listByTeamArgsForCall, struct {
		arg1 string
		arg2 reviews.ListFilter
	}{arg1, arg2})
	stub := fake.ListByTeamStub
	fakeReturns := fake.listByTeamReturns
	fake.recordInvocation("ListByTeam", []interface{}{arg1, arg2})
	fake.listByTeamMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListByTeamCallCount() int {
	fake.listByTeamMutex.RLock()
	defer fake.listByTeamMutex.RUnlock()
	return len(fake.listByTeamArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListByTeamCalls(stub func(string, reviews.ListFilter) ([]reviews.StoredReview, error)) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = stub
}

func (fake *FakeAgentReviewsFactory) ListByTeamArgsForCall(i int) (string, reviews.ListFilter) {
	fake.listByTeamMutex.RLock()
	defer fake.listByTeamMutex.RUnlock()
	argsForCall := fake.listByTeamArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentReviewsFactory) ListByTeamReturns(result1 []reviews.StoredReview, result2 error) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = nil
	fake.listByTeamReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTeamReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.listByTeamMutex.Lock()
	defer fake.listByTeamMutex.Unlock()
	fake.ListByTeamStub = nil
	if fake.listByTeamReturnsOnCall == nil {
		fake.listByTeamReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.listByTeamReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTicket(arg1 int) ([]reviews.StoredReview, error) {
	fake.listByTicketMutex.Lock()
	ret, specificReturn := fake.listByTicketReturnsOnCall[len(fake.listByTicketArgsForCall)]
	fake.listByTicketArgsForCall = append(fake.listByTicketArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.ListByTicketStub
	fakeReturns := fake.listByTicketReturns
	fake.recordInvocation("ListByTicket", []interface{}{arg1})
	fake.listByTicketMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentReviewsFactory) ListByTicketCallCount() int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	return len(fake.listByTicketArgsForCall)
}

func (fake *FakeAgentReviewsFactory) ListByTicketCalls(stub func(int) ([]reviews.StoredReview, error)) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = stub
}

func (fake *FakeAgentReviewsFactory) ListByTicketArgsForCall(i int) int {
	fake.listByTicketMutex.RLock()
	defer fake.listByTicketMutex.RUnlock()
	argsForCall := fake.listByTicketArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) ListByTicketReturns(result1 []reviews.StoredReview, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	fake.listByTicketReturns = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) ListByTicketReturnsOnCall(i int, result1 []reviews.StoredReview, result2 error) {
	fake.listByTicketMutex.Lock()
	defer fake.listByTicketMutex.Unlock()
	fake.ListByTicketStub = nil
	if fake.listByTicketReturnsOnCall == nil {
		fake.listByTicketReturnsOnCall = make(map[int]struct {
			result1 []reviews.StoredReview
			result2 error
		})
	}
	fake.listByTicketReturnsOnCall[i] = struct {
		result1 []reviews.StoredReview
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentReviewsFactory) Upsert(arg1 *reviews.StoredReview) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 *reviews.StoredReview
	}{arg1})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentReviewsFactory) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeAgentReviewsFactory) UpsertCalls(stub func(*reviews.StoredReview) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeAgentReviewsFactory) UpsertArgsForCall(i int) *reviews.StoredReview {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentReviewsFactory) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentReviewsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentReviewsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentReviewsFactory = new(FakeAgentReviewsFactory)
