// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentRunTranscriptFactory struct {
	ListByWorkflowRunStub        func(string, snapshot.WorkflowRunID) ([]db.AgentRunTranscript, error)
	listByWorkflowRunMutex       sync.RWMutex
	listByWorkflowRunArgsForCall []struct {
		arg1 string
		arg2 snapshot.WorkflowRunID
	}
	listByWorkflowRunReturns struct {
		result1 []db.AgentRunTranscript
		result2 error
	}
	listByWorkflowRunReturnsOnCall map[int]struct {
		result1 []db.AgentRunTranscript
		result2 error
	}
	UpsertStub        func(db.AgentRunTranscript) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 db.AgentRunTranscript
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRun(arg1 string, arg2 snapshot.WorkflowRunID) ([]db.AgentRunTranscript, error) {
	fake.listByWorkflowRunMutex.Lock()
	ret, specificReturn := fake.listByWorkflowRunReturnsOnCall[len(fake.listByWorkflowRunArgsForCall)]
	fake.listByWorkflowRunArgsForCall = append(fake.listByWorkflowRunArgsForCall, struct {
		arg1 string
		arg2 snapshot.WorkflowRunID
	}{arg1, arg2})
	stub := fake.ListByWorkflowRunStub
	fakeReturns := fake.listByWorkflowRunReturns
	fake.recordInvocation("ListByWorkflowRun", []interface{}{arg1, arg2})
	fake.listByWorkflowRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRunCallCount() int {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	return len(fake.listByWorkflowRunArgsForCall)
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRunCalls(stub func(string, snapshot.WorkflowRunID) ([]db.AgentRunTranscript, error)) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = stub
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRunArgsForCall(i int) (string, snapshot.WorkflowRunID) {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	argsForCall := fake.listByWorkflowRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRunReturns(result1 []db.AgentRunTranscript, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	fake.listByWorkflowRunReturns = struct {
		result1 []db.AgentRunTranscript
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunTranscriptFactory) ListByWorkflowRunReturnsOnCall(i int, result1 []db.AgentRunTranscript, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	if fake.listByWorkflowRunReturnsOnCall == nil {
		fake.listByWorkflowRunReturnsOnCall = make(map[int]struct {
			result1 []db.AgentRunTranscript
			result2 error
		})
	}
	fake.listByWorkflowRunReturnsOnCall[i] = struct {
		result1 []db.AgentRunTranscript
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunTranscriptFactory) Upsert(arg1 db.AgentRunTranscript) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 db.AgentRunTranscript
	}{arg1})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentRunTranscriptFactory) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeAgentRunTranscriptFactory) UpsertCalls(stub func(db.AgentRunTranscript) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeAgentRunTranscriptFactory) UpsertArgsForCall(i int) db.AgentRunTranscript {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunTranscriptFactory) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentRunTranscriptFactory) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentRunTranscriptFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentRunTranscriptFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentRunTranscriptFactory = new(FakeAgentRunTranscriptFactory)
