// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/db"
)

type FakeWorkerLifecycle struct {
	DeleteUnresponsiveEphemeralWorkersStub        func() ([]string, error)
	deleteUnresponsiveEphemeralWorkersMutex       sync.RWMutex
	deleteUnresponsiveEphemeralWorkersArgsForCall []struct {
	}
	deleteUnresponsiveEphemeralWorkersReturns struct {
		result1 []string
		result2 error
	}
	deleteUnresponsiveEphemeralWorkersReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetWorkerStateByNameStub        func() (map[string]db.WorkerState, error)
	getWorkerStateByNameMutex       sync.RWMutex
	getWorkerStateByNameArgsForCall []struct {
	}
	getWorkerStateByNameReturns struct {
		result1 map[string]db.WorkerState
		result2 error
	}
	getWorkerStateByNameReturnsOnCall map[int]struct {
		result1 map[string]db.WorkerState
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWorkerLifecycle) DeleteUnresponsiveEphemeralWorkers() ([]string, error) {
	fake.deleteUnresponsiveEphemeralWorkersMutex.Lock()
	ret, specificReturn := fake.deleteUnresponsiveEphemeralWorkersReturnsOnCall[len(fake.deleteUnresponsiveEphemeralWorkersArgsForCall)]
	fake.deleteUnresponsiveEphemeralWorkersArgsForCall = append(fake.deleteUnresponsiveEphemeralWorkersArgsForCall, struct {
	}{})
	stub := fake.DeleteUnresponsiveEphemeralWorkersStub
	fakeReturns := fake.deleteUnresponsiveEphemeralWorkersReturns
	fake.recordInvocation("DeleteUnresponsiveEphemeralWorkers", []interface{}{})
	fake.deleteUnresponsiveEphemeralWorkersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWorkerLifecycle) DeleteUnresponsiveEphemeralWorkersCallCount() int {
	fake.deleteUnresponsiveEphemeralWorkersMutex.RLock()
	defer fake.deleteUnresponsiveEphemeralWorkersMutex.RUnlock()
	return len(fake.deleteUnresponsiveEphemeralWorkersArgsForCall)
}

func (fake *FakeWorkerLifecycle) DeleteUnresponsiveEphemeralWorkersCalls(stub func() ([]string, error)) {
	fake.deleteUnresponsiveEphemeralWorkersMutex.Lock()
	defer fake.deleteUnresponsiveEphemeralWorkersMutex.Unlock()
	fake.DeleteUnresponsiveEphemeralWorkersStub = stub
}

func (fake *FakeWorkerLifecycle) DeleteUnresponsiveEphemeralWorkersReturns(result1 []string, result2 error) {
	fake.deleteUnresponsiveEphemeralWorkersMutex.Lock()
	defer fake.deleteUnresponsiveEphemeralWorkersMutex.Unlock()
	fake.DeleteUnresponsiveEphemeralWorkersStub = nil
	fake.deleteUnresponsiveEphemeralWorkersReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerLifecycle) DeleteUnresponsiveEphemeralWorkersReturnsOnCall(i int, result1 []string, result2 error) {
	fake.deleteUnresponsiveEphemeralWorkersMutex.Lock()
	defer fake.deleteUnresponsiveEphemeralWorkersMutex.Unlock()
	fake.DeleteUnresponsiveEphemeralWorkersStub = nil
	if fake.deleteUnresponsiveEphemeralWorkersReturnsOnCall == nil {
		fake.deleteUnresponsiveEphemeralWorkersReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.deleteUnresponsiveEphemeralWorkersReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerLifecycle) GetWorkerStateByName() (map[string]db.WorkerState, error) {
	fake.getWorkerStateByNameMutex.Lock()
	ret, specificReturn := fake.getWorkerStateByNameReturnsOnCall[len(fake.getWorkerStateByNameArgsForCall)]
	fake.getWorkerStateByNameArgsForCall = append(fake.getWorkerStateByNameArgsForCall, struct {
	}{})
	stub := fake.GetWorkerStateByNameStub
	fakeReturns := fake.getWorkerStateByNameReturns
	fake.recordInvocation("GetWorkerStateByName", []interface{}{})
	fake.getWorkerStateByNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWorkerLifecycle) GetWorkerStateByNameCallCount() int {
	fake.getWorkerStateByNameMutex.RLock()
	defer fake.getWorkerStateByNameMutex.RUnlock()
	return len(fake.getWorkerStateByNameArgsForCall)
}

func (fake *FakeWorkerLifecycle) GetWorkerStateByNameCalls(stub func() (map[string]db.WorkerState, error)) {
	fake.getWorkerStateByNameMutex.Lock()
	defer fake.getWorkerStateByNameMutex.Unlock()
	fake.GetWorkerStateByNameStub = stub
}

func (fake *FakeWorkerLifecycle) GetWorkerStateByNameReturns(result1 map[string]db.WorkerState, result2 error) {
	fake.getWorkerStateByNameMutex.Lock()
	defer fake.getWorkerStateByNameMutex.Unlock()
	fake.GetWorkerStateByNameStub = nil
	fake.getWorkerStateByNameReturns = struct {
		result1 map[string]db.WorkerState
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerLifecycle) GetWorkerStateByNameReturnsOnCall(i int, result1 map[string]db.WorkerState, result2 error) {
	fake.getWorkerStateByNameMutex.Lock()
	defer fake.getWorkerStateByNameMutex.Unlock()
	fake.GetWorkerStateByNameStub = nil
	if fake.getWorkerStateByNameReturnsOnCall == nil {
		fake.getWorkerStateByNameReturnsOnCall = make(map[int]struct {
			result1 map[string]db.WorkerState
			result2 error
		})
	}
	fake.getWorkerStateByNameReturnsOnCall[i] = struct {
		result1 map[string]db.WorkerState
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerLifecycle) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWorkerLifecycle) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.WorkerLifecycle = new(FakeWorkerLifecycle)
