// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/schema"
	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentRunMetricsFactory struct {
	GetByBuildStub        func(int) ([]schema.RunMetrics, error)
	getByBuildMutex       sync.RWMutex
	getByBuildArgsForCall []struct {
		arg1 int
	}
	getByBuildReturns struct {
		result1 []schema.RunMetrics
		result2 error
	}
	getByBuildReturnsOnCall map[int]struct {
		result1 []schema.RunMetrics
		result2 error
	}
	InsertIfAbsentStub        func(*schema.RunMetrics) (bool, error)
	insertIfAbsentMutex       sync.RWMutex
	insertIfAbsentArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	insertIfAbsentReturns struct {
		result1 bool
		result2 error
	}
	insertIfAbsentReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ListByWorkflowRunStub        func(string, snapshot.WorkflowRunID) ([]schema.RunMetrics, error)
	listByWorkflowRunMutex       sync.RWMutex
	listByWorkflowRunArgsForCall []struct {
		arg1 string
		arg2 snapshot.WorkflowRunID
	}
	listByWorkflowRunReturns struct {
		result1 []schema.RunMetrics
		result2 error
	}
	listByWorkflowRunReturnsOnCall map[int]struct {
		result1 []schema.RunMetrics
		result2 error
	}
	ListRecentStub        func(int) ([]schema.RunMetrics, error)
	listRecentMutex       sync.RWMutex
	listRecentArgsForCall []struct {
		arg1 int
	}
	listRecentReturns struct {
		result1 []schema.RunMetrics
		result2 error
	}
	listRecentReturnsOnCall map[int]struct {
		result1 []schema.RunMetrics
		result2 error
	}
	UpsertStub        func(*schema.RunMetrics) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	UpsertReturningInsertedStub        func(*schema.RunMetrics) (bool, *schema.RunMetrics, error)
	upsertReturningInsertedMutex       sync.RWMutex
	upsertReturningInsertedArgsForCall []struct {
		arg1 *schema.RunMetrics
	}
	upsertReturningInsertedReturns struct {
		result1 bool
		result2 *schema.RunMetrics
		result3 error
	}
	upsertReturningInsertedReturnsOnCall map[int]struct {
		result1 bool
		result2 *schema.RunMetrics
		result3 error
	}
	WorkflowStatsStub        func(string) ([]schema.WorkflowVersionStats, error)
	workflowStatsMutex       sync.RWMutex
	workflowStatsArgsForCall []struct {
		arg1 string
	}
	workflowStatsReturns struct {
		result1 []schema.WorkflowVersionStats
		result2 error
	}
	workflowStatsReturnsOnCall map[int]struct {
		result1 []schema.WorkflowVersionStats
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentRunMetricsFactory) GetByBuild(arg1 int) ([]schema.RunMetrics, error) {
	fake.getByBuildMutex.Lock()
	ret, specificReturn := fake.getByBuildReturnsOnCall[len(fake.getByBuildArgsForCall)]
	fake.getByBuildArgsForCall = append(fake.getByBuildArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetByBuildStub
	fakeReturns := fake.getByBuildReturns
	fake.recordInvocation("GetByBuild", []interface{}{arg1})
	fake.getByBuildMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunMetricsFactory) GetByBuildCallCount() int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	return len(fake.getByBuildArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) GetByBuildCalls(stub func(int) ([]schema.RunMetrics, error)) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = stub
}

func (fake *FakeAgentRunMetricsFactory) GetByBuildArgsForCall(i int) int {
	fake.getByBuildMutex.RLock()
	defer fake.getByBuildMutex.RUnlock()
	argsForCall := fake.getByBuildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) GetByBuildReturns(result1 []schema.RunMetrics, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	fake.getByBuildReturns = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) GetByBuildReturnsOnCall(i int, result1 []schema.RunMetrics, result2 error) {
	fake.getByBuildMutex.Lock()
	defer fake.getByBuildMutex.Unlock()
	fake.GetByBuildStub = nil
	if fake.getByBuildReturnsOnCall == nil {
		fake.getByBuildReturnsOnCall = make(map[int]struct {
			result1 []schema.RunMetrics
			result2 error
		})
	}
	fake.getByBuildReturnsOnCall[i] = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsent(arg1 *schema.RunMetrics) (bool, error) {
	fake.insertIfAbsentMutex.Lock()
	ret, specificReturn := fake.insertIfAbsentReturnsOnCall[len(fake.insertIfAbsentArgsForCall)]
	fake.insertIfAbsentArgsForCall = append(fake.insertIfAbsentArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.InsertIfAbsentStub
	fakeReturns := fake.insertIfAbsentReturns
	fake.recordInvocation("InsertIfAbsent", []interface{}{arg1})
	fake.insertIfAbsentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsentCallCount() int {
	fake.insertIfAbsentMutex.RLock()
	defer fake.insertIfAbsentMutex.RUnlock()
	return len(fake.insertIfAbsentArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsentCalls(stub func(*schema.RunMetrics) (bool, error)) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = stub
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsentArgsForCall(i int) *schema.RunMetrics {
	fake.insertIfAbsentMutex.RLock()
	defer fake.insertIfAbsentMutex.RUnlock()
	argsForCall := fake.insertIfAbsentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsentReturns(result1 bool, result2 error) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = nil
	fake.insertIfAbsentReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) InsertIfAbsentReturnsOnCall(i int, result1 bool, result2 error) {
	fake.insertIfAbsentMutex.Lock()
	defer fake.insertIfAbsentMutex.Unlock()
	fake.InsertIfAbsentStub = nil
	if fake.insertIfAbsentReturnsOnCall == nil {
		fake.insertIfAbsentReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.insertIfAbsentReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRun(arg1 string, arg2 snapshot.WorkflowRunID) ([]schema.RunMetrics, error) {
	fake.listByWorkflowRunMutex.Lock()
	ret, specificReturn := fake.listByWorkflowRunReturnsOnCall[len(fake.listByWorkflowRunArgsForCall)]
	fake.listByWorkflowRunArgsForCall = append(fake.listByWorkflowRunArgsForCall, struct {
		arg1 string
		arg2 snapshot.WorkflowRunID
	}{arg1, arg2})
	stub := fake.ListByWorkflowRunStub
	fakeReturns := fake.listByWorkflowRunReturns
	fake.recordInvocation("ListByWorkflowRun", []interface{}{arg1, arg2})
	fake.listByWorkflowRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRunCallCount() int {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	return len(fake.listByWorkflowRunArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRunCalls(stub func(string, snapshot.WorkflowRunID) ([]schema.RunMetrics, error)) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = stub
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRunArgsForCall(i int) (string, snapshot.WorkflowRunID) {
	fake.listByWorkflowRunMutex.RLock()
	defer fake.listByWorkflowRunMutex.RUnlock()
	argsForCall := fake.listByWorkflowRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRunReturns(result1 []schema.RunMetrics, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	fake.listByWorkflowRunReturns = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) ListByWorkflowRunReturnsOnCall(i int, result1 []schema.RunMetrics, result2 error) {
	fake.listByWorkflowRunMutex.Lock()
	defer fake.listByWorkflowRunMutex.Unlock()
	fake.ListByWorkflowRunStub = nil
	if fake.listByWorkflowRunReturnsOnCall == nil {
		fake.listByWorkflowRunReturnsOnCall = make(map[int]struct {
			result1 []schema.RunMetrics
			result2 error
		})
	}
	fake.listByWorkflowRunReturnsOnCall[i] = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) ListRecent(arg1 int) ([]schema.RunMetrics, error) {
	fake.listRecentMutex.Lock()
	ret, specificReturn := fake.listRecentReturnsOnCall[len(fake.listRecentArgsForCall)]
	fake.listRecentArgsForCall = append(fake.listRecentArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.ListRecentStub
	fakeReturns := fake.listRecentReturns
	fake.recordInvocation("ListRecent", []interface{}{arg1})
	fake.listRecentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunMetricsFactory) ListRecentCallCount() int {
	fake.listRecentMutex.RLock()
	defer fake.listRecentMutex.RUnlock()
	return len(fake.listRecentArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) ListRecentCalls(stub func(int) ([]schema.RunMetrics, error)) {
	fake.listRecentMutex.Lock()
	defer fake.listRecentMutex.Unlock()
	fake.ListRecentStub = stub
}

func (fake *FakeAgentRunMetricsFactory) ListRecentArgsForCall(i int) int {
	fake.listRecentMutex.RLock()
	defer fake.listRecentMutex.RUnlock()
	argsForCall := fake.listRecentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) ListRecentReturns(result1 []schema.RunMetrics, result2 error) {
	fake.listRecentMutex.Lock()
	defer fake.listRecentMutex.Unlock()
	fake.ListRecentStub = nil
	fake.listRecentReturns = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) ListRecentReturnsOnCall(i int, result1 []schema.RunMetrics, result2 error) {
	fake.listRecentMutex.Lock()
	defer fake.listRecentMutex.Unlock()
	fake.ListRecentStub = nil
	if fake.listRecentReturnsOnCall == nil {
		fake.listRecentReturnsOnCall = make(map[int]struct {
			result1 []schema.RunMetrics
			result2 error
		})
	}
	fake.listRecentReturnsOnCall[i] = struct {
		result1 []schema.RunMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) Upsert(arg1 *schema.RunMetrics) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentRunMetricsFactory) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) UpsertCalls(stub func(*schema.RunMetrics) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeAgentRunMetricsFactory) UpsertArgsForCall(i int) *schema.RunMetrics {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInserted(arg1 *schema.RunMetrics) (bool, *schema.RunMetrics, error) {
	fake.upsertReturningInsertedMutex.Lock()
	ret, specificReturn := fake.upsertReturningInsertedReturnsOnCall[len(fake.upsertReturningInsertedArgsForCall)]
	fake.upsertReturningInsertedArgsForCall = append(fake.upsertReturningInsertedArgsForCall, struct {
		arg1 *schema.RunMetrics
	}{arg1})
	stub := fake.UpsertReturningInsertedStub
	fakeReturns := fake.upsertReturningInsertedReturns
	fake.recordInvocation("UpsertReturningInserted", []interface{}{arg1})
	fake.upsertReturningInsertedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInsertedCallCount() int {
	fake.upsertReturningInsertedMutex.RLock()
	defer fake.upsertReturningInsertedMutex.RUnlock()
	return len(fake.upsertReturningInsertedArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInsertedCalls(stub func(*schema.RunMetrics) (bool, *schema.RunMetrics, error)) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = stub
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInsertedArgsForCall(i int) *schema.RunMetrics {
	fake.upsertReturningInsertedMutex.RLock()
	defer fake.upsertReturningInsertedMutex.RUnlock()
	argsForCall := fake.upsertReturningInsertedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInsertedReturns(result1 bool, result2 *schema.RunMetrics, result3 error) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = nil
	fake.upsertReturningInsertedReturns = struct {
		result1 bool
		result2 *schema.RunMetrics
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentRunMetricsFactory) UpsertReturningInsertedReturnsOnCall(i int, result1 bool, result2 *schema.RunMetrics, result3 error) {
	fake.upsertReturningInsertedMutex.Lock()
	defer fake.upsertReturningInsertedMutex.Unlock()
	fake.UpsertReturningInsertedStub = nil
	if fake.upsertReturningInsertedReturnsOnCall == nil {
		fake.upsertReturningInsertedReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 *schema.RunMetrics
			result3 error
		})
	}
	fake.upsertReturningInsertedReturnsOnCall[i] = struct {
		result1 bool
		result2 *schema.RunMetrics
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStats(arg1 string) ([]schema.WorkflowVersionStats, error) {
	fake.workflowStatsMutex.Lock()
	ret, specificReturn := fake.workflowStatsReturnsOnCall[len(fake.workflowStatsArgsForCall)]
	fake.workflowStatsArgsForCall = append(fake.workflowStatsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.WorkflowStatsStub
	fakeReturns := fake.workflowStatsReturns
	fake.recordInvocation("WorkflowStats", []interface{}{arg1})
	fake.workflowStatsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStatsCallCount() int {
	fake.workflowStatsMutex.RLock()
	defer fake.workflowStatsMutex.RUnlock()
	return len(fake.workflowStatsArgsForCall)
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStatsCalls(stub func(string) ([]schema.WorkflowVersionStats, error)) {
	fake.workflowStatsMutex.Lock()
	defer fake.workflowStatsMutex.Unlock()
	fake.WorkflowStatsStub = stub
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStatsArgsForCall(i int) string {
	fake.workflowStatsMutex.RLock()
	defer fake.workflowStatsMutex.RUnlock()
	argsForCall := fake.workflowStatsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStatsReturns(result1 []schema.WorkflowVersionStats, result2 error) {
	fake.workflowStatsMutex.Lock()
	defer fake.workflowStatsMutex.Unlock()
	fake.WorkflowStatsStub = nil
	fake.workflowStatsReturns = struct {
		result1 []schema.WorkflowVersionStats
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) WorkflowStatsReturnsOnCall(i int, result1 []schema.WorkflowVersionStats, result2 error) {
	fake.workflowStatsMutex.Lock()
	defer fake.workflowStatsMutex.Unlock()
	fake.WorkflowStatsStub = nil
	if fake.workflowStatsReturnsOnCall == nil {
		fake.workflowStatsReturnsOnCall = make(map[int]struct {
			result1 []schema.WorkflowVersionStats
			result2 error
		})
	}
	fake.workflowStatsReturnsOnCall[i] = struct {
		result1 []schema.WorkflowVersionStats
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentRunMetricsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentRunMetricsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentRunMetricsFactory = new(FakeAgentRunMetricsFactory)
