// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/agent/api/feedback"
	"github.com/concourse/concourse/agent/snapshot"
	"github.com/concourse/concourse/atc/db"
)

type FakeAgentFeedbackFactory struct {
	GetAllStub        func() ([]feedback.StoredFeedback, error)
	getAllMutex       sync.RWMutex
	getAllArgsForCall []struct {
	}
	getAllReturns struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	getAllReturnsOnCall map[int]struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	GetByReviewStub        func(string, string) ([]feedback.StoredFeedback, error)
	getByReviewMutex       sync.RWMutex
	getByReviewArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getByReviewReturns struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	getByReviewReturnsOnCall map[int]struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	GetByReviewSnapshotStub        func(snapshot.SnapshotID, string) ([]feedback.StoredFeedback, error)
	getByReviewSnapshotMutex       sync.RWMutex
	getByReviewSnapshotArgsForCall []struct {
		arg1 snapshot.SnapshotID
		arg2 string
	}
	getByReviewSnapshotReturns struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	getByReviewSnapshotReturnsOnCall map[int]struct {
		result1 []feedback.StoredFeedback
		result2 error
	}
	SaveStub        func(*feedback.StoredFeedback) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		arg1 *feedback.StoredFeedback
	}
	saveReturns struct {
		result1 error
	}
	saveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentFeedbackFactory) GetAll() ([]feedback.StoredFeedback, error) {
	fake.getAllMutex.Lock()
	ret, specificReturn := fake.getAllReturnsOnCall[len(fake.getAllArgsForCall)]
	fake.getAllArgsForCall = append(fake.getAllArgsForCall, struct {
	}{})
	stub := fake.GetAllStub
	fakeReturns := fake.getAllReturns
	fake.recordInvocation("GetAll", []interface{}{})
	fake.getAllMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentFeedbackFactory) GetAllCallCount() int {
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	return len(fake.getAllArgsForCall)
}

func (fake *FakeAgentFeedbackFactory) GetAllCalls(stub func() ([]feedback.StoredFeedback, error)) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = stub
}

func (fake *FakeAgentFeedbackFactory) GetAllReturns(result1 []feedback.StoredFeedback, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	fake.getAllReturns = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) GetAllReturnsOnCall(i int, result1 []feedback.StoredFeedback, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	if fake.getAllReturnsOnCall == nil {
		fake.getAllReturnsOnCall = make(map[int]struct {
			result1 []feedback.StoredFeedback
			result2 error
		})
	}
	fake.getAllReturnsOnCall[i] = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) GetByReview(arg1 string, arg2 string) ([]feedback.StoredFeedback, error) {
	fake.getByReviewMutex.Lock()
	ret, specificReturn := fake.getByReviewReturnsOnCall[len(fake.getByReviewArgsForCall)]
	fake.getByReviewArgsForCall = append(fake.getByReviewArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetByReviewStub
	fakeReturns := fake.getByReviewReturns
	fake.recordInvocation("GetByReview", []interface{}{arg1, arg2})
	fake.getByReviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentFeedbackFactory) GetByReviewCallCount() int {
	fake.getByReviewMutex.RLock()
	defer fake.getByReviewMutex.RUnlock()
	return len(fake.getByReviewArgsForCall)
}

func (fake *FakeAgentFeedbackFactory) GetByReviewCalls(stub func(string, string) ([]feedback.StoredFeedback, error)) {
	fake.getByReviewMutex.Lock()
	defer fake.getByReviewMutex.Unlock()
	fake.GetByReviewStub = stub
}

func (fake *FakeAgentFeedbackFactory) GetByReviewArgsForCall(i int) (string, string) {
	fake.getByReviewMutex.RLock()
	defer fake.getByReviewMutex.RUnlock()
	argsForCall := fake.getByReviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentFeedbackFactory) GetByReviewReturns(result1 []feedback.StoredFeedback, result2 error) {
	fake.getByReviewMutex.Lock()
	defer fake.getByReviewMutex.Unlock()
	fake.GetByReviewStub = nil
	fake.getByReviewReturns = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) GetByReviewReturnsOnCall(i int, result1 []feedback.StoredFeedback, result2 error) {
	fake.getByReviewMutex.Lock()
	defer fake.getByReviewMutex.Unlock()
	fake.GetByReviewStub = nil
	if fake.getByReviewReturnsOnCall == nil {
		fake.getByReviewReturnsOnCall = make(map[int]struct {
			result1 []feedback.StoredFeedback
			result2 error
		})
	}
	fake.getByReviewReturnsOnCall[i] = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshot(arg1 snapshot.SnapshotID, arg2 string) ([]feedback.StoredFeedback, error) {
	fake.getByReviewSnapshotMutex.Lock()
	ret, specificReturn := fake.getByReviewSnapshotReturnsOnCall[len(fake.getByReviewSnapshotArgsForCall)]
	fake.getByReviewSnapshotArgsForCall = append(fake.getByReviewSnapshotArgsForCall, struct {
		arg1 snapshot.SnapshotID
		arg2 string
	}{arg1, arg2})
	stub := fake.GetByReviewSnapshotStub
	fakeReturns := fake.getByReviewSnapshotReturns
	fake.recordInvocation("GetByReviewSnapshot", []interface{}{arg1, arg2})
	fake.getByReviewSnapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshotCallCount() int {
	fake.getByReviewSnapshotMutex.RLock()
	defer fake.getByReviewSnapshotMutex.RUnlock()
	return len(fake.getByReviewSnapshotArgsForCall)
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshotCalls(stub func(snapshot.SnapshotID, string) ([]feedback.StoredFeedback, error)) {
	fake.getByReviewSnapshotMutex.Lock()
	defer fake.getByReviewSnapshotMutex.Unlock()
	fake.GetByReviewSnapshotStub = stub
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshotArgsForCall(i int) (snapshot.SnapshotID, string) {
	fake.getByReviewSnapshotMutex.RLock()
	defer fake.getByReviewSnapshotMutex.RUnlock()
	argsForCall := fake.getByReviewSnapshotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshotReturns(result1 []feedback.StoredFeedback, result2 error) {
	fake.getByReviewSnapshotMutex.Lock()
	defer fake.getByReviewSnapshotMutex.Unlock()
	fake.GetByReviewSnapshotStub = nil
	fake.getByReviewSnapshotReturns = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) GetByReviewSnapshotReturnsOnCall(i int, result1 []feedback.StoredFeedback, result2 error) {
	fake.getByReviewSnapshotMutex.Lock()
	defer fake.getByReviewSnapshotMutex.Unlock()
	fake.GetByReviewSnapshotStub = nil
	if fake.getByReviewSnapshotReturnsOnCall == nil {
		fake.getByReviewSnapshotReturnsOnCall = make(map[int]struct {
			result1 []feedback.StoredFeedback
			result2 error
		})
	}
	fake.getByReviewSnapshotReturnsOnCall[i] = struct {
		result1 []feedback.StoredFeedback
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentFeedbackFactory) Save(arg1 *feedback.StoredFeedback) error {
	fake.saveMutex.Lock()
	ret, specificReturn := fake.saveReturnsOnCall[len(fake.saveArgsForCall)]
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		arg1 *feedback.StoredFeedback
	}{arg1})
	stub := fake.SaveStub
	fakeReturns := fake.saveReturns
	fake.recordInvocation("Save", []interface{}{arg1})
	fake.saveMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentFeedbackFactory) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeAgentFeedbackFactory) SaveCalls(stub func(*feedback.StoredFeedback) error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = stub
}

func (fake *FakeAgentFeedbackFactory) SaveArgsForCall(i int) *feedback.StoredFeedback {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	argsForCall := fake.saveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAgentFeedbackFactory) SaveReturns(result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentFeedbackFactory) SaveReturnsOnCall(i int, result1 error) {
	fake.saveMutex.Lock()
	defer fake.saveMutex.Unlock()
	fake.SaveStub = nil
	if fake.saveReturnsOnCall == nil {
		fake.saveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentFeedbackFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentFeedbackFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentFeedbackFactory = new(FakeAgentFeedbackFactory)
