// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"
	"time"

	"github.com/concourse/concourse/atc/db"
)

type FakeAgentSettingsFactory struct {
	GetDispatcherModeStub        func() (string, bool, error)
	getDispatcherModeMutex       sync.RWMutex
	getDispatcherModeArgsForCall []struct {
	}
	getDispatcherModeReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	getDispatcherModeReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	GetDispatcherSettingStub        func() (string, time.Time, string, bool, error)
	getDispatcherSettingMutex       sync.RWMutex
	getDispatcherSettingArgsForCall []struct {
	}
	getDispatcherSettingReturns struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	getDispatcherSettingReturnsOnCall map[int]struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	SetDispatcherModeStub        func(string, string) error
	setDispatcherModeMutex       sync.RWMutex
	setDispatcherModeArgsForCall []struct {
		arg1 string
		arg2 string
	}
	setDispatcherModeReturns struct {
		result1 error
	}
	setDispatcherModeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentSettingsFactory) GetDispatcherMode() (string, bool, error) {
	fake.getDispatcherModeMutex.Lock()
	ret, specificReturn := fake.getDispatcherModeReturnsOnCall[len(fake.getDispatcherModeArgsForCall)]
	fake.getDispatcherModeArgsForCall = append(fake.getDispatcherModeArgsForCall, struct {
	}{})
	stub := fake.GetDispatcherModeStub
	fakeReturns := fake.getDispatcherModeReturns
	fake.recordInvocation("GetDispatcherMode", []interface{}{})
	fake.getDispatcherModeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeCallCount() int {
	fake.getDispatcherModeMutex.RLock()
	defer fake.getDispatcherModeMutex.RUnlock()
	return len(fake.getDispatcherModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeCalls(stub func() (string, bool, error)) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = stub
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeReturns(result1 string, result2 bool, result3 error) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = nil
	fake.getDispatcherModeReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = nil
	if fake.getDispatcherModeReturnsOnCall == nil {
		fake.getDispatcherModeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.getDispatcherModeReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSetting() (string, time.Time, string, bool, error) {
	fake.getDispatcherSettingMutex.Lock()
	ret, specificReturn := fake.getDispatcherSettingReturnsOnCall[len(fake.getDispatcherSettingArgsForCall)]
	fake.getDispatcherSettingArgsForCall = append(fake.getDispatcherSettingArgsForCall, struct {
	}{})
	stub := fake.GetDispatcherSettingStub
	fakeReturns := fake.getDispatcherSettingReturns
	fake.recordInvocation("GetDispatcherSetting", []interface{}{})
	fake.getDispatcherSettingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4, ret.result5
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4, fakeReturns.result5
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingCallCount() int {
	fake.getDispatcherSettingMutex.RLock()
	defer fake.getDispatcherSettingMutex.RUnlock()
	return len(fake.getDispatcherSettingArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingCalls(stub func() (string, time.Time, string, bool, error)) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = stub
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingReturns(result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = nil
	fake.getDispatcherSettingReturns = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingReturnsOnCall(i int, result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = nil
	if fake.getDispatcherSettingReturnsOnCall == nil {
		fake.getDispatcherSettingReturnsOnCall = make(map[int]struct {
			result1 string
			result2 time.Time
			result3 string
			result4 bool
			result5 error
		})
	}
	fake.getDispatcherSettingReturnsOnCall[i] = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) SetDispatcherMode(arg1 string, arg2 string) error {
	fake.setDispatcherModeMutex.Lock()
	ret, specificReturn := fake.setDispatcherModeReturnsOnCall[len(fake.setDispatcherModeArgsForCall)]
	fake.setDispatcherModeArgsForCall = append(fake.setDispatcherModeArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.SetDispatcherModeStub
	fakeReturns := fake.setDispatcherModeReturns
	fake.recordInvocation("SetDispatcherMode", []interface{}{arg1, arg2})
	fake.setDispatcherModeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeCallCount() int {
	fake.setDispatcherModeMutex.RLock()
	defer fake.setDispatcherModeMutex.RUnlock()
	return len(fake.setDispatcherModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeCalls(stub func(string, string) error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = stub
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeArgsForCall(i int) (string, string) {
	fake.setDispatcherModeMutex.RLock()
	defer fake.setDispatcherModeMutex.RUnlock()
	argsForCall := fake.setDispatcherModeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeReturns(result1 error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = nil
	fake.setDispatcherModeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeReturnsOnCall(i int, result1 error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = nil
	if fake.setDispatcherModeReturnsOnCall == nil {
		fake.setDispatcherModeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setDispatcherModeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentSettingsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentSettingsFactory = new(FakeAgentSettingsFactory)
