// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/concourse/atc/db"
)

type FakePipelineRunFactory struct {
	CompletedRunsWithNewActivityStub        func() ([]db.PipelineRun, error)
	completedRunsWithNewActivityMutex       sync.RWMutex
	completedRunsWithNewActivityArgsForCall []struct {
	}
	completedRunsWithNewActivityReturns struct {
		result1 []db.PipelineRun
		result2 error
	}
	completedRunsWithNewActivityReturnsOnCall map[int]struct {
		result1 []db.PipelineRun
		result2 error
	}
	CreateRunStub        func(int, map[string]any, string) (db.PipelineRun, error)
	createRunMutex       sync.RWMutex
	createRunArgsForCall []struct {
		arg1 int
		arg2 map[string]any
		arg3 string
	}
	createRunReturns struct {
		result1 db.PipelineRun
		result2 error
	}
	createRunReturnsOnCall map[int]struct {
		result1 db.PipelineRun
		result2 error
	}
	GetRunStub        func(int, int) (db.PipelineRun, bool, error)
	getRunMutex       sync.RWMutex
	getRunArgsForCall []struct {
		arg1 int
		arg2 int
	}
	getRunReturns struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}
	getRunReturnsOnCall map[int]struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}
	GetRunByIDStub        func(int) (db.PipelineRun, bool, error)
	getRunByIDMutex       sync.RWMutex
	getRunByIDArgsForCall []struct {
		arg1 int
	}
	getRunByIDReturns struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}
	getRunByIDReturnsOnCall map[int]struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}
	ListRunsStub        func(int, int) ([]db.PipelineRun, error)
	listRunsMutex       sync.RWMutex
	listRunsArgsForCall []struct {
		arg1 int
		arg2 int
	}
	listRunsReturns struct {
		result1 []db.PipelineRun
		result2 error
	}
	listRunsReturnsOnCall map[int]struct {
		result1 []db.PipelineRun
		result2 error
	}
	RunBelongsToPipelineStub        func(int, int) (bool, error)
	runBelongsToPipelineMutex       sync.RWMutex
	runBelongsToPipelineArgsForCall []struct {
		arg1 int
		arg2 int
	}
	runBelongsToPipelineReturns struct {
		result1 bool
		result2 error
	}
	runBelongsToPipelineReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	RunningRunsStub        func() ([]db.PipelineRun, error)
	runningRunsMutex       sync.RWMutex
	runningRunsArgsForCall []struct {
	}
	runningRunsReturns struct {
		result1 []db.PipelineRun
		result2 error
	}
	runningRunsReturnsOnCall map[int]struct {
		result1 []db.PipelineRun
		result2 error
	}
	RunsForTerminalTicketsStub        func() ([]db.PipelineRun, error)
	runsForTerminalTicketsMutex       sync.RWMutex
	runsForTerminalTicketsArgsForCall []struct {
	}
	runsForTerminalTicketsReturns struct {
		result1 []db.PipelineRun
		result2 error
	}
	runsForTerminalTicketsReturnsOnCall map[int]struct {
		result1 []db.PipelineRun
		result2 error
	}
	RunsToArchiveStub        func() ([]db.PipelineRun, error)
	runsToArchiveMutex       sync.RWMutex
	runsToArchiveArgsForCall []struct {
	}
	runsToArchiveReturns struct {
		result1 []db.PipelineRun
		result2 error
	}
	runsToArchiveReturnsOnCall map[int]struct {
		result1 []db.PipelineRun
		result2 error
	}
	TemplatesForTerminalTicketsStub        func() ([]db.Pipeline, error)
	templatesForTerminalTicketsMutex       sync.RWMutex
	templatesForTerminalTicketsArgsForCall []struct {
	}
	templatesForTerminalTicketsReturns struct {
		result1 []db.Pipeline
		result2 error
	}
	templatesForTerminalTicketsReturnsOnCall map[int]struct {
		result1 []db.Pipeline
		result2 error
	}
	TicketBelongsToRunStub        func(int, int) (bool, error)
	ticketBelongsToRunMutex       sync.RWMutex
	ticketBelongsToRunArgsForCall []struct {
		arg1 int
		arg2 int
	}
	ticketBelongsToRunReturns struct {
		result1 bool
		result2 error
	}
	ticketBelongsToRunReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePipelineRunFactory) CompletedRunsWithNewActivity() ([]db.PipelineRun, error) {
	fake.completedRunsWithNewActivityMutex.Lock()
	ret, specificReturn := fake.completedRunsWithNewActivityReturnsOnCall[len(fake.completedRunsWithNewActivityArgsForCall)]
	fake.completedRunsWithNewActivityArgsForCall = append(fake.completedRunsWithNewActivityArgsForCall, struct {
	}{})
	stub := fake.CompletedRunsWithNewActivityStub
	fakeReturns := fake.completedRunsWithNewActivityReturns
	fake.recordInvocation("CompletedRunsWithNewActivity", []interface{}{})
	fake.completedRunsWithNewActivityMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) CompletedRunsWithNewActivityCallCount() int {
	fake.completedRunsWithNewActivityMutex.RLock()
	defer fake.completedRunsWithNewActivityMutex.RUnlock()
	return len(fake.completedRunsWithNewActivityArgsForCall)
}

func (fake *FakePipelineRunFactory) CompletedRunsWithNewActivityCalls(stub func() ([]db.PipelineRun, error)) {
	fake.completedRunsWithNewActivityMutex.Lock()
	defer fake.completedRunsWithNewActivityMutex.Unlock()
	fake.CompletedRunsWithNewActivityStub = stub
}

func (fake *FakePipelineRunFactory) CompletedRunsWithNewActivityReturns(result1 []db.PipelineRun, result2 error) {
	fake.completedRunsWithNewActivityMutex.Lock()
	defer fake.completedRunsWithNewActivityMutex.Unlock()
	fake.CompletedRunsWithNewActivityStub = nil
	fake.completedRunsWithNewActivityReturns = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) CompletedRunsWithNewActivityReturnsOnCall(i int, result1 []db.PipelineRun, result2 error) {
	fake.completedRunsWithNewActivityMutex.Lock()
	defer fake.completedRunsWithNewActivityMutex.Unlock()
	fake.CompletedRunsWithNewActivityStub = nil
	if fake.completedRunsWithNewActivityReturnsOnCall == nil {
		fake.completedRunsWithNewActivityReturnsOnCall = make(map[int]struct {
			result1 []db.PipelineRun
			result2 error
		})
	}
	fake.completedRunsWithNewActivityReturnsOnCall[i] = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) CreateRun(arg1 int, arg2 map[string]any, arg3 string) (db.PipelineRun, error) {
	fake.createRunMutex.Lock()
	ret, specificReturn := fake.createRunReturnsOnCall[len(fake.createRunArgsForCall)]
	fake.createRunArgsForCall = append(fake.createRunArgsForCall, struct {
		arg1 int
		arg2 map[string]any
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateRunStub
	fakeReturns := fake.createRunReturns
	fake.recordInvocation("CreateRun", []interface{}{arg1, arg2, arg3})
	fake.createRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) CreateRunCallCount() int {
	fake.createRunMutex.RLock()
	defer fake.createRunMutex.RUnlock()
	return len(fake.createRunArgsForCall)
}

func (fake *FakePipelineRunFactory) CreateRunCalls(stub func(int, map[string]any, string) (db.PipelineRun, error)) {
	fake.createRunMutex.Lock()
	defer fake.createRunMutex.Unlock()
	fake.CreateRunStub = stub
}

func (fake *FakePipelineRunFactory) CreateRunArgsForCall(i int) (int, map[string]any, string) {
	fake.createRunMutex.RLock()
	defer fake.createRunMutex.RUnlock()
	argsForCall := fake.createRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePipelineRunFactory) CreateRunReturns(result1 db.PipelineRun, result2 error) {
	fake.createRunMutex.Lock()
	defer fake.createRunMutex.Unlock()
	fake.CreateRunStub = nil
	fake.createRunReturns = struct {
		result1 db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) CreateRunReturnsOnCall(i int, result1 db.PipelineRun, result2 error) {
	fake.createRunMutex.Lock()
	defer fake.createRunMutex.Unlock()
	fake.CreateRunStub = nil
	if fake.createRunReturnsOnCall == nil {
		fake.createRunReturnsOnCall = make(map[int]struct {
			result1 db.PipelineRun
			result2 error
		})
	}
	fake.createRunReturnsOnCall[i] = struct {
		result1 db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) GetRun(arg1 int, arg2 int) (db.PipelineRun, bool, error) {
	fake.getRunMutex.Lock()
	ret, specificReturn := fake.getRunReturnsOnCall[len(fake.getRunArgsForCall)]
	fake.getRunArgsForCall = append(fake.getRunArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	stub := fake.GetRunStub
	fakeReturns := fake.getRunReturns
	fake.recordInvocation("GetRun", []interface{}{arg1, arg2})
	fake.getRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakePipelineRunFactory) GetRunCallCount() int {
	fake.getRunMutex.RLock()
	defer fake.getRunMutex.RUnlock()
	return len(fake.getRunArgsForCall)
}

func (fake *FakePipelineRunFactory) GetRunCalls(stub func(int, int) (db.PipelineRun, bool, error)) {
	fake.getRunMutex.Lock()
	defer fake.getRunMutex.Unlock()
	fake.GetRunStub = stub
}

func (fake *FakePipelineRunFactory) GetRunArgsForCall(i int) (int, int) {
	fake.getRunMutex.RLock()
	defer fake.getRunMutex.RUnlock()
	argsForCall := fake.getRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePipelineRunFactory) GetRunReturns(result1 db.PipelineRun, result2 bool, result3 error) {
	fake.getRunMutex.Lock()
	defer fake.getRunMutex.Unlock()
	fake.GetRunStub = nil
	fake.getRunReturns = struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunFactory) GetRunReturnsOnCall(i int, result1 db.PipelineRun, result2 bool, result3 error) {
	fake.getRunMutex.Lock()
	defer fake.getRunMutex.Unlock()
	fake.GetRunStub = nil
	if fake.getRunReturnsOnCall == nil {
		fake.getRunReturnsOnCall = make(map[int]struct {
			result1 db.PipelineRun
			result2 bool
			result3 error
		})
	}
	fake.getRunReturnsOnCall[i] = struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunFactory) GetRunByID(arg1 int) (db.PipelineRun, bool, error) {
	fake.getRunByIDMutex.Lock()
	ret, specificReturn := fake.getRunByIDReturnsOnCall[len(fake.getRunByIDArgsForCall)]
	fake.getRunByIDArgsForCall = append(fake.getRunByIDArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetRunByIDStub
	fakeReturns := fake.getRunByIDReturns
	fake.recordInvocation("GetRunByID", []interface{}{arg1})
	fake.getRunByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakePipelineRunFactory) GetRunByIDCallCount() int {
	fake.getRunByIDMutex.RLock()
	defer fake.getRunByIDMutex.RUnlock()
	return len(fake.getRunByIDArgsForCall)
}

func (fake *FakePipelineRunFactory) GetRunByIDCalls(stub func(int) (db.PipelineRun, bool, error)) {
	fake.getRunByIDMutex.Lock()
	defer fake.getRunByIDMutex.Unlock()
	fake.GetRunByIDStub = stub
}

func (fake *FakePipelineRunFactory) GetRunByIDArgsForCall(i int) int {
	fake.getRunByIDMutex.RLock()
	defer fake.getRunByIDMutex.RUnlock()
	argsForCall := fake.getRunByIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePipelineRunFactory) GetRunByIDReturns(result1 db.PipelineRun, result2 bool, result3 error) {
	fake.getRunByIDMutex.Lock()
	defer fake.getRunByIDMutex.Unlock()
	fake.GetRunByIDStub = nil
	fake.getRunByIDReturns = struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunFactory) GetRunByIDReturnsOnCall(i int, result1 db.PipelineRun, result2 bool, result3 error) {
	fake.getRunByIDMutex.Lock()
	defer fake.getRunByIDMutex.Unlock()
	fake.GetRunByIDStub = nil
	if fake.getRunByIDReturnsOnCall == nil {
		fake.getRunByIDReturnsOnCall = make(map[int]struct {
			result1 db.PipelineRun
			result2 bool
			result3 error
		})
	}
	fake.getRunByIDReturnsOnCall[i] = struct {
		result1 db.PipelineRun
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePipelineRunFactory) ListRuns(arg1 int, arg2 int) ([]db.PipelineRun, error) {
	fake.listRunsMutex.Lock()
	ret, specificReturn := fake.listRunsReturnsOnCall[len(fake.listRunsArgsForCall)]
	fake.listRunsArgsForCall = append(fake.listRunsArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	stub := fake.ListRunsStub
	fakeReturns := fake.listRunsReturns
	fake.recordInvocation("ListRuns", []interface{}{arg1, arg2})
	fake.listRunsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) ListRunsCallCount() int {
	fake.listRunsMutex.RLock()
	defer fake.listRunsMutex.RUnlock()
	return len(fake.listRunsArgsForCall)
}

func (fake *FakePipelineRunFactory) ListRunsCalls(stub func(int, int) ([]db.PipelineRun, error)) {
	fake.listRunsMutex.Lock()
	defer fake.listRunsMutex.Unlock()
	fake.ListRunsStub = stub
}

func (fake *FakePipelineRunFactory) ListRunsArgsForCall(i int) (int, int) {
	fake.listRunsMutex.RLock()
	defer fake.listRunsMutex.RUnlock()
	argsForCall := fake.listRunsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePipelineRunFactory) ListRunsReturns(result1 []db.PipelineRun, result2 error) {
	fake.listRunsMutex.Lock()
	defer fake.listRunsMutex.Unlock()
	fake.ListRunsStub = nil
	fake.listRunsReturns = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) ListRunsReturnsOnCall(i int, result1 []db.PipelineRun, result2 error) {
	fake.listRunsMutex.Lock()
	defer fake.listRunsMutex.Unlock()
	fake.ListRunsStub = nil
	if fake.listRunsReturnsOnCall == nil {
		fake.listRunsReturnsOnCall = make(map[int]struct {
			result1 []db.PipelineRun
			result2 error
		})
	}
	fake.listRunsReturnsOnCall[i] = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunBelongsToPipeline(arg1 int, arg2 int) (bool, error) {
	fake.runBelongsToPipelineMutex.Lock()
	ret, specificReturn := fake.runBelongsToPipelineReturnsOnCall[len(fake.runBelongsToPipelineArgsForCall)]
	fake.runBelongsToPipelineArgsForCall = append(fake.runBelongsToPipelineArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	stub := fake.RunBelongsToPipelineStub
	fakeReturns := fake.runBelongsToPipelineReturns
	fake.recordInvocation("RunBelongsToPipeline", []interface{}{arg1, arg2})
	fake.runBelongsToPipelineMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) RunBelongsToPipelineCallCount() int {
	fake.runBelongsToPipelineMutex.RLock()
	defer fake.runBelongsToPipelineMutex.RUnlock()
	return len(fake.runBelongsToPipelineArgsForCall)
}

func (fake *FakePipelineRunFactory) RunBelongsToPipelineCalls(stub func(int, int) (bool, error)) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = stub
}

func (fake *FakePipelineRunFactory) RunBelongsToPipelineArgsForCall(i int) (int, int) {
	fake.runBelongsToPipelineMutex.RLock()
	defer fake.runBelongsToPipelineMutex.RUnlock()
	argsForCall := fake.runBelongsToPipelineArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePipelineRunFactory) RunBelongsToPipelineReturns(result1 bool, result2 error) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = nil
	fake.runBelongsToPipelineReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunBelongsToPipelineReturnsOnCall(i int, result1 bool, result2 error) {
	fake.runBelongsToPipelineMutex.Lock()
	defer fake.runBelongsToPipelineMutex.Unlock()
	fake.RunBelongsToPipelineStub = nil
	if fake.runBelongsToPipelineReturnsOnCall == nil {
		fake.runBelongsToPipelineReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.runBelongsToPipelineReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunningRuns() ([]db.PipelineRun, error) {
	fake.runningRunsMutex.Lock()
	ret, specificReturn := fake.runningRunsReturnsOnCall[len(fake.runningRunsArgsForCall)]
	fake.runningRunsArgsForCall = append(fake.runningRunsArgsForCall, struct {
	}{})
	stub := fake.RunningRunsStub
	fakeReturns := fake.runningRunsReturns
	fake.recordInvocation("RunningRuns", []interface{}{})
	fake.runningRunsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) RunningRunsCallCount() int {
	fake.runningRunsMutex.RLock()
	defer fake.runningRunsMutex.RUnlock()
	return len(fake.runningRunsArgsForCall)
}

func (fake *FakePipelineRunFactory) RunningRunsCalls(stub func() ([]db.PipelineRun, error)) {
	fake.runningRunsMutex.Lock()
	defer fake.runningRunsMutex.Unlock()
	fake.RunningRunsStub = stub
}

func (fake *FakePipelineRunFactory) RunningRunsReturns(result1 []db.PipelineRun, result2 error) {
	fake.runningRunsMutex.Lock()
	defer fake.runningRunsMutex.Unlock()
	fake.RunningRunsStub = nil
	fake.runningRunsReturns = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunningRunsReturnsOnCall(i int, result1 []db.PipelineRun, result2 error) {
	fake.runningRunsMutex.Lock()
	defer fake.runningRunsMutex.Unlock()
	fake.RunningRunsStub = nil
	if fake.runningRunsReturnsOnCall == nil {
		fake.runningRunsReturnsOnCall = make(map[int]struct {
			result1 []db.PipelineRun
			result2 error
		})
	}
	fake.runningRunsReturnsOnCall[i] = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunsForTerminalTickets() ([]db.PipelineRun, error) {
	fake.runsForTerminalTicketsMutex.Lock()
	ret, specificReturn := fake.runsForTerminalTicketsReturnsOnCall[len(fake.runsForTerminalTicketsArgsForCall)]
	fake.runsForTerminalTicketsArgsForCall = append(fake.runsForTerminalTicketsArgsForCall, struct {
	}{})
	stub := fake.RunsForTerminalTicketsStub
	fakeReturns := fake.runsForTerminalTicketsReturns
	fake.recordInvocation("RunsForTerminalTickets", []interface{}{})
	fake.runsForTerminalTicketsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) RunsForTerminalTicketsCallCount() int {
	fake.runsForTerminalTicketsMutex.RLock()
	defer fake.runsForTerminalTicketsMutex.RUnlock()
	return len(fake.runsForTerminalTicketsArgsForCall)
}

func (fake *FakePipelineRunFactory) RunsForTerminalTicketsCalls(stub func() ([]db.PipelineRun, error)) {
	fake.runsForTerminalTicketsMutex.Lock()
	defer fake.runsForTerminalTicketsMutex.Unlock()
	fake.RunsForTerminalTicketsStub = stub
}

func (fake *FakePipelineRunFactory) RunsForTerminalTicketsReturns(result1 []db.PipelineRun, result2 error) {
	fake.runsForTerminalTicketsMutex.Lock()
	defer fake.runsForTerminalTicketsMutex.Unlock()
	fake.RunsForTerminalTicketsStub = nil
	fake.runsForTerminalTicketsReturns = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunsForTerminalTicketsReturnsOnCall(i int, result1 []db.PipelineRun, result2 error) {
	fake.runsForTerminalTicketsMutex.Lock()
	defer fake.runsForTerminalTicketsMutex.Unlock()
	fake.RunsForTerminalTicketsStub = nil
	if fake.runsForTerminalTicketsReturnsOnCall == nil {
		fake.runsForTerminalTicketsReturnsOnCall = make(map[int]struct {
			result1 []db.PipelineRun
			result2 error
		})
	}
	fake.runsForTerminalTicketsReturnsOnCall[i] = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunsToArchive() ([]db.PipelineRun, error) {
	fake.runsToArchiveMutex.Lock()
	ret, specificReturn := fake.runsToArchiveReturnsOnCall[len(fake.runsToArchiveArgsForCall)]
	fake.runsToArchiveArgsForCall = append(fake.runsToArchiveArgsForCall, struct {
	}{})
	stub := fake.RunsToArchiveStub
	fakeReturns := fake.runsToArchiveReturns
	fake.recordInvocation("RunsToArchive", []interface{}{})
	fake.runsToArchiveMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) RunsToArchiveCallCount() int {
	fake.runsToArchiveMutex.RLock()
	defer fake.runsToArchiveMutex.RUnlock()
	return len(fake.runsToArchiveArgsForCall)
}

func (fake *FakePipelineRunFactory) RunsToArchiveCalls(stub func() ([]db.PipelineRun, error)) {
	fake.runsToArchiveMutex.Lock()
	defer fake.runsToArchiveMutex.Unlock()
	fake.RunsToArchiveStub = stub
}

func (fake *FakePipelineRunFactory) RunsToArchiveReturns(result1 []db.PipelineRun, result2 error) {
	fake.runsToArchiveMutex.Lock()
	defer fake.runsToArchiveMutex.Unlock()
	fake.RunsToArchiveStub = nil
	fake.runsToArchiveReturns = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) RunsToArchiveReturnsOnCall(i int, result1 []db.PipelineRun, result2 error) {
	fake.runsToArchiveMutex.Lock()
	defer fake.runsToArchiveMutex.Unlock()
	fake.RunsToArchiveStub = nil
	if fake.runsToArchiveReturnsOnCall == nil {
		fake.runsToArchiveReturnsOnCall = make(map[int]struct {
			result1 []db.PipelineRun
			result2 error
		})
	}
	fake.runsToArchiveReturnsOnCall[i] = struct {
		result1 []db.PipelineRun
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) TemplatesForTerminalTickets() ([]db.Pipeline, error) {
	fake.templatesForTerminalTicketsMutex.Lock()
	ret, specificReturn := fake.templatesForTerminalTicketsReturnsOnCall[len(fake.templatesForTerminalTicketsArgsForCall)]
	fake.templatesForTerminalTicketsArgsForCall = append(fake.templatesForTerminalTicketsArgsForCall, struct {
	}{})
	stub := fake.TemplatesForTerminalTicketsStub
	fakeReturns := fake.templatesForTerminalTicketsReturns
	fake.recordInvocation("TemplatesForTerminalTickets", []interface{}{})
	fake.templatesForTerminalTicketsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) TemplatesForTerminalTicketsCallCount() int {
	fake.templatesForTerminalTicketsMutex.RLock()
	defer fake.templatesForTerminalTicketsMutex.RUnlock()
	return len(fake.templatesForTerminalTicketsArgsForCall)
}

func (fake *FakePipelineRunFactory) TemplatesForTerminalTicketsCalls(stub func() ([]db.Pipeline, error)) {
	fake.templatesForTerminalTicketsMutex.Lock()
	defer fake.templatesForTerminalTicketsMutex.Unlock()
	fake.TemplatesForTerminalTicketsStub = stub
}

func (fake *FakePipelineRunFactory) TemplatesForTerminalTicketsReturns(result1 []db.Pipeline, result2 error) {
	fake.templatesForTerminalTicketsMutex.Lock()
	defer fake.templatesForTerminalTicketsMutex.Unlock()
	fake.TemplatesForTerminalTicketsStub = nil
	fake.templatesForTerminalTicketsReturns = struct {
		result1 []db.Pipeline
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) TemplatesForTerminalTicketsReturnsOnCall(i int, result1 []db.Pipeline, result2 error) {
	fake.templatesForTerminalTicketsMutex.Lock()
	defer fake.templatesForTerminalTicketsMutex.Unlock()
	fake.TemplatesForTerminalTicketsStub = nil
	if fake.templatesForTerminalTicketsReturnsOnCall == nil {
		fake.templatesForTerminalTicketsReturnsOnCall = make(map[int]struct {
			result1 []db.Pipeline
			result2 error
		})
	}
	fake.templatesForTerminalTicketsReturnsOnCall[i] = struct {
		result1 []db.Pipeline
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) TicketBelongsToRun(arg1 int, arg2 int) (bool, error) {
	fake.ticketBelongsToRunMutex.Lock()
	ret, specificReturn := fake.ticketBelongsToRunReturnsOnCall[len(fake.ticketBelongsToRunArgsForCall)]
	fake.ticketBelongsToRunArgsForCall = append(fake.ticketBelongsToRunArgsForCall, struct {
		arg1 int
		arg2 int
	}{arg1, arg2})
	stub := fake.TicketBelongsToRunStub
	fakeReturns := fake.ticketBelongsToRunReturns
	fake.recordInvocation("TicketBelongsToRun", []interface{}{arg1, arg2})
	fake.ticketBelongsToRunMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePipelineRunFactory) TicketBelongsToRunCallCount() int {
	fake.ticketBelongsToRunMutex.RLock()
	defer fake.ticketBelongsToRunMutex.RUnlock()
	return len(fake.ticketBelongsToRunArgsForCall)
}

func (fake *FakePipelineRunFactory) TicketBelongsToRunCalls(stub func(int, int) (bool, error)) {
	fake.ticketBelongsToRunMutex.Lock()
	defer fake.ticketBelongsToRunMutex.Unlock()
	fake.TicketBelongsToRunStub = stub
}

func (fake *FakePipelineRunFactory) TicketBelongsToRunArgsForCall(i int) (int, int) {
	fake.ticketBelongsToRunMutex.RLock()
	defer fake.ticketBelongsToRunMutex.RUnlock()
	argsForCall := fake.ticketBelongsToRunArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePipelineRunFactory) TicketBelongsToRunReturns(result1 bool, result2 error) {
	fake.ticketBelongsToRunMutex.Lock()
	defer fake.ticketBelongsToRunMutex.Unlock()
	fake.TicketBelongsToRunStub = nil
	fake.ticketBelongsToRunReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) TicketBelongsToRunReturnsOnCall(i int, result1 bool, result2 error) {
	fake.ticketBelongsToRunMutex.Lock()
	defer fake.ticketBelongsToRunMutex.Unlock()
	fake.TicketBelongsToRunStub = nil
	if fake.ticketBelongsToRunReturnsOnCall == nil {
		fake.ticketBelongsToRunReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.ticketBelongsToRunReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePipelineRunFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePipelineRunFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.PipelineRunFactory = new(FakePipelineRunFactory)
