// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"
	"time"

	"github.com/concourse/concourse/atc/db"
)

type FakeAgentSettingsFactory struct {
	GetActionsModeStub        func() (string, bool, error)
	getActionsModeMutex       sync.RWMutex
	getActionsModeArgsForCall []struct {
	}
	getActionsModeReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	getActionsModeReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	GetActionsSettingStub        func() (string, time.Time, string, bool, error)
	getActionsSettingMutex       sync.RWMutex
	getActionsSettingArgsForCall []struct {
	}
	getActionsSettingReturns struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	getActionsSettingReturnsOnCall map[int]struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	GetDispatcherModeStub        func() (string, bool, error)
	getDispatcherModeMutex       sync.RWMutex
	getDispatcherModeArgsForCall []struct {
	}
	getDispatcherModeReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	getDispatcherModeReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	GetDispatcherSettingStub        func() (string, time.Time, string, bool, error)
	getDispatcherSettingMutex       sync.RWMutex
	getDispatcherSettingArgsForCall []struct {
	}
	getDispatcherSettingReturns struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	getDispatcherSettingReturnsOnCall map[int]struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}
	SetActionsModeStub        func(string, string) error
	setActionsModeMutex       sync.RWMutex
	setActionsModeArgsForCall []struct {
		arg1 string
		arg2 string
	}
	setActionsModeReturns struct {
		result1 error
	}
	setActionsModeReturnsOnCall map[int]struct {
		result1 error
	}
	SetDispatcherModeStub        func(string, string) error
	setDispatcherModeMutex       sync.RWMutex
	setDispatcherModeArgsForCall []struct {
		arg1 string
		arg2 string
	}
	setDispatcherModeReturns struct {
		result1 error
	}
	setDispatcherModeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentSettingsFactory) GetActionsMode() (string, bool, error) {
	fake.getActionsModeMutex.Lock()
	ret, specificReturn := fake.getActionsModeReturnsOnCall[len(fake.getActionsModeArgsForCall)]
	fake.getActionsModeArgsForCall = append(fake.getActionsModeArgsForCall, struct {
	}{})
	stub := fake.GetActionsModeStub
	fakeReturns := fake.getActionsModeReturns
	fake.recordInvocation("GetActionsMode", []interface{}{})
	fake.getActionsModeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentSettingsFactory) GetActionsModeCallCount() int {
	fake.getActionsModeMutex.RLock()
	defer fake.getActionsModeMutex.RUnlock()
	return len(fake.getActionsModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetActionsModeCalls(stub func() (string, bool, error)) {
	fake.getActionsModeMutex.Lock()
	defer fake.getActionsModeMutex.Unlock()
	fake.GetActionsModeStub = stub
}

func (fake *FakeAgentSettingsFactory) GetActionsModeReturns(result1 string, result2 bool, result3 error) {
	fake.getActionsModeMutex.Lock()
	defer fake.getActionsModeMutex.Unlock()
	fake.GetActionsModeStub = nil
	fake.getActionsModeReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetActionsModeReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.getActionsModeMutex.Lock()
	defer fake.getActionsModeMutex.Unlock()
	fake.GetActionsModeStub = nil
	if fake.getActionsModeReturnsOnCall == nil {
		fake.getActionsModeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.getActionsModeReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetActionsSetting() (string, time.Time, string, bool, error) {
	fake.getActionsSettingMutex.Lock()
	ret, specificReturn := fake.getActionsSettingReturnsOnCall[len(fake.getActionsSettingArgsForCall)]
	fake.getActionsSettingArgsForCall = append(fake.getActionsSettingArgsForCall, struct {
	}{})
	stub := fake.GetActionsSettingStub
	fakeReturns := fake.getActionsSettingReturns
	fake.recordInvocation("GetActionsSetting", []interface{}{})
	fake.getActionsSettingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4, ret.result5
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4, fakeReturns.result5
}

func (fake *FakeAgentSettingsFactory) GetActionsSettingCallCount() int {
	fake.getActionsSettingMutex.RLock()
	defer fake.getActionsSettingMutex.RUnlock()
	return len(fake.getActionsSettingArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetActionsSettingCalls(stub func() (string, time.Time, string, bool, error)) {
	fake.getActionsSettingMutex.Lock()
	defer fake.getActionsSettingMutex.Unlock()
	fake.GetActionsSettingStub = stub
}

func (fake *FakeAgentSettingsFactory) GetActionsSettingReturns(result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getActionsSettingMutex.Lock()
	defer fake.getActionsSettingMutex.Unlock()
	fake.GetActionsSettingStub = nil
	fake.getActionsSettingReturns = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) GetActionsSettingReturnsOnCall(i int, result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getActionsSettingMutex.Lock()
	defer fake.getActionsSettingMutex.Unlock()
	fake.GetActionsSettingStub = nil
	if fake.getActionsSettingReturnsOnCall == nil {
		fake.getActionsSettingReturnsOnCall = make(map[int]struct {
			result1 string
			result2 time.Time
			result3 string
			result4 bool
			result5 error
		})
	}
	fake.getActionsSettingReturnsOnCall[i] = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherMode() (string, bool, error) {
	fake.getDispatcherModeMutex.Lock()
	ret, specificReturn := fake.getDispatcherModeReturnsOnCall[len(fake.getDispatcherModeArgsForCall)]
	fake.getDispatcherModeArgsForCall = append(fake.getDispatcherModeArgsForCall, struct {
	}{})
	stub := fake.GetDispatcherModeStub
	fakeReturns := fake.getDispatcherModeReturns
	fake.recordInvocation("GetDispatcherMode", []interface{}{})
	fake.getDispatcherModeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeCallCount() int {
	fake.getDispatcherModeMutex.RLock()
	defer fake.getDispatcherModeMutex.RUnlock()
	return len(fake.getDispatcherModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeCalls(stub func() (string, bool, error)) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = stub
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeReturns(result1 string, result2 bool, result3 error) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = nil
	fake.getDispatcherModeReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherModeReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.getDispatcherModeMutex.Lock()
	defer fake.getDispatcherModeMutex.Unlock()
	fake.GetDispatcherModeStub = nil
	if fake.getDispatcherModeReturnsOnCall == nil {
		fake.getDispatcherModeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.getDispatcherModeReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSetting() (string, time.Time, string, bool, error) {
	fake.getDispatcherSettingMutex.Lock()
	ret, specificReturn := fake.getDispatcherSettingReturnsOnCall[len(fake.getDispatcherSettingArgsForCall)]
	fake.getDispatcherSettingArgsForCall = append(fake.getDispatcherSettingArgsForCall, struct {
	}{})
	stub := fake.GetDispatcherSettingStub
	fakeReturns := fake.getDispatcherSettingReturns
	fake.recordInvocation("GetDispatcherSetting", []interface{}{})
	fake.getDispatcherSettingMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4, ret.result5
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4, fakeReturns.result5
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingCallCount() int {
	fake.getDispatcherSettingMutex.RLock()
	defer fake.getDispatcherSettingMutex.RUnlock()
	return len(fake.getDispatcherSettingArgsForCall)
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingCalls(stub func() (string, time.Time, string, bool, error)) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = stub
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingReturns(result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = nil
	fake.getDispatcherSettingReturns = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) GetDispatcherSettingReturnsOnCall(i int, result1 string, result2 time.Time, result3 string, result4 bool, result5 error) {
	fake.getDispatcherSettingMutex.Lock()
	defer fake.getDispatcherSettingMutex.Unlock()
	fake.GetDispatcherSettingStub = nil
	if fake.getDispatcherSettingReturnsOnCall == nil {
		fake.getDispatcherSettingReturnsOnCall = make(map[int]struct {
			result1 string
			result2 time.Time
			result3 string
			result4 bool
			result5 error
		})
	}
	fake.getDispatcherSettingReturnsOnCall[i] = struct {
		result1 string
		result2 time.Time
		result3 string
		result4 bool
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeAgentSettingsFactory) SetActionsMode(arg1 string, arg2 string) error {
	fake.setActionsModeMutex.Lock()
	ret, specificReturn := fake.setActionsModeReturnsOnCall[len(fake.setActionsModeArgsForCall)]
	fake.setActionsModeArgsForCall = append(fake.setActionsModeArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.SetActionsModeStub
	fakeReturns := fake.setActionsModeReturns
	fake.recordInvocation("SetActionsMode", []interface{}{arg1, arg2})
	fake.setActionsModeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentSettingsFactory) SetActionsModeCallCount() int {
	fake.setActionsModeMutex.RLock()
	defer fake.setActionsModeMutex.RUnlock()
	return len(fake.setActionsModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) SetActionsModeCalls(stub func(string, string) error) {
	fake.setActionsModeMutex.Lock()
	defer fake.setActionsModeMutex.Unlock()
	fake.SetActionsModeStub = stub
}

func (fake *FakeAgentSettingsFactory) SetActionsModeArgsForCall(i int) (string, string) {
	fake.setActionsModeMutex.RLock()
	defer fake.setActionsModeMutex.RUnlock()
	argsForCall := fake.setActionsModeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentSettingsFactory) SetActionsModeReturns(result1 error) {
	fake.setActionsModeMutex.Lock()
	defer fake.setActionsModeMutex.Unlock()
	fake.SetActionsModeStub = nil
	fake.setActionsModeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) SetActionsModeReturnsOnCall(i int, result1 error) {
	fake.setActionsModeMutex.Lock()
	defer fake.setActionsModeMutex.Unlock()
	fake.SetActionsModeStub = nil
	if fake.setActionsModeReturnsOnCall == nil {
		fake.setActionsModeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setActionsModeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) SetDispatcherMode(arg1 string, arg2 string) error {
	fake.setDispatcherModeMutex.Lock()
	ret, specificReturn := fake.setDispatcherModeReturnsOnCall[len(fake.setDispatcherModeArgsForCall)]
	fake.setDispatcherModeArgsForCall = append(fake.setDispatcherModeArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.SetDispatcherModeStub
	fakeReturns := fake.setDispatcherModeReturns
	fake.recordInvocation("SetDispatcherMode", []interface{}{arg1, arg2})
	fake.setDispatcherModeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeCallCount() int {
	fake.setDispatcherModeMutex.RLock()
	defer fake.setDispatcherModeMutex.RUnlock()
	return len(fake.setDispatcherModeArgsForCall)
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeCalls(stub func(string, string) error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = stub
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeArgsForCall(i int) (string, string) {
	fake.setDispatcherModeMutex.RLock()
	defer fake.setDispatcherModeMutex.RUnlock()
	argsForCall := fake.setDispatcherModeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeReturns(result1 error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = nil
	fake.setDispatcherModeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) SetDispatcherModeReturnsOnCall(i int, result1 error) {
	fake.setDispatcherModeMutex.Lock()
	defer fake.setDispatcherModeMutex.Unlock()
	fake.SetDispatcherModeStub = nil
	if fake.setDispatcherModeReturnsOnCall == nil {
		fake.setDispatcherModeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setDispatcherModeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAgentSettingsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentSettingsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.AgentSettingsFactory = new(FakeAgentSettingsFactory)
