package accessor

import (
	"github.com/concourse/concourse/atc"
)

const (
	MemberRole   = "member"
	OwnerRole    = "owner"
	OperatorRole = "pipeline-operator"
	ViewerRole   = "viewer"
)

var DefaultRoles = map[string]string{
	atc.SaveConfig:                     MemberRole,
	atc.GetConfig:                      ViewerRole,
	atc.GetCC:                          ViewerRole,
	atc.GetBuild:                       ViewerRole,
	atc.GetBuildPlan:                   ViewerRole,
	atc.CreateBuild:                    MemberRole,
	atc.ListBuilds:                     ViewerRole,
	atc.BuildEvents:                    ViewerRole,
	atc.BuildResources:                 ViewerRole,
	atc.AbortBuild:                     OperatorRole,
	atc.GetBuildPreparation:            ViewerRole,
	atc.GetJob:                         ViewerRole,
	atc.CreateJobBuild:                 OperatorRole,
	atc.RerunJobBuild:                  OperatorRole,
	atc.SetBuildComment:                OperatorRole,
	atc.ListAllJobs:                    ViewerRole,
	atc.ListJobs:                       ViewerRole,
	atc.ListJobBuilds:                  ViewerRole,
	atc.ListJobInputs:                  ViewerRole,
	atc.GetJobBuild:                    ViewerRole,
	atc.PauseJob:                       OperatorRole,
	atc.UnpauseJob:                     OperatorRole,
	atc.ScheduleJob:                    OperatorRole,
	atc.GetVersionsDB:                  ViewerRole,
	atc.JobBadge:                       ViewerRole,
	atc.MainJobBadge:                   ViewerRole,
	atc.ClearTaskCache:                 OperatorRole,
	atc.ListAllResources:               ViewerRole,
	atc.ListResources:                  ViewerRole,
	atc.ListResourceTypes:              ViewerRole,
	atc.GetResource:                    ViewerRole,
	atc.UnpinResource:                  OperatorRole,
	atc.SetPinCommentOnResource:        OperatorRole,
	atc.CheckResource:                  OperatorRole,
	atc.CheckResourceWebHook:           OperatorRole,
	atc.CheckResourceType:              OperatorRole,
	atc.CheckPrototype:                 OperatorRole,
	atc.ListResourceVersions:           ViewerRole,
	atc.GetResourceVersion:             ViewerRole,
	atc.EnableResourceVersion:          OperatorRole,
	atc.DisableResourceVersion:         OperatorRole,
	atc.PinResourceVersion:             OperatorRole,
	atc.ListBuildsWithVersionAsInput:   ViewerRole,
	atc.ListBuildsWithVersionAsOutput:  ViewerRole,
	atc.GetDownstreamResourceCausality: ViewerRole,
	atc.GetUpstreamResourceCausality:   ViewerRole,
	atc.ClearResourceCache:             OperatorRole,
	atc.CopyResourceVersions:           OperatorRole,
	atc.ListDeprecatedScopes:           ViewerRole,
	atc.ListAllPipelines:               ViewerRole,
	atc.ListPipelines:                  ViewerRole,
	atc.GetPipeline:                    ViewerRole,
	atc.DeletePipeline:                 MemberRole,
	atc.OrderPipelines:                 MemberRole,
	atc.OrderPipelinesWithinGroup:      MemberRole,
	atc.PausePipeline:                  OperatorRole,
	atc.ArchivePipeline:                MemberRole,
	atc.UnpausePipeline:                OperatorRole,
	atc.ExposePipeline:                 MemberRole,
	atc.HidePipeline:                   MemberRole,
	atc.RenamePipeline:                 MemberRole,
	atc.ListPipelineBuilds:             ViewerRole,
	atc.CreatePipelineBuild:            MemberRole,
	atc.PipelineBadge:                  ViewerRole,
	atc.RegisterWorker:                 MemberRole,
	atc.ListWorkers:                    ViewerRole,
	atc.DeleteWorker:                   MemberRole,
	atc.SetLogLevel:                    MemberRole,
	atc.GetLogLevel:                    ViewerRole,
	atc.DownloadCLI:                    ViewerRole,
	atc.GetInfo:                        ViewerRole,
	atc.GetInfoCreds:                   ViewerRole,
	atc.GetHealth:                      ViewerRole,
	atc.ListContainers:                 ViewerRole,
	atc.GetContainer:                   ViewerRole,
	atc.HijackContainer:                MemberRole,
	atc.ListVolumes:                    ViewerRole,
	atc.ListTeams:                      ViewerRole,
	atc.GetTeam:                        ViewerRole,
	atc.SetTeam:                        OwnerRole,
	atc.RenameTeam:                     OwnerRole,
	atc.DestroyTeam:                    OwnerRole,
	atc.ListTeamBuilds:                 ViewerRole,
	atc.CreateArtifact:                 MemberRole,
	atc.GetArtifact:                    MemberRole,
	atc.ListBuildArtifacts:             ViewerRole,
	atc.GetWall:                        ViewerRole,
	// Agent review/feedback routes. Team-less /api/v1/agent/* routes are
	// wrapped in CheckAgentAuthorizationHandler, which authorizes against
	// the main team using these entries. Every route in that wrappa case
	// (and every :team_name-scoped route in CheckAuthorizationHandler)
	// needs an entry here: a missing entry resolves to requiredRole ""
	// and hasRequiredRole's default case, making the route admin-only.
	atc.SubmitAgentFeedback:         MemberRole,
	atc.ListRecentAgentRunMetrics:   ViewerRole,
	atc.ListBuildAgentRunMetrics:    ViewerRole,
	atc.ListTeamAgentReviews:        ViewerRole,
	atc.GetBuildAgentReviews:        ViewerRole,
	atc.GetAgentSnapshotReview:      ViewerRole,
	atc.ListAgentWorkflowRunReviews: ViewerRole,
	atc.GetAgentCostRollup:          ViewerRole,
	atc.CreatePipelineRun:           MemberRole,
	atc.ListPipelineRuns:            ViewerRole,
	atc.GetPipelineRun:              ViewerRole,

	atc.ListAgentWorkflows:                         ViewerRole,
	atc.ListAgentWorkflowVersions:                  ViewerRole,
	atc.GetAgentWorkflowVersion:                    ViewerRole,
	atc.CreateAgentWorkflowVersion:                 MemberRole,
	atc.PromoteAgentWorkflowVersion:                MemberRole,
	atc.GetAgentWorkflowStats:                      ViewerRole,
	atc.UpdateAgentWorkflow:                        MemberRole,
	atc.CreateAgentWorkflowRun:                     MemberRole,
	atc.ListAgentWorkflowRuns:                      ViewerRole,
	atc.GetAgentWorkflowRunOperationalStatusCounts: ViewerRole,
	atc.GetAgentWorkflowRun:                        ViewerRole,
	atc.CancelAgentWorkflowRun:                     MemberRole,
	atc.RetryAgentWorkflowRun:                      MemberRole,
	atc.GetAgentWorkflowRunOutputs:                 ViewerRole,
	atc.ListAgentWorkflowRunWaits:                  ViewerRole,
	atc.ResolveAgentWorkflowRunWait:                MemberRole,
	atc.ListAgentWorkflowRunOutcomes:               ViewerRole,
	atc.SetAgentWorkflowRunOutputOutcome:           MemberRole,
	atc.ListAgentWorkflowRunMetrics:                ViewerRole,
	atc.ListAgentWorkflowRunTranscripts:            ViewerRole,
	atc.GetAgentWorkflowRunTranscript:              ViewerRole,
	atc.CreateAgentExperiment:                      MemberRole,
	atc.ListAgentExperiments:                       ViewerRole,
	atc.GetAgentExperiment:                         ViewerRole,
	atc.UpdateAgentExperiment:                      MemberRole,
	atc.ValidateAgentExperiment:                    ViewerRole,
	atc.StartAgentExperiment:                       MemberRole,
	atc.CancelAgentExperiment:                      MemberRole,
	atc.ListAgentExperimentCells:                   ViewerRole,
	atc.GetAgentExperimentCell:                     ViewerRole,
	atc.GetAgentExperimentScorecard:                ViewerRole,

	atc.CreateAgentSnapshot:                MemberRole,
	atc.CaptureAgentResourceSnapshot:       MemberRole,
	atc.ListAgentSnapshots:                 ViewerRole,
	atc.GetAgentSnapshot:                   ViewerRole,
	atc.GetAgentRepositoryChangeProjection: ViewerRole,
	atc.DownloadAgentSnapshot:              ViewerRole,
	atc.PinAgentSnapshot:                   MemberRole,
	atc.UnpinAgentSnapshot:                 MemberRole,

	// Ticket-core routes (00-shared-contracts.md §4.2).
	atc.ListAgentTickets:      ViewerRole,
	atc.CreateAgentTicket:     MemberRole,
	atc.GetAgentTicket:        ViewerRole,
	atc.UpdateAgentTicket:     MemberRole,
	atc.TransitionAgentTicket: MemberRole,
	atc.DispatchAgentTicket:   MemberRole,
}
