DROP TRIGGER hangar_output_activation_role_guard_truncate ON hangar_output_activation_epochs;
DROP TRIGGER hangar_output_activation_role_guard ON hangar_output_activation_epochs;
DROP FUNCTION hangar_activation_role_guard();
