package output

import (
	"crypto/ed25519"
	"encoding/base64"
	"fmt"
	"reflect"
	"time"

	"github.com/concourse/concourse/hangar"
	"github.com/concourse/concourse/hangar/executioncontrol"
	"github.com/google/uuid"
)

const InputPublicationVersion = "hangar-input/v1"

const MaxInputContentBytes int64 = 256 << 20

// InputStage describes canonical bytes privately staged by the publishing node.
// It is not a publication, a read warrant, or authority to admit a Run. The
// consumer must durably reserve this logical identity before calling publish.
type InputStage struct {
	Version         string                           `json:"version"`
	ReservationID   ReservationID                    `json:"reservation_id"`
	NodeUID         executioncontrol.NodeUID         `json:"node_uid"`
	ActivationEpoch executioncontrol.ActivationEpoch `json:"activation_epoch"`
	Scope           hangar.Scope                     `json:"scope"`
	Digest          hangar.Digest                    `json:"digest"`
	Bytes           int64                            `json:"bytes"`
	CreatedAt       Timestamp                        `json:"created_at"`
	ExpiresAt       Timestamp                        `json:"expires_at"`
}

func (s InputStage) Validate() error {
	if s.Version != InputPublicationVersion || s.ReservationID.Validate() != nil || s.NodeUID == "" || s.ActivationEpoch == 0 || s.Scope.Validate() != nil || s.Digest.Validate() != nil || s.Bytes <= 0 || s.CreatedAt.Validate() != nil || s.ExpiresAt.Validate() != nil || !s.ExpiresAt.After(s.CreatedAt.Time) || s.ExpiresAt.Sub(s.CreatedAt.Time) > 2*time.Minute {
		return fmt.Errorf("%w: invalid input stage", ErrIncomplete)
	}
	return nil
}

func (s InputStage) ObjectMarker() ObjectMarker {
	return ObjectMarker{Version: MarkerVersion, ReservationID: s.ReservationID, ActivationEpoch: s.ActivationEpoch, Scope: s.Scope, Digest: s.Digest, CreatedAt: s.CreatedAt}
}

// InputPublishRequest contains no path, scope or bucket. Nonce is generated by
// the consumer and retained with its logical reservation before object create.
type InputPublishRequest struct {
	Version       string        `json:"version"`
	ReservationID ReservationID `json:"reservation_id"`
	Nonce         string        `json:"nonce"`
}

func (p InputPublishRequest) Validate() error {
	if p.Version != InputPublicationVersion || p.ReservationID.Validate() != nil {
		return ErrIncomplete
	}
	if id, err := uuid.Parse(p.Nonce); err != nil || id == uuid.Nil || id.String() != p.Nonce {
		return ErrIncomplete
	}
	return nil
}

// InputPublication is a fresh node-signed observation of an exact publication.
// The marker may belong to an earlier publication of identical bytes. There is
// no execution, Pod or quiescence witness because an upload has none.
type InputPublication struct {
	Stage          InputStage        `json:"stage"`
	Nonce          string            `json:"nonce"`
	Attributes     TreeAttributes    `json:"attributes"`
	Metageneration int64             `json:"metageneration"`
	Marker         map[string]string `json:"marker"`
	SignedAt       Timestamp         `json:"signed_at"`
	KeyID          string            `json:"key_id"`
	Signature      string            `json:"signature"`
}

func (p InputPublication) Validate() error {
	if err := p.validateClaims(); err != nil {
		return err
	}
	signature, err := base64.StdEncoding.DecodeString(p.Signature)
	if err != nil || len(signature) != ed25519.SignatureSize {
		return ErrCorrupt
	}
	return nil
}

func (p InputPublication) validateClaims() error {
	if err := p.Stage.Validate(); err != nil {
		return err
	}
	if err := (InputPublishRequest{Version: p.Stage.Version, ReservationID: p.Stage.ReservationID, Nonce: p.Nonce}).Validate(); err != nil {
		return err
	}
	m, err := ParseObjectMarker(p.Marker)
	if err != nil || !reflect.DeepEqual(m.Metadata(), p.Marker) || m.ActivationEpoch != p.Stage.ActivationEpoch || p.Attributes.Validate() != nil || p.Attributes.Ref.Scope != p.Stage.Scope || p.Attributes.Ref.Digest != p.Stage.Digest || p.Attributes.LogicalBytes != p.Stage.Bytes || p.Attributes.StoredBytes != p.Stage.Bytes || !m.Matches(p.Attributes.Ref) || p.Metageneration <= 0 || p.KeyID == "" || len(p.KeyID) > MaxKeyIDBytes || p.SignedAt.Validate() != nil || p.SignedAt.Before(p.Stage.CreatedAt.Time) || !p.SignedAt.Before(p.Stage.ExpiresAt.Time) {
		return fmt.Errorf("%w: invalid input publication", ErrConflict)
	}
	return nil
}
