package output

import (
	"fmt"
	"reflect"
	"time"

	"github.com/concourse/concourse/hangar"
	"github.com/concourse/concourse/hangar/executioncontrol"
	"github.com/google/uuid"
)

const InputPublicationVersion = "hangar-input/v1"

const MaxInputContentBytes int64 = 256 << 20

// InputStage describes canonical bytes privately staged by the publishing node.
// It is not a publication, a read warrant, or authority to admit a Run. The
// consumer must durably reserve this logical identity before calling publish.
type InputStage struct {
	Version       string                   `json:"version"`
	ReservationID ReservationID            `json:"reservation_id"`
	NodeUID       executioncontrol.NodeUID `json:"node_uid"`
	Scope         hangar.Scope             `json:"scope"`
	Digest        hangar.Digest            `json:"digest"`
	Bytes         int64                    `json:"bytes"`
	CreatedAt     Timestamp                `json:"created_at"`
	ExpiresAt     Timestamp                `json:"expires_at"`
}

func (s InputStage) Validate() error {
	if s.Version != InputPublicationVersion || s.ReservationID.Validate() != nil || s.NodeUID == "" || s.Scope.Validate() != nil || s.Digest.Validate() != nil || s.Bytes <= 0 || s.CreatedAt.Validate() != nil || s.ExpiresAt.Validate() != nil || !s.ExpiresAt.After(s.CreatedAt.Time) || s.ExpiresAt.Sub(s.CreatedAt.Time) > 2*time.Minute {
		return fmt.Errorf("%w: invalid input stage", ErrIncomplete)
	}
	return nil
}

func (s InputStage) ObjectMarker() ObjectMarker {
	return ObjectMarker{ReservationID: s.ReservationID, Scope: s.Scope, Digest: s.Digest, CreatedAt: s.CreatedAt}
}

// InputPublishRequest contains no path, scope or bucket. Nonce is generated by
// the consumer and retained with its logical reservation before object create.
type InputPublishRequest struct {
	Version       string        `json:"version"`
	ReservationID ReservationID `json:"reservation_id"`
	Nonce         string        `json:"nonce"`
}

func (p InputPublishRequest) Validate() error {
	if p.Version != InputPublicationVersion || p.ReservationID.Validate() != nil {
		return ErrIncomplete
	}
	if id, err := uuid.Parse(p.Nonce); err != nil || id == uuid.Nil || id.String() != p.Nonce {
		return ErrIncomplete
	}
	return nil
}

// InputPublication is the publishing node's fresh observation of an exact
// publication, answered over the control plane's mutually authenticated
// connection to that node. The marker may belong to an earlier publication of
// identical bytes. There is no execution, Pod or quiescence witness because an
// upload has none.
type InputPublication struct {
	Stage          InputStage        `json:"stage"`
	Nonce          string            `json:"nonce"`
	Attributes     TreeAttributes    `json:"attributes"`
	Metageneration int64             `json:"metageneration"`
	Marker         map[string]string `json:"marker"`
}

// For checks a publication against the consumer's retained stage and nonce.
// The consumer must also consume that nonce and register its claim in one
// database transaction; this check alone grants no ownership.
func (p InputPublication) For(stage InputStage, nonce string) error {
	if p.Stage != stage || p.Nonce != nonce {
		return fmt.Errorf("%w: the publication answers another stage or nonce", ErrUnauthorized)
	}

	return p.Validate()
}

func (p InputPublication) Validate() error {
	if err := p.Stage.Validate(); err != nil {
		return err
	}
	if err := (InputPublishRequest{Version: p.Stage.Version, ReservationID: p.Stage.ReservationID, Nonce: p.Nonce}).Validate(); err != nil {
		return err
	}
	m, err := ParseObjectMarker(p.Marker)
	if err != nil || !reflect.DeepEqual(m.Metadata(), p.Marker) || p.Attributes.Validate() != nil || p.Attributes.Ref.Scope != p.Stage.Scope || p.Attributes.Ref.Digest != p.Stage.Digest || p.Attributes.LogicalBytes != p.Stage.Bytes || p.Attributes.StoredBytes != p.Stage.Bytes || !m.Matches(p.Attributes.Ref) || p.Metageneration <= 0 {
		return fmt.Errorf("%w: invalid input publication", ErrConflict)
	}
	return nil
}
