package db_test

import (
	"github.com/concourse/concourse/atc"
	"github.com/concourse/concourse/atc/db"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Bounded discovery pagination", func() {
	It("applies visibility and literal text filters before pipeline page limits", func() {
		privateTeam, err := teamFactory.CreateTeam(atc.Team{Name: "private-page"})
		Expect(err).NotTo(HaveOccurred())
		_, _, err = privateTeam.SavePipeline(atc.PipelineRef{Name: "match-hidden"}, atc.Config{}, 0, true)
		Expect(err).NotTo(HaveOccurred())
		visible, _, err := privateTeam.SavePipeline(atc.PipelineRef{Name: "match-public"}, atc.Config{}, 0, true)
		Expect(err).NotTo(HaveOccurred())
		Expect(visible.Expose()).To(Succeed())
		factory := db.NewPipelineFactory(dbConn, lockFactory)
		list, err := factory.PipelinePage(nil, false, privateTeam.Name(), "match", 0, 1)
		Expect(err).NotTo(HaveOccurred())
		Expect(list).To(HaveLen(1))
		Expect(list[0].ID()).To(Equal(visible.ID()))
		list, err = factory.PipelinePage(nil, false, privateTeam.Name(), "%", 0, 1)
		Expect(err).NotTo(HaveOccurred())
		Expect(list).To(BeEmpty())
		list, err = factory.PipelinePage([]string{privateTeam.Name()}, false, privateTeam.Name(), "match", 0, 2)
		Expect(err).NotTo(HaveOccurred())
		Expect(list).To(HaveLen(2))
	})
	It("paginates filtered chronological builds through recent reruns without skipping older matches", func() {
		p, _, err := defaultTeam.SavePipeline(atc.PipelineRef{Name: "filtered"}, atc.Config{Jobs: atc.JobConfigs{{Name: "pick"}, {Name: "ignore"}}}, 0, true)
		Expect(err).NotTo(HaveOccurred())
		job, found, err := p.Job("pick")
		Expect(err).NotTo(HaveOccurred())
		Expect(found).To(BeTrue())
		ignored, _, err := p.Job("ignore")
		Expect(err).NotTo(HaveOccurred())
		first, err := job.CreateBuild(defaultBuildCreatedBy)
		Expect(err).NotTo(HaveOccurred())
		second, err := job.CreateBuild(defaultBuildCreatedBy)
		Expect(err).NotTo(HaveOccurred())
		_, err = ignored.CreateBuild(defaultBuildCreatedBy)
		Expect(err).NotTo(HaveOccurred())
		rerun, err := job.RerunBuild(first, defaultBuildCreatedBy)
		Expect(err).NotTo(HaveOccurred())
		page, pagination, err := p.BuildsFiltered("pick", atc.StatusPending, db.Page{Limit: 1})
		Expect(err).NotTo(HaveOccurred())
		Expect(page).To(HaveLen(1))
		Expect(page[0].ID()).To(Equal(rerun.ID()))
		Expect(pagination.Older).NotTo(BeNil())
		page, pagination, err = p.BuildsFiltered("pick", atc.StatusPending, *pagination.Older)
		Expect(err).NotTo(HaveOccurred())
		Expect(page).To(HaveLen(1))
		Expect(page[0].ID()).To(Equal(second.ID()))
		Expect(pagination.Older).NotTo(BeNil())
		page, _, err = p.BuildsFiltered("pick", atc.StatusPending, *pagination.Older)
		Expect(err).NotTo(HaveOccurred())
		Expect(page).To(HaveLen(1))
		Expect(page[0].ID()).To(Equal(first.ID()))
	})
	It("continues by identity when live members are inserted, removed or change status", func() {
		p, _, err := defaultTeam.SavePipeline(atc.PipelineRef{Name: "live-page"}, atc.Config{Jobs: atc.JobConfigs{{Name: "unit"}}}, 0, true)
		Expect(err).NotTo(HaveOccurred())
		job, found, err := p.Job("unit")
		Expect(err).NotTo(HaveOccurred())
		Expect(found).To(BeTrue())
		first, err := job.CreateBuild("")
		Expect(err).NotTo(HaveOccurred())
		second, err := job.CreateBuild("")
		Expect(err).NotTo(HaveOccurred())
		third, err := job.CreateBuild("")
		Expect(err).NotTo(HaveOccurred())
		page, next, err := p.BuildsFiltered("unit", atc.StatusPending, db.Page{Limit: 1})
		Expect(err).NotTo(HaveOccurred())
		Expect(page[0].ID()).To(Equal(third.ID()))
		Expect(next.Older).NotTo(BeNil())
		_, err = dbConn.Exec("DELETE FROM builds WHERE id=$1", second.ID())
		Expect(err).NotTo(HaveOccurred())
		_, err = dbConn.Exec("UPDATE builds SET status='succeeded' WHERE id=$1", first.ID())
		Expect(err).NotTo(HaveOccurred())
		newest, err := job.CreateBuild("")
		Expect(err).NotTo(HaveOccurred())
		page, _, err = p.BuildsFiltered("unit", atc.StatusPending, *next.Older)
		Expect(err).NotTo(HaveOccurred())
		Expect(page).To(BeEmpty())
		page, _, err = p.BuildsFiltered("unit", atc.StatusPending, db.Page{Limit: 1})
		Expect(err).NotTo(HaveOccurred())
		Expect(page[0].ID()).To(Equal(newest.ID()))
	})

})
